### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by addie-tyc** [coding-coworking-club/basic-python-2020-fall#10]
## 提交連結

https://judge.ccclub.io/status/3e792c2eb8e9cd22725752d14d54e293

## 程式碼

```python
s = input()

s_list = []
for i in range(len(s)):
    if s[i].isalpha():
        s_list.append(s[i])
        
s = "".join(s_list)
your_dict = {}
for i in range(len(s)):
    count = 0
    for j in range(len(s)):
        if s[i]==s[j]:
            count += 1
    your_dict[s[i]] = count

ans = []
for i in range(len(your_dict)):    
    ans.append(str(list(your_dict.keys())[i]) + str(list(your_dict.values())[i]))
print(" ".join(sorted(ans)))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/65952631/93714730-3a999a80-fb97-11ea-858c-7dc26cfe289b.png)

## 問題描述

在 jupyter 上的輸出跟答案一樣，
不曉得是哪裡沒注意到，
請助教大大開示，
感謝辛苦了！

**Comment by tcwang76** [comment]
注意英文大小寫被視為同一個字母噢!
(這題答案應該是以小寫英文為主)
例如"A"、"a"同樣被視為"a"，
所以如果輸入的字串為"An apple"，
答案應該要是a2 e1 l1 n1 p2

**Comment by addie-tyc** [comment]
Got it!感謝助教
