### ISSUE TITLE
[Homework 1] 小明買宵夜

### ISSUE THREAD

**Issue by ambre915** [coding-coworking-club/basic-python-2020-fall#101]
## 程式碼

```python
menu = input().split()
pay = input().split()
mon = int(input())

for i in range(0, len(pay)):
    for j in range(i+1, len(pay)):
        if i == j:
            break
        elif pay[i] + pay[j] == mon:
            print(menu[i], menu[j])
```

## 問題描述

試著把我的codes放在之前課堂教的visualization tool上
發現codes在jupyter可以跑但都沒有結果的原因好像是
一直沒有執行到print那一行
感覺條件應該沒有寫錯
不知道是哪裏出問題了
還請助教開示，感謝！

祝助教中秋節快樂
月餅烤肉吃多都不胖 ヽ(●´∀`●)ﾉ

**Comment by yeutong** [comment]
因為 `pay` 裡面每個元素是字串，但 `money` 是數字，所以怎麼加都不會相等噢

**Comment by ambre915** [comment]
> 因為 `pay` 裡面每個元素是字串，但 `money` 是數字，所以怎麼加都不會相等噢

已解決，謝謝！
