### ISSUE TITLE
[Homework 1]  出題目

### ISSUE THREAD

**Issue by aiffel108131** [coding-coworking-club/basic-python-2020-fall#102]
## 提交連結

https://judge.ccclub.io/status/312684ef348347d3e3eb67a1668e579e

## 程式碼

```python
Stark_battery, Blue_battery, clothes, battery, = int(input()), int(input()), int(input()), int(input())
Blue  = (8*clothes - battery + Stark_battery + Blue_battery)/4
if (Blue==int(Blue)) and (clothes - Blue > 0)  and (Blue > 0):
    print("True")
else:
    print("False")

```

## 問題描述

批改系統過不了，應該是條件判斷少了什麼，但一直找不出來

**Comment by yeutong** [comment]
`Blue  = (8*clothes - battery + Stark_battery + Blue_battery)/4`  可以大概說明一下這行在做什麼嗎？

**Comment by aiffel108131** [comment]
> `Blue = (8*clothes - battery + Stark_battery + Blue_battery)/4` 可以大概說明一下這行在做什麼嗎？
從已知條件(clothes,battery,Blue_battery,Stark_battery)計算出有幾套蝙蝠裝
Blue + Stark =clothes    --1
4*Blue + 8*Stark + (Blue_battery + Stark_battery) = battery    --2
1代入2
4*Blue + 8*(clothes - Blue) + (Blue_battery + Stark_battery) = battery
整理一下
Blue = battery - 8*(clothes - Blue) - (Blue_battery + Stark_battery)
Blue = (8*clothes + Stark_battery + Blue_battery - battery) / 4

**Comment by yeutong** [comment]
感覺你好像有點誤會題意了，鋼鐵裝跟蝙蝠裝的額定備用電池數是會改變的
第二個方程式應該是
Blue_battery ＊ Blue + Stark_battery ＊ Stark = battery

**Comment by aiffel108131** [comment]
謝謝,我了解了
