### ISSUE TITLE
[General] Judge系統無法出現最新的status

### ISSUE THREAD

**Issue by tziyingchen** [coding-coworking-club/basic-python-2020-fall#103]
## 程式碼

```python

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/71817508/94798779-ab04af00-0414-11eb-81d3-045f2562d60b.png)

## 問題描述
10/1寫的答案沒有出現在status中，所以想發問為什麼一直是wrong answer也無法找到連結發問QQ
最新的status是9/30的紀錄

**Comment by yeutong** [comment]
因為 contest 的記錄是分開的 (畢竟 contest 可以用密碼鎖起來) 
先點進 contest 找到該次作業，再點右側的 submission 應該就會有了～
