### ISSUE TITLE
[General] 4-3：三角形

### ISSUE THREAD

**Issue by Chiahsin13** [coding-coworking-club/basic-python-2020-fall#106]
## 提交連結

https://judge.ccclub.io/status/42cc050f533ae8111a106f51a7f6843f

## 程式碼

```python
a=int(input())
b=int(input())
c=int(input())
if a<=0 or b<=0 or c<=0:
    print("False'')
elif a%1 != 0 or b%1 != 0 or c%1 != 0:
    print("False")
elif a+b>c:
    print("True")
```

## 問題描述

連結中的程式碼，有在jupiter notebook測試過，但在Judge中無法審核通過，所以我想是不是「正整數」的問題，所以又重新寫了一次程式碼，但在jupiter notebook一直錯誤，想請問可否提點一下，謝謝答覆的任何人！

**Comment by Neptune2901** [comment]
3
2
1
不會形成三角形但跑出來是True唷！
可能要多加一些條件
