### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by tziyingchen** [coding-coworking-club/basic-python-2020-fall#107]
## 提交連結

https://judge.ccclub.io/status/5a649ff50d4690517c81b144473a77be
## 程式碼

```python
a= int(input())
for upper in range(1,a+1):
    print(' '*(a-upper),'*'*(2*upper-1))
for lower in range(a-1,0,-1):
    print(' '*(a-lower),'*'*(2*lower-1))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/71817508/94806378-6d0d8800-0420-11eb-8d9a-1906e4e65202.png)

## 問題描述

在Jupyter上測試都可以，也確認過極端值，參考其他同學問題已去除右側的多於空格
不知道為什麼還是wrong answer QQ

**Comment by yeutong** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)將格式修正噢，程式碼要貼在兩個 ``` 中間，然後請附上提交連結

你的反而是左邊會有多的空格，注意在菱形最長的那排最左側是`*`，沒有空格。

**Comment by tziyingchen** [comment]
謝謝助教 我解出來了
但是不是很懂為什麼在print裡面用 ' , ' 作為空格和 * 的連接會和用 ' + ' 的有差異
我用逗號的時候在output前面都會多出額外一個空格
但是用加號的時候就不會

```python
#用逗號會多空格
a= int(input())
for upper in range(1,a+1):
    print(' '*(a-upper),'*'*(2*upper-1))
for lower in range(a-1,0,-1):
    print(' '*(a-lower),'*'*(2*lower-1))

#用加號不會多空格
a= int(input())
for upper in range(1,a+1):
    print(' '*(a-upper)+'*'*(2*upper-1))
for lower in range(a-1,0,-1):
    print(' '*(a-lower)+'*'*(2*lower-1))
```

**Comment by chun9425** [comment]
用加號的話是對兩個字串做串接，
也就是說將兩個字串連接在一起之後再印出來，
所以中間不會有空格。

在 print 裡面用逗號的話是要在同一個輸出指令中輸出多個內容，
按照 python 的預設，
不同的內容中間會空一格，
如果要更改預設就要使用 sep，
有點忘記的話可以回去複習一下輸出的部分喔~

**Comment by tziyingchen** [comment]
謝謝助教
