### ISSUE TITLE
[General] 2-1：數字及字串和

### ISSUE THREAD

**Issue by Cappucino2419** [coding-coworking-club/basic-python-2020-fall#11]
## 程式碼

```python
a = 8
b = 7
print(a + b)
print(str(a)+ str(b))
```

## 問題描述

不懂錯在哪裡 在電腦中跑出來是對的

**Comment by chun9425** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)依規定附上提交連結

a 跟 b 的值不是固定的，
而是要讓使用者輸入，
如果照你的程式碼，
第二筆測資就不會過了
