### ISSUE TITLE
[Homework 1]小明寫論文 

### ISSUE THREAD

**Issue by muchiu** [coding-coworking-club/basic-python-2020-fall#114]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203105

## 程式碼

def special_title(x):
    a= x[0].upper() + x[1:]
    return a

x = input()
words = x.split()
word=[]

for i in range (0,len(words)):
    a=special_title(words[i])
    word.append(a)

lst=[word[0]]
for i in range (1,len(word)):
    if (word[i] == "To" or word[i] == "A" or word[i] == "An" or word[i] == "The" or word[i] == "From" or word[i] == "For" or word[i] == "Of" or i == "And" or i == "In"):
        word[i]=word[i].lower()
    else:
        word[i]
    lst.append(word[i])

s = " ".join(lst)
print(s)

## 錯誤訊息
wrong answer

## 問題描述

有參考#22 避開中英混雜情形，
方式: 透過def 去定義新的function 讓大寫發生在每個單字第一個位置。

也確認過系統上兩個sample是沒問題的，想麻煩助教給予提點。

**Comment by alexypdu** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!
