### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by rubiiii** [coding-coworking-club/basic-python-2020-fall#116]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203101

## 程式碼

a = int(input())
b = range(1,a+1)

c = [2*i-1 for i in b]
for x in c:
    print('{:^10}'.format(x*'*'))
    
d = range(1,a)
e = [2*i-1 for i in d]
e.sort(reverse=True)
for i in e:
    print('{:^10}'.format(i*'*'))

## 問題描述

我在jupyter上試input/output，都有出現正確菱形圖案，
但在judge繳交作業卻被說是錯誤答案，想請問是哪裡錯誤，或是該往哪個方向去想!!
再麻煩助教們撥空幫我解答~謝謝

**Comment by chun9425** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!
