### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by r07341020** [coding-coworking-club/basic-python-2020-fall#117]
## 提交連結
https://judge.ccclub.io/status/1db5a138e0e87294dcfecdf196b71e7a

## 程式碼
a = " * "

b = " "

s2 = int(input())

for i in range(1, 2 * s2, 2):
   
      j = (2 * s2 - i - 1) // 2

      print(b * j, a * i)

for k in range(2 * s2-3, 0, -2):

       l = (2 * s2 - k - 1) // 2

       print(b * l, a * k)

```python

```

## 錯誤訊息
Wrong Answer

## 問題描述
在jupyter、compiler上都測試成功，可是提交到批改系統的時候卻顯示Wrong Answer，不太清楚為什麼會這樣。

**Comment by chun9425** [comment]
你輸出每一行前面都多了一個空格
