### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by nclare** [coding-coworking-club/basic-python-2020-fall#118]
## 

https://judge.ccclub.io/status/3d37f163320266e16793744e6c0c6a6b

## 程式碼

    
```

a= int(input()) 
b= int(input())
clothes=int(input())
sum=int(input())

X=(sum-clothes*b)/(a-b)
Y=(a*clothes-sum)/(a-b)
mix=X*Y
if mix%1==0 and X>0:
    if Y>0:
        if a!=b:
            print("True")
        else:
            print("False")
    else:
        print("False")
else:
    print("False")

```

## 問題描述

 在python上回答都正確，但批改系統顯示runtime error，自己檢查了幾遍仍沒發現錯誤><

**Comment by yeutong** [comment]
提交連結放錯了，這個是題目的連結，請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)修正噢

想想看 a = b 的情況

**Comment by nclare** [comment]
助教您好
  謝謝提醒連結錯誤！我已經更正，另外我有考慮到a=b時會沒有答案，所以有設a!=b 才會true，不確定助教的意思是這個設定是錯的嗎~?

**Comment by yeutong** [comment]
你考慮的沒錯，但程式執行上會出現一些錯誤
可以在 jupyter 上測 a = b 的測資，然後看錯誤訊息就知道為什麼了
