### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by f89234** [coding-coworking-club/basic-python-2020-fall#119]
## 程式碼

```python
n = int()
for i in range (1,n+1):
    print(" "*(n-i)+"*"*(2*i-1))
for i in reversed(range(1,n)):
    print(" "*(n-i)+"*"*(2*i-1))
```

## 問題描述

將數字代入 n = int(2) 及 n = int(4)
放進 https://repl.it/languages/python3 網站跑，可以跑出跟作業一樣的圖形，
但將程式碼放在judge 系統跑，卻是wrong answer，
是不是n的型態設定錯了？

**Comment by chun9425** [comment]
資料型態是設定為 int 沒有錯喔~
這邊題目是要讓使用者輸入菱形的邊長，
再依據使用者的輸入印出菱形，
所以在一開始的時候要先用 input 讓使用者輸入資料，
而不是自己將 sample input 的內容填進去 int() 裡面喔

**Comment by f89234** [comment]
好的，謝謝您
