### ISSUE TITLE
[General] 2-2：偶數

### ISSUE THREAD

**Issue by Cappucino2419** [coding-coworking-club/basic-python-2020-fall#12]
## 程式碼

```python
  a = 20
  print(a % 2 == 0)
```

## 問題描述

不懂錯誤所在

**Comment by chun9425** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)依規定附上提交連結

a 的值不是固定的，
而是要讓使用者輸入，
如果照你的程式碼，
第二筆測資就不會過了

**Comment by Huang-0000** [comment]
n = int(input())
n%2 ==0 

我這樣為什麼也錯？？

**Comment by chun9425** [comment]
你沒有把最後的答案用 print 輸出
