### ISSUE TITLE
[General] 8-4：最大公因數

### ISSUE THREAD

**Issue by JamieTai-creater** [coding-coworking-club/basic-python-2020-fall#120]
## 提交連結
https://judge.ccclub.io/status/8eaf0a3df79f22e349732d759e0a6f8e

## 程式碼

```python
l1=[int(num) for num in input().split(" ")]
l2=[int(num) for num in input().split(" ")]
def gcd(l1, l2):
    temp=0
    num=0
    numlist=[]
    for i in range(0,len(l1)):
        if l1[i]<l2[i]:
            temp=l1[i]
        else:
            temp=l2[i]
        for k in range(1,temp):
            if l1[i]%temp==0 and l2[i]%temp==0:
                num=temp
                break
            else:
                temp-=1
        numlist.append(num)
    return numlist
print(gcd(l1, l2))
```

## 問題描述
在jupyter notebook上用sample跑出來是正確的，想不到還有什麼細節沒考慮到

**Comment by winnywu508** [comment]
當list 1 = 3 3 list 2 = 5 5 
這段邏輯就append到num (用這個example就是0, 而不是1)
你再看一下怎麼順邏輯

for k in range(1,temp):
            if l1[i]%temp==0 and l2[i]%temp==0:
                num=temp
                break
            else:
                temp-=1
