### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by hazel-ys-lin** [coding-coworking-club/basic-python-2020-fall#122]
## 提交連結

https://judge.ccclub.io/status/5bd2d4244a5d6577132162e1aa9e96fb

## 程式碼

```python
i_bat, b_bat, cos, total_bat = int(input()), int(input()), int(input()), int(input())
if i_bat - b_bat ==0:
    if cos == total_bat / i_bat and i_bat >0:
        print('True')
    else:
        print('False')
else:
    x = (total_bat - (cos * b_bat)) / (i_bat - b_bat)
    y = ((i_bat * cos) - total_bat)  / (i_bat - b_bat)
    if x >= 0 and y >= 0 and x == int(x) and y ==int(y):
        print('True')
    else:
        print('False')
```

## 問題描述

參考了各個關於出題目的issue，也考慮了i_bat == b_bat的情況，也用i_bat == b_bat的測資跑過，但在編譯器沒有問題，Judger持續顯示Wrong Answer，不知道有沒有沒考慮到的情況或是測資可以讓我再試試看的，謝謝助教

**Comment by misvap** [comment]
嗨同學！我不是助教，想問你第2行到第6行你的邏輯是什麼呢？（這個地方我看不懂

我自己的做法是：對 i_bat - b_bat ==0 的狀況再分別算次一次它們的 x, y 值，然後再檢查是否為正整數。

如果不想檢查正整數的部分重複寫兩次的話，可以拆成兩個 if-else 寫（非 nested），一個寫不同情況下的 x, y怎麼求，另一個寫檢證是否為正整數。即把不同的步驟拆開，未來要優化也比較不會牽一髮動全身。

希望有幫到你，加油

**Comment by hazel-ys-lin** [comment]
哈囉同學你好～謝謝你的建議，我把i_bat - b_bat ==0以下的判斷式刪除之後就成功了

雖然成功之後我還是有個疑問，也就是以以下的程式碼成功之後：
```
i_bat, b_bat, cos, total_bat = int(input()), int(input()), int(input()), int(input())
if i_bat - b_bat ==0:
    print('False')
else:
    x = (total_bat - (cos * b_bat)) / (i_bat - b_bat)
    y = ((i_bat * cos) - total_bat)  / (i_bat - b_bat)
    if x >= 0 and y >= 0 and x == int(x) and y ==int(y):
        print('True')
    else:
        print('False')
```
如此一來如果每套鋼鐵裝的電池數量和每套蝙蝠俠裝的電池數量如果相等，儘管符合題目給的條件，仍會被判斷成False

以我自己拿來測試的(8, 8, 2, 16)為例，在我修改之前的code上為True，在系統通過的code會顯示為False，
因此關於第2行到第6行的寫法，我原先才會將a = b 的情況帶入x, y的關係式，得出若a = b，cos 必定等於 total_bat / i_bat寫進判斷式裡（雖然這樣就等於重複再判斷一次）

原先的想法是：在a = b 的情況下還是有可能有正整數解，有可能不只一組，但在給定的測資數字是有限的情況下，正整數解的數量並不會有無限多組解（考慮到題目的前提是「鋼鐵人與蝙蝠俠的裝備數量都必須為正整數，也就是**若驗算出的答案為非正整數、0、無解、無限多解**，該題目都不合格，輸出 False。」因此我才會想說是不是需要將「並非無解也非無限多組解而是多組解」的情況也考慮進去）

因此可能是我誤會題目的意思，但還是想問可不可以知道同學在i_bat - b_bat ==0的情況下是怎麼得出x, y的判斷式的？
