### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by gigatt-jm** [coding-coworking-club/basic-python-2020-fall#128]
## 提交連結

https://judge.ccclub.io/status/4dfd617d8eb3b47e467da752661c17aa

## 程式碼

```python
# 小明寫論文
sentence = input().split()
lower_list = ['to', 'a', 'an', 'the', 'from', 'for', 'or', 'and', 'in']
for word in sentence:
    if (word not in lower_list) or (word == sentence[0]) or (word == sentence[-1]):
        word = word[0].upper() + word[1:]
    print(word, end = ' ')
```

## 錯誤訊息

Wrong Answer

## 問題描述

助教們好，目前這樣的回答是參考助教的hint檔案所寫，大部分的input好像出來的output是對的，但還是wrong answer。不知道哪裡漏掉考慮了？非常感謝！！！

**Comment by misvap** [comment]
嗨同學，我不是助教，想問你第4行到第7行的程式碼，你的邏輯是什麼？

然後，我丟“an little CAE dOG IN” 的 input 進去，出來的 output 格式不對喔

**Comment by gigatt-jm** [comment]
你好！謝謝你！這樣看來我是沒考慮到非首字母大寫的情況～解決了～非常感恩！
