### ISSUE TITLE
[Homework 1] 小明買宵夜

### ISSUE THREAD

**Issue by Lienchen-cpu** [coding-coworking-club/basic-python-2020-fall#130]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203104

## 程式碼

items = []
prices = []
money = int(input())

foundItemCombination = False

for i in range(len(items)):
    if foundItemCombination: 
        break
    for j in range(i+1,len(items)):
        if (int(prices[i])+int(prices[j]) == money ):
            print(items[i],items[j])
            foundItemCombination = True
            break

## 錯誤訊息

Runtime error 

## 問題描述

測試過了code 應該沒問題，麻煩助教幫我看一下，謝謝

**Comment by alexypdu** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!
