### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by r07341020** [coding-coworking-club/basic-python-2020-fall#131]
## 提交連結
https://judge.ccclub.io/status/fa583185c460bae98243bbac0a5556d4

## 程式碼
num = [ ]

while True:

       n = input().replace(",", ' ')

       if num == "end":

            break

        new = num. append(int(n)) 

new = num. append(int(n))
n = 0

total = 0

for i in range(len(new)):

      total = total + new[i]

      i = i + 1

print(total)

```python

```

## 錯誤訊息
![擷取](https://user-images.githubusercontent.com/71606820/94928788-c647eb00-04f6-11eb-8551-eff16f7da959.PNG)

## 問題描述
這題先做到一半，但想說先檢查到new = num. append(int(n))那一行時似乎一直有發生錯誤，所以想先請教助教們、同學們是不是自己語法或邏輯有點錯誤><，再麻煩大家了 謝謝~~

**Comment by misvap** [comment]
嗨同學！我不是助教所以我看不到你連結內的程式碼，因為你貼的格式不是很好讀，我盡量分享我的想法～

invalid literal for int() with base 10: "...."

這個 error 的意思是，你想轉成 integer 的內容並不是數字，所以 compiler 無法識別，也就沒辦法後續轉成 int（整數） 了。從錯誤訊息來看，你的 n 輸入的 value 是 “end” 的時候，它並不是數字，所以沒辦法被轉成 int 型態。

建議參考以下連結張貼 issue 的教學（這樣比較好幫你看喔）
https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29

**Comment by huaitzu** [comment]
num是append所有輸入數字的list，裡面有很多個項目，而"end"是個字串，所以是無法用num == "end"來判斷是否結束while迴圈，這部分要再重新設計。

append這個指令是不需要指派給變數才能執行的，可以直接num. append(int(n))即可，詳細可參考：https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-c15425c12009

另外，for迴圈是迭代的，舉例來說 for i in range(4)的 i ，在for迴圈內程式碼被執行4次的過程中，i 依序為0, 1, 2, 3，因此不用另外寫 i = i + 1。還有你是把輸入的那些數字儲存在num這個list裡，因此最後要進行加總的時候也是要從num這個list去找數字出來相加，別忘了最後答案還要加上`,`。

建議你再去閱讀一下關於迴圈的規則後再來重新思考這題喔~
https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-4990a5757aa6
