### ISSUE TITLE
[General] 7-1：長方星

### ISSUE THREAD

**Issue by Huang-0000** [coding-coworking-club/basic-python-2020-fall#136]
## 程式碼

```python
l = int(input())
w = int(input())
for l in range(l, l+1):
    print("*" * l, ("\n" + "*" * l) * (w-1))

```

## 問題描述

在jupyter 上測試可以跑吃來題目要求，但judge顯示wrong anwser。

**Comment by Huang-0000** [comment]
提問的格式跑掉了

l = int(input())
w = int(input())
for l in range(l, l+1):
    print("*" * l, ("\n" + "*" * l) * (w-1))

**Comment by Huang-0000** [comment]
l = int(input())
w = int(input())
for l in range(l, l+1):
    print('*' * l, ('\n' + '*' * l) * (w-1))

**Comment by Huang-0000** [comment]
抱歉格式一直跑掉，所以我截圖程式碼。
`l = int(input())
w = int(input())
for l in range(l, l+1):
    print('*' * l, ('\n' + '*' * l) * (w-1))`

**Comment by misvap** [comment]
嗨同學！我不是助教，跟你分享一下我的想法：

你印出來的結果有多空白鍵喔！ 原因是 print(a, b) 時，印出的結果會是： a b （即 a 與 b 之間會有一個空白鍵，這是default的）。如果不想有這格空白鍵的話，可以採用下述其中一種用法：
1. print(a+b) 
2. print(a, b, sep="")

就可以印出 ab （即中間沒有空白鍵）

**Comment by Huang-0000** [comment]
了解，謝謝你～
