### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by enn-lu** [coding-coworking-club/basic-python-2020-fall#137]
## 提交連結
[https://judge.ccclub.io/contest/4/problem/203102](url)

## 程式碼

```python
ib=int(input())
bb=int(input())
t=int(input())
bt=int(input())
x=int((bt-(bb*y))/ib)
y=int(t-x)
if  x>0 and y>0:
    print("true")
    elife (x*y)>0
    print("true")
else:
    print("fulse")
```

## 錯誤訊息
Runtime Error

## 問題描述
數學算式應該沒有問題，但是X跟Y不能帶入，出來的答案都是錯誤

**Comment by Kevinweisl** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!
