### ISSUE TITLE
[General] 8-3：及格門檻

### ISSUE THREAD

**Issue by StarCat0928** [coding-coworking-club/basic-python-2020-fall#139]
## 提交連結

https://judge.ccclub.io/status/bdc21333422e56209e4419d4da7d0ca9

## 程式碼

```python
s1 = input()
s3 = int(input())
s2 = s1.split()

def threshold(s1, s2):
    print("[", end="")
    for i in range(len(s1)):
        if(int(s1[i]) >= s2):
            print("True, ", end="")
        elif(int(s1[i]) < s2):
            print("False, ", end="")
    print("\b\b]", end="")            
    
threshold(s2, s3)
```

## 問題描述

以上的程式碼我在Spyder上運行時輸出結果皆與judge上的輸出範例完全相同，我也測試了其他的範例，也都輸出正確，但不知為何submit完後會跑出Wrong Answer。這題我主要的想法就是我將輸入的字串先split，之後一個一個與輸入的門檻做比較，一開始先輸出一個「[」，之後若大於等於門檻則輸出「True, 」，若小於門檻則輸出「False, 」，最後再使用「\b\b]」先刪掉多餘的「, 」再加入缺少的「]」，輸出結果就會跟範例的一模一樣，請問這樣的想法哪裏出了問題，還是要把輸出結果換成list串列在輸出才正確呢，若是如此可以請助教教我如何宣告並輸出串列。

**Comment by misvap** [comment]
嗨同學！我不是助教，一些想法和你分享～
1. 可以使用 list_name = [] 的方式宣告一個空的 list，之後 print(list_name) 即可印出該 list
2. 你 print() 的結果，其型態為 string，但題目要的結果是 print() 一個 list（參考第一點），並且該 list 的 item 型態為 boolean 的 True/ False，而非"True"/ "False"（這個的型態是 string）。

**Comment by StarCat0928** [comment]
我試過宣告一個空串列，但要在其串列指定值時，會有錯誤訊息寫出超出串列索引範圍，這問題要如何解決呢？

**Comment by StarCat0928** [comment]
我想我的問題應該是因為我沒有指定串列的長度，但我也不知道如何指定

**Comment by misvap** [comment]
你可以貼程式碼讓我參考嗎？這樣講我比較難推測你的問題點，目前想到的原因是你的迴圈初始值跟最後一個值設定要再想一下

**Comment by StarCat0928** [comment]
s1 = input()
s3 = int(input())
s2 = s1.split()

def threshold(s1, s2):
    print("[", end="")
    for i in range(len(s1)):
        if(int(s1[i]) >= s2):
            print("True, ", end="")
        elif(int(s1[i]) < s2):
            print("False, ", end="")
    print("\b\b]", end="")            
    
threshold(s2, s3)

**Comment by StarCat0928** [comment]
1 = input()
s3 = int(input())
s2 = s1.split()

def threshold(s1, s2):
    lst1 = ""
    for i in range(len(s1)):
        if(int(s1[i]) >= s2):
            lst1 = lst1 + "True" + " "
        elif(int(s1[i]) < s2):
            lst1 = lst1 + "False" + " "
    lst = [bool(num) for num in lst1.split()]
    print(lst)            
    
threshold(s2, s3)

**Comment by StarCat0928** [comment]
我有試過用字串串列轉換成布林串列，但輸出結果全部會變成True

**Comment by misvap** [comment]
同學拍謝，可以比照你第一則的格式那樣貼嗎？阿捏真的比較難看懂...

**Comment by StarCat0928** [comment]
```python
s1 = input()
s3 = int(input())
s2 = s1.split()

def threshold(s1, s2):
    lst1 = ""
    for i in range(len(s1)):
        if(int(s1[i]) >= s2):
            lst1 = lst1 + "True" + " "
        elif(int(s1[i]) < s2):
            lst1 = lst1 + "False" + " "
    lst = [bool(num) for num in lst1.split()]
    print(lst)            
    
threshold(s2, s3)
```

**Comment by StarCat0928** [comment]
我的想法是用字串的方式輸出True和False(中間用空格分開)，然後在用split分開然後全部轉換為布林值，但結果會全部變True

**Comment by misvap** [comment]
你的 s1, s2, s3 分別代表什麼哇？

**Comment by StarCat0928** [comment]
s1是輸入的值，s2是s1 split過的串列(因為s1會有空格)，s3是通過門檻

**Comment by misvap** [comment]
那你在 def 裡面的s1, s2 也是這個意思嗎？

**Comment by StarCat0928** [comment]
那只是剛剛好而以，真正會做用到的引數會是s2跟s3

**Comment by StarCat0928** [comment]
def裡的變數是我設定的區域變數

**Comment by StarCat0928** [comment]
這不會影響def函式外面的變數

**Comment by misvap** [comment]
```python
s1 = input()
s3 = int(input())
s2 = s1.split()
```
這個部分應該要寫在 function 裡面，因為這是吃進來的值，你再對它做處理，原因是我們不太可能叫使用者自己做好一個字串再丟給我們。然後變數的命名建議統一，會比較好讀。

**Comment by StarCat0928** [comment]
Ok，我試試看

**Comment by misvap** [comment]
然後 lst1 = "" 的地方可以直接用一個空 list 去接，後面就用 .append() 的方式把值寫進來，就不用再花一個步驟把 string 轉成 list

**Comment by StarCat0928** [comment]
Ok了，謝謝你
