### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by er258er258** [coding-coworking-club/basic-python-2020-fall#140]
## 提交連結

https://judge.ccclub.io/status/3f92a8299814572545918f693ca214c0

## 程式碼

i = int(input( ))
b = int(input( ))
c = int(input( ))
d = int(input( ))
  
if i - b == 0 or b - i == 0: 
    print("False")
else:
    ans_y = (i * c - d) / (i - b)
    ans_x = (b * c - d) / (b - i)
    if ans_y == int(ans_y) and ans_x == int(ans_x) and ans_x > 0 and ans_y > 0:
        print("Ture")
    else:
        print("False")

```python

```

## 問題描述

主要已經設定分母不得為0，且答案為整數並大於0，不知為何還是wrong answer，因此想請教一下助教

**Comment by misvap** [comment]
嗨同學！我不是助教，跟你分享一下我的想法：
1. i == b 的狀況還是可以求出符合規定的解的，所以這裡的結果不會是印出"False"喔！建議可以自己帶值進去算算看
2. i == b 的情況下，ans_y 和 ans_x 可以再想一下它們會變成什麼

**Comment by alexypdu** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!
