### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by sandy273040** [coding-coworking-club/basic-python-2020-fall#141]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203101

## 程式碼

```python

```
a=int(input())
i=0
v=1
b=str("*")
s=str(" ")
s_n=a-1 #要在第a排的空格是0要多扣一格
s_n1=0
for i in range(1,a,1): #行數 ＃第一行到第a-1行
    print(s * s_n,b*v)
    v=v+2 #星星數目
    i=i+1 #行數增加
    s_n=s_n-1 #空格數目
for i in range(a,0,-1): #行數反過來 #第a行到第一行 
    print(s * s_n1,b*v)
    v=v-2
    i=i+1
    s_n1=s_n1+1

## 問題描述

在jupyter notebook 可以印出邊長正確的菱形，輸入0也沒有跑出菱形

程式的思路：a是欲輸入的數字、b是星星、s是空格、s_n是第一個迴圈空格數量的變數、s_n1是第二個迴圈的空格數量的變數
然後分成兩個迴圈，一個行數星星數增加且空格遞減至零，另一個回圈相反，但是設定第一個回圈只跑到第a-1行，第二個回圈從第a行開始跑遞減星星

想請問助教還有哪裡沒有考慮到嗎？

**Comment by alexypdu** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝！
