### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by tziyingchen** [coding-coworking-club/basic-python-2020-fall#142]
## 提交連結

https://judge.ccclub.io/status/f197fd6cc1b9f0e345dc5a749a83fd5c
## 程式碼

```python
for word in sentence:
    if (word not in lower_case):
        word = word[0].upper() + word[1:]        
    elif word == sentence[0]:
        word = word[0].upper() + word[1:]
    elif word == sentence[-1]:
        word = word[0].upper() + word[1:]
```

## 問題描述

助教好~ 我已經解答出這題 但是在答題過程中有一點我感覺自己是嘗試出來的
不知道為什麼原本的方法不行
我原本寫
```python
for word in sentence:
    if (word != in lower_case)
```
或者是
```python
for word in sentence:
    if (word in lower_case == False)
```
句子中的單詞都無法順利變成大寫開頭
想請問這是為什麼呢

**Comment by alexypdu** [comment]
> 助教好~ 我已經解答出這題 但是在答題過程中有一點我感覺自己是嘗試出來的
> 不知道為什麼原本的方法不行
> 我原本寫
> 
> ```python
> for word in sentence:
>     if (word != in lower_case)
> ```
`a != b` 是判斷 a, b 是否相同、`a in b` 是判斷 b 是否包含 a，兩者混用為語法錯誤。
> 
> 或者是
> 
> ```python
> for word in sentence:
>     if (word in lower_case == False)
> ```
`==` 在一句話中比 `in` 優先（先乘除後加減的概念），所以會先判斷 `lower == False` 得到 `False` 再變成判斷 `word in False`
> 
> 句子中的單詞都無法順利變成大寫開頭
> 想請問這是為什麼呢
