### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by Chennwei** [coding-coworking-club/basic-python-2020-fall#143]
## 提交連結

https://judge.ccclub.io/status/d40263413089e0ebcab0401a6e9cbf80

## 程式碼

```python
#x鋼鐵裝數量 y蝙蝠裝數量
#x + y = c
#a * x + b * y = d
#(b - a) * y = d - a * c
#y = (d - a * c) / (b - a)
#(a - b) * x = d - b * c
#x = (d - b * c) / (a - b)

a = int(input())
b = int(input())
c = int(input())
d = int(input())

if (a - b) == 0:
    print("False")
else:
    ans_x = (d - b * c)/(a - b)
    ans_y = (d - a * c)/(b - a)
    if  ans_x == int(ans_x) & ans_y == int(ans_y) & ans_x > 0 & ans_y > 0:
        print("True")
    else:
        print("False")

```

## 問題描述

想請問我已經把整數條件、必為正整數條件、還有分母不為0條件放進去了
但我在jupyter上面跑input1的時候會出現Type Error
不曉得是哪個部分出了問題

**Comment by alexypdu** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝！

**Comment by Chennwei** [comment]
你好，請問這樣的排版是否正確呢？

**Comment by alexypdu** [comment]
@Chennwei 能否附上 **Type Error** 的詳細訊息？

**Comment by Chennwei** [comment]
我把input1丟進去jupyter後出現這串：
TypeError                                 Traceback (most recent call last)
<ipython-input-17-d0a0cb9d13c9> in <module>
     17     ans_x = (d - b * c)/(a - b)
     18     ans_y = (d - a * c)/(b - a)
---> 19     if  ans_x == int(ans_x) & ans_y == int(ans_y) & ans_x > 0 & ans_y > 0:
     20         print("True")
     21     else:

TypeError: unsupported operand type(s) for &: 'int' and 'float'

**Comment by alexypdu** [comment]
邏輯判斷 **且** 要用 `and` 而不是 `&`

**Comment by Chennwei** [comment]
謝謝助教，後來發現問題是在這個部分：
if  ans_x == int(ans_x) & ans_y == int(ans_y) & ans_x > 0 & ans_y > 0:
ans_x == int(ans_x) 以及ans_y == int(ans_y)沒有括弧起來，這個括弧起來就正確了，使用&也沒有問題。
