### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by tmousecello** [coding-coworking-club/basic-python-2020-fall#147]
## 程式碼

a=int(input())
b=int(input())
c=int(input())
d=int(input())
if a>b:
  l=(d-b*c)/(a-b)
  e=(d-b*c)%(a-b)
  
  if e == 0 and l>0:
    print("True")
  else:
    print("False")
elif a<b:
  e=(d-a*c)%(b-a)
  l=(d-a*c)/(b-a)
  
  if e == 0 and l>0:
    print("True")
  else:
    print("False")
elif a == b:
  if a*c==d :
    print("True")
  else:
    print("False")

```a=int(input())
b=int(input())
c=int(input())
d=int(input())
if a>b:
  l=(d-b*c)/(a-b)
  e=(d-b*c)%(a-b)
  
  if e == 0 and l>0:
    print("True")
  else:
    print("False")
elif a<b:
  e=(d-a*c)%(b-a)
  l=(d-a*c)/(b-a)
  
  if e == 0 and l>0:
    print("True")
  else:
    print("False")
elif a == b:
  if a*c==d :
    print("True")
  else:
    print("False")

```

## 問題描述

跑出結果正確卻無法過審

**Comment by alexypdu** [comment]
請詳閱 [GitHub Issue 使用教學](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29) 後附上提交連結及格式正確的程式碼。
