### ISSUE TITLE
[General] 8-2：最長字串

### ISSUE THREAD

**Issue by JosephTsai225** [coding-coworking-club/basic-python-2020-fall#151]
## 提交連結

https://judge.ccclub.io/status/181db1f54f7fbd371ae3aabb2f6c5b6c

## 程式碼

```python
def longest_str(x):
    if len(x) != 1:
        for i in range(1, len(x)):
            if len(x[i - 1]) < len(x[i]):
                ans = x[i]
            else:
                ans =  x[i - 1]
        return ans        
    else:
        return x[0]
    
str_input = input().split()
print(longest_str(str_input))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/71642214/95005859-dfa08280-062f-11eb-9c43-1cf92f86bc64.png)

## 問題描述

輸入題目之測資，輸出皆沒問題，也考慮到測資只有一個字串的情況，不清楚是哪一種情況沒考慮到導致wrong answer，再麻煩助教或同學解惑，謝謝！

**Comment by winnywu508** [comment]
如果我輸入wwwwww wwww ww 出來的是wwww
但答案應該要是wwwwww

else:
                ans =  x[i - 1] 

這段code會蓋掉wwwwww
http://www.pythontutor.com/visualize.html#mode=display 
建議你用visualizor 來看

**Comment by JosephTsai225** [comment]
重新改寫code之後沒問題了，將最大長度字串持續保留，繼續比大小，感謝！
