### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by rubiiii** [coding-coworking-club/basic-python-2020-fall#155]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203101

## 程式碼

```python
a = int(input())
b = range(1,a+1)

c = [2*i-1 for i in b]
for x in c:
    print('{:^100}'.format(x*'*'))
    
d = range(1,a)
e = [2*i-1 for i in d]
e.sort(reverse=True)
for i in e:
    print('{:^100}'.format(i*'*'))
```

## 問題描述

自己嘗試時，皆有出現正確的菱形圖案
我是利用range區間的數字去跑公式2i-1序列，再把元素替換成*號印出來
但繳交時還是出現錯誤答案，想請問是有哪裡錯誤或沒想到嗎
謝謝，麻煩了!!

**Comment by Kevinweisl** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!
