### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by rubiiii** [coding-coworking-club/basic-python-2020-fall#156]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203102

## 程式碼

```python
a = int(input())
b = int(input())
c = int(input())
d = int(input())
y=(a*c-d)/(a-b)
x=(c-y)
if x>0 and y>0 and x==int(x) and y==int(y) and x!=0 and y!=0:
    print('True')
else: print('False')
```

## 錯誤訊息

Runtime Error
## 問題描述

感覺答案有沒想到的條件，才會出現Runtime Error
是因為沒有設定a,b 變數需要不能為0嗎
可是這樣要怎麼在前面讓他輸入不為0，用if條件嗎

**Comment by Kevinweisl** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!

提交連結不是放題目的網址，是放你送出程式後的那個連結。
