### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by leila-lin** [coding-coworking-club/basic-python-2020-fall#157]
## 提交連結

https://judge.ccclub.io/status/86fb8c15e2f8de06c3cc4223fc87bdc2

## 程式碼

```python
sentence = str(input()).split()
low_list = ['to', 'a', 'an', 'the', 'from', 'for', 'of', 'and','in']
c = 0
for word in sentence:
    if c == 0 or word not in low_list or c == len(sentence)-1:
        word = word[0].upper() + word[1::]
        c += 1
    print(word,end=' ')
    
```

## 問題描述

我用以上程式碼 input "an end to live for" 測試，出來是 An End to Live for ，
但批改系統還是 Accepted 我的答案，想確認一下我的程式碼還有需要修改的地方嗎？

**Comment by Kevinweisl** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)，
附上正確提交連結以及格式正確的程式碼，謝謝!

提交連結不是放題目的網址，是放你送出程式後的那個連結。

**Comment by leila-lin** [comment]
謝謝提醒，已經修改為正確的提交連結！
