### ISSUE TITLE
[General] 7-1：長方星

### ISSUE THREAD

**Issue by elaine0620** [coding-coworking-club/basic-python-2020-fall#161]
## 提交連結
https://judge.ccclub.io/status/d3755df331f81618f6b3f1cd1c532c07

## 程式碼
```python
W=int(input())
I=int(input())
if W>0 and I>0 and I>W:
for N in range(I):
    print("*" *int(W))
```

## 錯誤訊息
wrong answer

## 問題描述

請問為何長方形的邊長不用設定長>寬 ? 
如果我在程式碼放入: if W>0 and I>0 ("正"整數) and I>W (長>寬) -> 就會成為WA
但如果拿掉就可以通過... :P

**Comment by Kevinweisl** [comment]
你的提交連結和你貼上來的 code 不同，麻煩補上會變 WA 的提交連結。

**Comment by elaine0620** [comment]
Link is already updated!
