### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by ZoeTsao** [coding-coworking-club/basic-python-2020-fall#162]
## 提交連結

https://judge.ccclub.io/status/21872b52f43b65ce538ec278fb0cd990

## 程式碼

```python

n=input()
sum=0

while n != "end" :
    n=int(n)
    print(format(n,","))
    sum += int(n)
    
    if n == "end":
        break
print(sum)

```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

會一直進入無限迴圈，還請助教幫忙看看

**Comment by alexypdu** [comment]
請詳閱 [GitHub Issue 使用教學](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29) 後附上提交連結及格式正確的程式碼。

**Comment by ZoeTsao** [comment]
謝謝助教，已更新

**Comment by alexypdu** [comment]
你範例測資一就沒過囉！
`n != 'end'` 的時候你的 while loop 會無限循環呢
