### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by leila-lin** [coding-coworking-club/basic-python-2020-fall#163]
## 提交連結

https://judge.ccclub.io/status/86fb8c15e2f8de06c3cc4223fc87bdc2

## 程式碼

```python
sentence = str(input()).split()
low_list = ['to', 'a', 'an', 'the', 'from', 'for', 'of', 'and','in']
c = 0
for word in sentence:
    if c == 0 or word not in low_list or c == len(sentence)-1:
        word = word[0].upper() + word[1::]
        c += 1
    print(word,end=' ')
```

## 問題描述

我用以上程式碼 input "an end to live for" 測試，出來是 An End to Live for ，
但批改系統還是 Accepted 我的答案，想確認一下我的程式碼還有需要修改的地方嗎？

**Comment by leila-lin** [comment]
不好意思我找出原因了，把ｃ+=1 放在for 迴圈內而不是放在if  判斷裡面，就可以讓答案正確，謝謝～

**Comment by Peterorr** [comment]
@leila-lin 恭喜妳喔！也謝謝妳補充上原因，如果問題解決了記得 close 👍
