### ISSUE TITLE
[General] 字串加密 II

### ISSUE THREAD

**Issue by BettyJH** [coding-coworking-club/basic-python-2020-fall#164]
## 提交連結

https://judge.ccclub.io/status/fde842848e7cc02b7e9de83e1318dae0

## 程式碼

```python
s, n = input(), input()
len(s) >= len(n)

word_list = []

for i in range(len(s)):
    for j in range(len(n)):
        if i == j:
            word = chr(ord(s[i]) + int(n[j]))
            word_list.append(word)
            ans = "".join(word_list)
print(ans)

```

## 錯誤訊息

wrong answer

## 問題描述

我在judge上測試成功，但仍不通過。請問是沒有考慮到什麼條件？
題目裡的這句「字串與整數的長度不一定相等，以字串長度為準：如果字串比較長要把數字補齊；如果數字比較長的話把多餘的截斷。」是要我做什麼假設嗎？(這邊有點看不懂)
謝謝！

**Comment by winnywu508** [comment]
比如說我input www, 22答案出來的是 yy 但應該要出現yyy

**輸入有兩行，包含一個長度為n的字串以及一個整數（字串與整數的長度不一定相等，以字串長度為準：如果字串比較長要把數字補齊；如果數字比較長的話把多餘的截斷。）**

**Comment by Viggochang** [comment]
題目希望你用輸入的 數字串 對 字母串進行加密
但是 數字串的數字數量 可能比 字母串的字母數量多或少
如果數字比字母多, 那多的數字不會用到
如果數字比字母少, 那必須把 數字串的數字補齊
數字 不夠的部分請再從 數字串 的第一個開始補

**Comment by BettyJH** [comment]
感謝助教！我少理解了這個條件「數字 不夠的部分請再從 數字串 的第一個開始補」！
已經過關了～
