### ISSUE TITLE
[Homework 2] 尋找低谷

### ISSUE THREAD

**Issue by lazyYC** [coding-coworking-club/basic-python-2020-fall#167]
## 提交連結

https://judge.ccclub.io/status/e5015f4bbfefb8f4d25d95b47b910772

## 程式碼

```python
h = [float(i) for i in input().split()]     #題目未說明都是整數，以float代替int
#h是一個以float為元素的串列

for i in range(1, len(h)):     #頭尾不可能是低谷，只檢查index值[1:-2]
    if h[i] < h[i-1] and h[i] < h[i+1]:     #檢查的項目是否低於前一個及後一個項目
        loc = h.index(h[i])     #由該位置的內容找回位置
print(loc)
```

## 問題描述

實在找不到還有什麼原因。按題目來說應該是可以這樣寫，不知道是否有被我忽略的問題？

感謝親愛的助教：)

**Comment by yles840421** [comment]
嗨~我不是助教哈哈，跟你分享下我的想法
你這邊的問題是最後用index方式去找出低谷，假如sample 2改為 [ 4 15 14 13 12 4 10 11 ]就會fail了，因為雖然找到正確的低谷數字為4，但index會先抓最左方的4當答案

而且你其實可以令loc直接等於if達成條件時的 i，不用還用index去搜尋阿XD

**Comment by lazyYC** [comment]
@yles840421 太厲害了！我想超久真的沒注意到這個問題，十分感謝！
