### ISSUE TITLE
[General] 7-1：長方星

### ISSUE THREAD

**Issue by TzuYuChen1** [coding-coworking-club/basic-python-2020-fall#168]
## 提交連結

https://judge.ccclub.io/status/302fe8eaa1da468c1bc5471418d58c06
## 程式碼

```python
l = int(input())
w = int(input())
for i in range(l, l+1):
    print('*' * i)
    for j in range(l, l+1):
        print(('*' * j + '\n') * (w-2), ('*' * j), sep = '')
```

```python
l = int(input())
w = int(input())
for i in range(l, l+1):
    print(('*' * i + '\n') * (w-1), ('*' * i), sep = '')
```

## 問題描述

兩種程式碼在jupyter上都能跑出結果，但judge系統只接受第二種，第一種會跑出wrong answer，不太確定是為什麼？麻煩助教指教，謝謝！

**Comment by Viggochang** [comment]
你的第一種程式碼在第1個 for 迴圈時，會印出 "第一行星星"
而在第2個 for 迴圈時會再印出 "中間的星星" 和 "最後一行星星"

在你的程式碼中，w 的大小會影響 "中間的星星" 的行數
無論如何 "第一行星星" 和 "最後一行星星" 都會被印出來

所以當 w =1 時，正確答案應該只印出 1行星星
但你的程式碼卻會印出 2行

========================================

另外，你的兩個迴圈都寫了 for i in range(l, l+1)
但這樣的 for 迴圈其實只執行了一次，此時 i = l
並沒有發揮 for 迴圈該有的功能
因此在你程式碼中，可以不使用 for 迴圈，直接寫 i = l 也會有一樣的效果
