### ISSUE TITLE
[Homework 2] 二元搜索

### ISSUE THREAD

**Issue by troublecat55** [coding-coworking-club/basic-python-2020-fall#169]
## 提交連結

1.accept version: https://judge.ccclub.io/status/c7e53afde1bd68b1690b4a9da78c90e9
2.wrong answer version: https://judge.ccclub.io/status/7b94142757dbbc10aa69a48dfbdb69c4

## 程式碼

```python
#do something with inputs
def binary_search_recursive(key, target):
#my binary recursive codes here

try:
    binary_search_recursive(key, target)
except IndexError:
    print("Not Found")
else:
    print(value[binary_search_recursive(key, target)]) 
```

## 錯誤訊息

wrong answer

## 問題描述

我的程式碼已經accept了（見上方1.accept version的連結）

但是由於好奇，我正在嘗試「try-except」的除錯方法（見上方2.wrong answer的連結），由於我之前得到的錯誤訊息都是「 list index out of range」，就想說用「except IndexError」來試

我的寫法是參考ccclub的medium文章寫的，在Jupyter測試過，也在repl.it丟過測資，都出現正確答案、沒出現錯誤訊息，但是在judge上跑wrong answer，想請問我是否漏掉了什麼？

先謝謝了！

ps由於程式碼已經accept，我上面程式碼的欄位貼的是簡化過的出現錯誤的版本，詳細都在連結裡面

**Comment by jeffery12697** [comment]
因為題目是`'not found'`

**Comment by jeffery12697** [comment]
因為題目是`'not found'`

**Comment by troublecat55** [comment]
哦我問了一個蠢問題XDD，謝謝助教！
