### ISSUE TITLE
[General] 停車位順位

### ISSUE THREAD

**Issue by Powei-Hsiao** [coding-coworking-club/basic-python-2020-fall#170]
## 提交連結

https://judge.ccclub.io/status/f9a77fb51b63da7280ea799a7e178b40
## 程式碼

```python
n = int(input())
count = n
lst = []

while count != 0:
    lst.append(input().split())
    count -= 1
   
def muti_sort(lst):
    build = lst[1]
    year = int(lst[2])
    num = int(lst[3]) 
    if year >= 10:
        year = 0
    elif year >= 5:
        year = 1
    else:
        year = 2
    if num % 2 == 0:
        num = 1
    else:
        num = 0  
    return (build, year, num)

for i in range(n):
    print(sorted(lst, key= muti_sort)[i][0])

```

## 問題描述

參考 #40 的已 close 的 issue，Sample Input 2 第四列應為 m416t50y5z C 5 176，系統上好像沒改到。
不過自行更改輸入測試還是顯示 Time Limit Exceeded 的錯誤，想法如下
1.  利用第一個 input 參數以 while loop 將 input 加入 lst 的串列。
2. 建立輸入為 list 輸出為 tuple 的muti_sort function，tuple第一個欄位放'A'~'C'，直接回傳字串A ,B ,C；第二個欄位年資排列為大於或等於 10 年設為 0， 大於或等於 5 年設為 1，小於 5 年為 2；第三個欄位奇數為 0 偶數為 1 。
3. 以 for loop 搭配sorted(lst, key=muti_sort) 將 ID 印出來。

問題為
1. 需要考慮到兩個人住同一棟可是一個年資 >= 10 年另一個年資 < 5 年的比較情況嗎 ?
2. 看不出來程式跑太久的原因。

再麻煩助教協助解答，謝謝!

**Comment by yles840421** [comment]
嗨~我不是助教，剛好寫過這題分享下我的看法:
1. 需要考慮住同一棟但年資不同的情況
2.程式跑太久應該是因為你用sorted方式+for迴圈，等於每次迴圈都要重跑一次sort，在迴圈發生前先用sort()處理過就可以省很多計算量
3. 你這邊好像沒考慮到ABC棟樓，建議可以tuple多加一個ord()，讓ABC數字化方便篩選

**Comment by Powei-Hsiao** [comment]
> 嗨~我不是助教，剛好寫過這題分享下我的看法:
> 
> 1. 需要考慮住同一棟但年資不同的情況
>    2.程式跑太久應該是因為你用sorted方式+for迴圈，等於每次迴圈都要重跑一次sort，在迴圈發生前先用sort()處理過就可以省很多計算量
> 2. 你這邊好像沒考慮到ABC棟樓，建議可以tuple多加一個ord()，讓ABC數字化方便篩選

**Comment by Powei-Hsiao** [comment]
在 print 出答案前，先將原本的 list 以 key=muti_sort 排序後重新提交已被系統系統接受，謝謝你的提示。

ABC樓棟在 muti_sort 裡回傳的第一個變數 build 中判斷，應該沒有問題。不過問題是當兩個住戶住同一棟，同樣偶數或奇數的門牌號碼時，一個住戶年資 10 年以上另一個住戶年資不到 5 年，以規則來看似乎沒有辦法比較(或是我會錯意)。

**Comment by yles840421** [comment]
10年以上(含) > 5年以上(含)，未滿10年> 未滿5年
我覺得中間的逗號分隔我想只是拿來斷句「5年以上(含)，未滿10年」的哈哈，所以應該是10 年以上>未滿5年
我猜你是理解為「10年以上(含) > 5年以上(含)」、「未滿10年> 未滿5年」兩個部分?
