### ISSUE TITLE
[Homework 2] 不知道要輸入幾行

### ISSUE THREAD

**Issue by yihan-lin** [coding-coworking-club/basic-python-2020-fall#171]
## 提交連結

https://judge.ccclub.io/status/6a9e3324572a73644a4a1c688bea7712
## 程式碼

```python
i = input()
lst = [i]
while i != "":
    i = input()
    lst.append(i)
new = lst[0:-1]
ans = "-".join(new)
print(ans)
```

## 錯誤訊息

runtime error
## 問題描述

我的想法是建立一個迴圈，當沒有新的輸入(空的)即停止，但lst裡還會存在一個空的東西，把它去除掉變成新的lst new，再把new轉換成Str輸出
但提交顯示runtime error....QQ我猜大概是因為不支持空的輸入??但我實在想不到別的方式，有什麼提示嗎QQ
p.s.我還想問一個，其實我本來程式碼第三行lst的部分不是 [i]是=[]，但我用Jupyter跑發現第一個會不見，所以我就把它先加進去list裡面，但我不太懂為什麼它會消失，在我的理解裡，在迴圈了也包含第一個輸入的input，所以也會在迴圈中產生的lst裡才對......

**Comment by andysleep** [comment]
我猜可能還有一個使用者不輸入的情況
你在Jupyter Run的時候按下正方形的停止按鈕(interrupt the kernel) 就會出現錯誤了
為了解決這問題可以試試try..except看看

**Comment by jeffery12697** [comment]
可以先看完這週的影片(try - except的部分)，在搭配[這篇](https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-613b2fdf38bf)試試看~

**Comment by yihan-lin** [comment]
我考慮了try except但這次卻變成wrong answer...但我看不出來哪裡錯，可否再幫我看看呢?
```
i = input()
lst = [i]
while i != "":
    try:
        i = input()
        lst.append(i)
    except:
        break
new = lst[0:-1]
ans = "-".join(new)
print(ans)
```
送出錯誤連結如下
[https://judge.ccclub.io/status/e974d1fbedaa15f33389216776f2ca1c](url)
