### ISSUE TITLE
[Week 4] 字母拼圖

### ISSUE THREAD

**Issue by YaoCianHui** [coding-coworking-club/basic-python-2020-fall#172]
## 程式碼

```python
def char_puzzle(lst):
    char_puzzle_str = "".join(lst)  #轉換成字串
    char_puzzle_lst = list(char_puzzle_str) #轉換成list
    char_puzzle_lst.sort()  #依字母先後排列
    for i in char_puzzle_lst[1:]:  #取list中的字母, 且跳過第一個
        for n in range(int(char_puzzle_lst.index(i))):  #該字母跟list前面的比較
            if i == char_puzzle_lst[n-1]: #如果i跟前面一樣
                char_puzzle_lst.remove(i) #移除i
    return "".join(char_puzzle_lst) #轉成str
```

## 錯誤訊息

![螢幕快照 2020-10-06 下午11 11 56](https://user-images.githubusercontent.com/71608067/95220951-93b92d80-0829-11eb-891f-1e4f41724cf8.png)

## 問題描述

 用python tutor看發現基本上都不會看發現基本上都不會進到if條件裡，但我實在不知道為什麼 > < 麻煩助教幫我看看，謝謝

**Comment by Viggochang** [comment]
幾個地方提點：
1. index() 功能只會找到第一個出現的元素的位置
    舉例來說：lst = ['a', 'p', 'p', 'l', 'e' ]，那 lst.index('p') 會等於 1
    所以你的第二個 for 迴圈在進行時，當 i 為相同的英文字母時，就會得到同樣的值

2. range(x) 的起始值是從 0 開始到 x-1
    舉例來說 for n in range(3)，那 n 將會依序為 0, 1, 2
    你在 if 條件裡判斷寫到 if i == char_puzzle_lst[n-1]
    當 n 為 0 時，就會出現 char_puzzle_lst[-1]，這樣會取到 char_puzzle_lst 裡的最後一個值
    因此跟你想要取 "前一個值" 的這個目標就會不一樣

**Comment by YaoCianHui** [comment]
好～了解了！謝謝助教！
