### ISSUE TITLE
[Homework 2] 不知道要輸入幾行

### ISSUE THREAD

**Issue by vicky495582** [coding-coworking-club/basic-python-2020-fall#174]
## 提交連結

https://judge.ccclub.io/contest/9/problem/203202

## 程式碼

```python
sentence=[]
word = input()
while True:
    try:
        sentence.append(word)
    except:
        break
sentence = " - ".join(word)
print(sentence)
```

## 錯誤訊息

想請問這樣寫的話在JUPYTER上測試時，要怎麼讓系統知道我INPUT結束了~
上傳批改系統顯示 TIME LIMITED EXCEED

**Comment by yles840421** [comment]
要讓input在為 ""(空字串)時結束~

**Comment by jeffery12697** [comment]
#171

**Comment by No37elephant** [comment]
HI, 這好像是 Judge 系統輸入資料的方式所造成的問題，可以參考這個文章[https://zerojudge.tw/ShowThread?postid=15789&reply=0](url)。

**Comment by yeutong** [comment]
請參考[GitHub Issue 使用教學](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)修正題目格式~
