### ISSUE TITLE
[Homework 2] 不知道要輸入幾行

### ISSUE THREAD

**Issue by hychang75** [coding-coworking-club/basic-python-2020-fall#176]
## 提交連結

https://judge.ccclub.io/status/3b39bb1463611490d0471608eaf5147b

## 程式碼

```python
sentence = [] 
while True: 
    word = str(input()) 
    if word: 
        sentence.append(word) 
    else: 
        break 
print('-'.join(sentence))

```

## 錯誤訊息

Runtime error 

## 問題描述

您好，在 Jupyter notebook 上試了很多次，output看起來都是成功的，真的想不到過不了的原因，再麻煩助教了，謝謝~

**Comment by jeffery12697** [comment]
#171
