### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by troublecat55** [coding-coworking-club/basic-python-2020-fall#177]
## 提交連結

https://judge.ccclub.io/contest/9/problem/203205

## 程式碼

```python

```

## 問題描述
我的程式碼accpet了，所以我的問題和我的程式碼比較無關，但是我真的是滿好奇問的，希望能得到助教或出題者的回答。

我想知道為什麼這題「hint」希望回答的人「試試看用二元搜索來解這題吧！」。

由於我最近在網路上自學一些基礎的資料結構，但是還沒學完，就我目前所學，如果是lookup的話BST是O(logn)、hash table是O(1)，big-O complexity都是constant time ，所以一般用BST而不是hash table的原因是：1.　BST資料本身能sorted data 　2.　資料本身有parent-child的關係要處理。（但是這題沒有需要sorted、資料本身也並沒有parent-child的關係？）

所以用hash table來解這題應該是比較優化的解法？還是我誤會了什麼？（例如recursive二元搜索跟BST traverse其實是不同的方法嗎？）

先謝謝助教或出題者！

**Comment by jeffery12697** [comment]
嗨你好～
你說的沒錯！在時間複雜度上hash table在這題算是最優解，而且 python 上是可以幾乎秒解這題ＸＤ，但那是後面會教到的資料型態，這題主要是讓同學練習 list 跟 二元搜索的方法，如果兩者都能熟悉使用，用哪種方法都是可行的喔～

**Comment by troublecat55** [comment]
感謝助教解答，太好了所以我沒有學錯XD。
之前我accept的就是hash table的版本。我目前對二元搜索的syntax還沒那麼熟悉，之後如果有空再來寫寫看二元搜索的版本。
