### ISSUE TITLE
[Homework 2] 尋找低谷

### ISSUE THREAD

**Issue by WilsonJhong** [coding-coworking-club/basic-python-2020-fall#178]
## 提交連結

[辛苦的助教請點我](https://judge.ccclub.io/status/f46ffc6af3429d82302a3b4044656530)

## 程式碼

```python
a = input()
ans = []
a = a.split(" ")
a = list(map(int, a))
for i in range(len(a)- 2) : #因頭尾不須計入，因此減去2
    if a[i] > a[i+1] and a[i+1] < a[i+2] :
        ans.append(a[i+1]) #這行我個人覺得是多餘的XD 當初沒看到只會有一個低谷
print(a.index(min(ans))) #最後找出那個低谷的數字再去確認在a串列中的位置
```

## 問題描述

因兩筆測資都顯示正確答案，應該是我有尚未考慮周全的地方，但已經苦惱一下午了 XD 希望接受助教提點，十分感謝

**Comment by yles840421** [comment]
嗨~我不是助教哈哈，跟你分享下我的想法
你這邊的問題是最後用index方式去找出低谷，假如sample 2改為 [ 4 15 14 13 12 4 10 11 ]就會fail了，因為雖然找到正確的低谷數字為4，但index會先抓最左方的4當答案

**Comment by WilsonJhong** [comment]
> 嗨~我不是助教哈哈，跟你分享下我的想法
> 你這邊的問題是最後用index方式去找出低谷，假如sample 2改為 [ 4 15 14 13 12 4 10 11 ]就會fail了，因為雖然找到正確的低谷數字為4，但index會先抓最左方的4當答案

感謝你的回應！成功找到問題點了 XDD 祝福好人一生平安
