### ISSUE TITLE
[General] 奇偶遞迴

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#180]
## 提交連結

https://judge.ccclub.io/status/85b0ac2472c32280af535e1d25e19862
## 程式碼

```python
def f(x):
    if x == 1:
        return 1
    elif x % 2 == 1:
        return f((x-1)/2) + f((x-1)/2 + 1)
    else:
        while x % 2 == 0:
            x = x//2
        return f(x)

```

## 錯誤訊息
Wrong answer

## 問題描述

助教您好，想請問是何種測資無法通過呢?(有懷疑過是不是輸入0或負數，但那應該會直接runtime error才是)

**Comment by jeffery12697** [comment]
這題還是要寫個 input output~

**Comment by yles840421** [comment]
原來如此~感謝!
不過那請問需要考慮負數與0嗎?依照題目的邏輯，f(0)似乎只能靠定義取得才對?(且負數也會需要用到f(0)的值才能求出)
