### ISSUE TITLE
[Homework 2] 尋找低谷

### ISSUE THREAD

**Issue by gigatt-jm** [coding-coworking-club/basic-python-2020-fall#181]
## 提交連結

https://judge.ccclub.io/status/77ac32c9a70f3ed15206be9eb86ac432

## 程式碼

```python
lines = input()
lines = [int(x) for x in lines.split()]
minimum = min(lines)
print(lines.index(minimum))
```

## 錯誤訊息

Wrong Answer

## 問題描述

助教們好，我的想法是先split input的string然後轉成integer，再找出所有數字中的最小值，就可以知道低谷是哪一個。最後再用.index()去找出index位置並且print低谷出現的位子。測試sample input 1 & 2都看似正確，但還是wrong answer，不確定是哪裡漏掉了，不知道助教們能否幫忙確認一下，非常感謝！！！

**Comment by Poyu781** [comment]
我與還沒解出來，但我看起來可能是低谷不只一個，還在測試當中

**Comment by gigatt-jm** [comment]
題目Description好像有寫「可以保證會恰好出現一個低谷，且不會有相鄰的山稜線數值相同的情形。」所以應該是只有一個低谷？

**Comment by Poyu781** [comment]
我剛剛測試寫成功了，的確改程會判斷很多低谷就對了！我也覺得題目沒寫清楚，可能需要調整一下敘述！

**Comment by gigatt-jm** [comment]
所以是會有不只一個低谷的意思嗎？那output 就可能會有不只一個數字？

**Comment by Poyu781** [comment]
是的～我用 21 15 14 13 12 4 13 11 17  去測，要得到 output 是 ’57' ，這樣才會被 Accepted

**Comment by gigatt-jm** [comment]
了解！那請問一下你的output的57中間有空格嗎？還是沒有就兩個數字連在一起

**Comment by yeutong** [comment]
嗨嗨 抱歉造成大家誤解QQ 低谷（符合比兩邊都低的情況）確實只會出現一次，但低谷的數值可能出現不止一次
可以參考 #215
