### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by vicky495582** [coding-coworking-club/basic-python-2020-fall#186]
## 提交連結

https://judge.ccclub.io/status/97ff072b36799a37df7d6cf2ca9e0969
## 程式碼

```python
name = input().split()
money =[int(i) for i in input().split()] 
lst = []
pay_name = input()
while pay_name!="":
    try:
        index = name.index(pay_name)
        pay_money = money[index]
        lst.append(pay_money)
        pay_name = input()
    except:
        break
for money in lst:
    print(money)
```

## 問題描述

 想請問我在jupyter notebook 上測試都可以，但丟到批改系統卻顯示時間用太多( time limit exceeded)，想請問我的寫法有沒有哪裡出錯

**Comment by yeutong** [comment]
你的做法是對的沒有問題，但這題想讓大家操作看看二元搜索，不知道你寫二元搜索那題了嗎~
可以用 ASCII 的排序來試試看在這題套用二元搜索的想法，可以進一步節省時間噢

**Comment by yeutong** [comment]
另外你的提交連結放錯了，那個是題目的連結，請參考 [GitHub Issue 使用教學](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29) 修改

**Comment by vicky495582** [comment]
已更改~謝謝助教

**Comment by yumei86** [comment]
因為問題很像，所以在這篇發問> <
雖然已經用dictionary的方式解決此題，
但就是想不到如何用二元搜索的方式。
目前的根據助教上面的提示，會想先用 ASCII 將每個字串轉成數字，
再依據排序的功能由小排到大，接下來用二元搜索找到對應值，
最後在對應到金額。
想請問助教這樣的思考邏輯可不可行，能不能再提供一些提示> < 非常感謝！
