### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by rubiiii** [coding-coworking-club/basic-python-2020-fall#189]
## 提交連結

https://judge.ccclub.io/status/260b5f322f1318654a982b87b2bf1ee0
## 程式碼

```python
count = 0
while True:
    num = input()
    if num == "end":
        break
    else: 
        num1 = num.split(",")
        num2 = "".join(num1) 
        num3 = int(num2)
        count = count + num3       
count_str = str(count)
new = []
for i in count_str :
    new.append(i)
new.reverse()
for j in range(len(new)+2):
    if j % 4 == 0 and j > 3 :
        new.insert(j-1,',')
new.reverse()
for k in new:
    print(k, end="")
```

## 錯誤訊息

Wrong Answer

## 問題描述

數字相加的部分應該是OK的
但不確定是不是要標逗點地方是不是寫錯，
我是想說逗號都是(4的倍數-1)的位數要標逗號，
所以才除4餘0然後j-1位數標逗號

可以幫我想邏輯哪裡有錯嗎
謝謝

**Comment by huaitzu** [comment]
使用insert會改變實際上list的長度，插入一個物件該list的長度就會+1，然而一開始跑for迴圈的range(list長度)，不會隨著list長度在迴圈內更動而更新，因此末端的數字在迴圈內不會被跑到而無法依據條件加到逗號。

如果看完敘述還是不太清楚的話，可以試看看這個測資：
12345678989345
82795483789485
end

可以參考HW1 hint的作法進行修改~
