### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by rebecca7702** [coding-coworking-club/basic-python-2020-fall#19]
## 提交連結
https://judge.ccclub.io/contest/3/problem/202105

## 程式碼

```python
entertime = input()
EnterHour=int(entertime[0:2])
EnterMins=int(entertime[3:5])

exittime = input()
ExitHour=int(exittime[0:2])
ExitMins=int(exittime[3:5])

HaveCert = input()

ParkingMins = 60*(ExitHour-EnterHour) + (ExitMins-EnterMins)
if ParkingMins < 0:
    print('No overnight parking')
else:
    Howmany30 = ParkingMins // 30 

    if (Howmany30 * 30 < ParkingMins) :
        Howmany30 = Howmany30 +1

    if HaveCert == "Y" :
        if ParkingMins < 30:
            Howmany30 = 0

    if HaveCert == "Y" :
        ParkingFee = (20/2) * Howmany30 
    else :
        ParkingFee = 20 * Howmany30 

    print(str(ParkingFee))
```

## 問題描述
在Jupyter上都沒有問題，但Judge一直不讓我過，我不知道問題在哪裡。
謝謝助教。

**Comment by misvap** [comment]
`else:
    Howmany30 = ParkingMins // 30 

    if (Howmany30 * 30 < ParkingMins) :
        Howmany30 = Howmany30 +1

    if HaveCert == "Y" :
        if ParkingMins < 30:
            Howmany30 = 0

    if HaveCert == "Y" :
        ParkingFee = (20/2) * Howmany30 
    else :
        ParkingFee = 20 * Howmany30`

1. 這個部分的 indentation 和 ParkingFee 要不要再看一下～
2. 要考慮同一分鐘進出不用錢的情況

PS 建議 if else 的條件，是否有證件的優先權往前挪
（拍謝我還在搞懂怎麼在github insert code，格式跑掉你再看一下）
