### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by enn-lu** [coding-coworking-club/basic-python-2020-fall#190]
## 程式碼

```python
sentence=input().split()
list=[]

for word in sentence:
	if word==sentence[0]or word==sentence[-1]:
		a=word[0].upper() + word[1:]
		list.append(a)
	else:
		for text in list_1:
			if word == text:
				a=word
				list.append(a)
				
			else:
				a=word[0].upper() + word[1:]
				list.append(a)
				
print(*list)
```

## 問題描述

想法: 判定input的文字中是否有 不能大寫的字
問題: for text in list_1好像會出問題
分別檢查
(1)if word == text:
		a=word
		print(a)
可print出來的能正確顯示input中不能被轉成大寫的字 
(2)else:
              a=word[0].upper() + word[1:]
	      print(a)
會print出九個相同的字

例如:
input:  under the dome an affair to remember
(1)output: 
the 
an
to
(2)output:
The
The
The
The
The
The
The
The
Dome
Dome
Dome
Dome
Dome
Dome
Dome
Dome
Dome
An
An
An
An
An
An
An
An
Affaire
Affaire
Affaire
Affaire
Affaire
Affaire
Affaire
Affaire
Affaire
To
To
To
To
To
To
To
To

**Comment by winnywu508** [comment]
你前面只有lst = [] 沒有list_1 = []. for text in list_1: 這段會卡住

**Comment by winnywu508** [comment]
text也沒有定義

**Comment by winnywu508** [comment]
我覺得你的邏輯大致上是對的
可以加一段定義 text = ['to', 'a', 'an', 'the', 'form', 'for', 'of', 'and', 'in']
然後思考一下你第二個for loop for text in list_1:
