### ISSUE TITLE
[General] 空字串

### ISSUE THREAD

**Issue by sydney1111** [coding-coworking-club/basic-python-2020-fall#191]
## 程式碼

```python
print("" == input().split())

```

## 問題描述

想請問一下，為什麼在input().split()不打字，即輸入空字串，會不等於 ""，即原先設定的空字串條件呢?
阿不知道這樣講能不能看懂，主要就是為什麼輸入空字串時，這個程式碼會等於false呢?
我有想過是不是空字串進split會被分割，但若改成一個空白print(" " == input().split())或是兩個空白都還是一樣是false，不曉得怎麼樣才可以是true。

**Comment by chun9425** [comment]
使用 split() 的話是會回傳串列，不是字串
也就是說如果執行下面的程式碼
```python
a = ''
print(a.split())
```
會得到 []，也就是空串列，而不是空字串，
你可以再自己試試看~

**Comment by sydney1111** [comment]
非常感謝!!
