### ISSUE TITLE
[General] 8-1：乘積最大值

### ISSUE THREAD

**Issue by ritawu91** [coding-coworking-club/basic-python-2020-fall#195]
## 提交連結
https://judge.ccclub.io/status/ca89bae6617e8414426befa949256736

## 程式碼

```def max_mul(l):
    l=[int(i) for i in l.split()]
    s=[ ]#建立空字串以放進乘積值
    number=sorted(l)
    for i in range (len(number)):
        s.append(int(number[i-1]) * int(number[i])) #乘積值加入字串中
        
    max_value= max(s) #乘積中最大的
    return (max_value)
l= input()
print(max_mul(l))
```

## 錯誤訊息
Wrong Answer

## 問題描述
在不同的平台測試成功，也測試不同的數字。但丟到Judge 系統，it says Wrong Answer

**Comment by winnywu508** [comment]
可以測試看看-3 2 -1 0 -1 2 output應該是要0 但你的code會跑出6
number=sorted(l) <- 這段邏輯會把最大相鄰乘積的順序打亂
應該不用sorted list

**Comment by Viggochang** [comment]
除了不需要對輸入值進行排序外，
你的 for 迴圈
```
for i in range (len(number)):
        s.append(int(number[i-1]) * int(number[i])) #乘積值加入字串中
```
會使 i 從 0 開始迭代 至 len(number)-1
因此當 i 為 0 ，執行 int(number[i-1]) * int(number[i])) 時
即為 int(number[-1]) * int(number[0]))，
其中 number[-1] 會取到 number 陣列裡的最後一項，
int(number[0]) 為 number 陣列裡的第一項，
這兩個數相乘並不符合題目所述「連續兩個相鄰乘積」
