### ISSUE TITLE
[Homework 2] 不知輸入有幾行

### ISSUE THREAD

**Issue by ambre915** [coding-coworking-club/basic-python-2020-fall#197]
## 提交連結

https://judge.ccclub.io/status/9faf09afacf059c5273ab60df7ffa5c1

## 程式碼

```python
first = input()
lst = []
lst.append(first)

while first !="":
    i = input()
    if i != "" :
        lst.append(i)
    else:
        break
        
ans = '-'.join(lst)
print(ans)
```

## 問題描述

助教好，上面是我寫這題作業的邏輯，我先有一行輸入，剩下的輸入存入lst之後，等到使用者輸入為空（直接enter）則視為不再有輸入之後，就用'-'連結。
看了之前其他同學的發問以及助教的回覆，還是不太明白，而且我主要花更多時間在瞭解題意。
所以想跟助教確認，這題題目的意思是，是多次的輸入視為多行，還是一次的輸入中就可能會有多行？
這題的寫法是以前面那個理解寫的，若題目是這個意思，不知我有什麼漏考量的地方造成runtime error，還請助教提點。
若題目的意思是，一次的輸入可能會有多行，那我曉得我便要用別種寫法。
但是我在測試自己的程式的時候，也有嘗試直接把多行的測資放進input，但他並不是多行，也有到medium提供的Repl.it環境測試，出現了一些錯誤訊息，看起來好像也是不支援一次有多行input的，不知我是否有理解錯誤。

謝謝助教～

**Comment by Neptune2901** [comment]
參考#171
