### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by misvap** [coding-coworking-club/basic-python-2020-fall#198]
## 提交連結

https://judge.ccclub.io/status/6b1020e614c80f00a674ae5b5d13b85a

## 程式碼

```python
# NOT solution to prob 203205

# take in names, and mapped debt value 
name_lst = input().split()
value_lst = [int(i) for i in input().split()]

# take in order to ask for debt
while True:
    try:
        this_person = input()
        if this_person in name_lst:
            index = name_lst.index(this_person)
            print(value_lst[index])
    except: # break the loop when users enter nothing
        break 
```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

助教、同學好！針對這題，我有兩個問題想問：

1. 如何對未定行數的 input debug（使用 http://pythontutor.com/visualize.html#mode=display debug，未定行數的輸入不知道如何debug）
2. 這題我使用了不同方法依然是 Time Limist Exceeded，以下詳述我的思路（第一種）：
2-1. 利用 name_lst 儲存使用者輸入的人名。利用 value_lst 儲存使用者輸入的負債金額。
2-2. 利用一個 while-loop 來獲得使用者輸入的討債名單順序。
2-2-1. 在 try 區塊嘗試吃進使用者的 input ，再判斷其是否出現 name_lst 裡，若有，則到 value_lst 的對應 index 印出其負債金額。
2-2-2. 若使用者沒有輸入任何的 input，則進入 except 的區塊，並 break 掉這個 while loop。

我的另一個想法，是將上述步驟 2. 拆成兩個部分：
1. 一個部分是判斷使用者是否有 input，若有則 append 到一個 order list。
2. 針對 order list 裡的每個 item 印出對應的負債金額。
```python
# NOT solution to prob 203205

# take in names, and mapped debt value 
name_lst = input().split()
value_lst = [int(i) for i in input().split()]

# take in order 
order = []
while True:
    try:
        this_person = input()
        order.append(this_person)
    except: # break the loop when users enter nothing
        break 

# print result 
for name in order:
    if name in name_lst:
        index = name_lst.index(name)
        print(value_lst[index])
```

我認為問題出在 while loop 裡，參考 #171 的討論仍想不到原因，再麻煩助教或同學協助了，謝謝大家！

**Comment by Neptune2901** [comment]
試試使用二元搜索吧！花的時間會比逐一檢視還少就可以通過了~

**Comment by misvap** [comment]
好！我來試試看！

**Comment by misvap** [comment]
順利解決了！謝謝助教
