### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by troublecat55** [coding-coworking-club/basic-python-2020-fall#2]
## 提交連結
https://judge.ccclub.io/status/4334ad7325be457f0dc4f857a6219734

## 程式碼

```python
l = (int(input()))
w = (int(input()))
def add_sub_rectangle(l, w):
    ### l 和 w 的型態為整數(int)
    ### 請在下面開始你的程式
    if((l <= 0) or (w <= 0)):
        print("invalid")
    else:
        for i in range(w):
            for j in range(l):
                if i % 2 == 0:
#                     print(i)
                    if j % 2 == 0:
                        print("+",end="")
                    elif j % 2 != 0:
                        print("-",end="")
                elif (i % 2 != 0) :
                    if j % 2 == 0:
                        print("-",end="")
                    elif j % 2 != 0:
                        print("+",end="")
            print()
add_sub_rectangle(l, w)
```
## 問題描述

我在Udemy上通過了，在Jupyter跑也沒什麼問題，但是不知道為什麼Judge過不了
思路很簡單就是l跟w小於等於零，就印invalid
然後後面是跑二維陣列a[i][j]，找出pattern如果i跟j兩個index都是奇數或都是偶數的話印"+" ，不然一奇數一偶數的話印＂－＂
例如跑
l=3       (j是index);
w=2     (i是index);

陣列如下：
a[0][0] a[0][1] a[0][2]
a[1][0] a[1][1] a[1][2]
+-+
-+-
所以我程式是照這個思路寫的，請問有漏掉什麼嗎

ps,由於我之後會比較忙怕作業交不出來，我就先超前進度了，希望能得到解答，先謝謝了！

**Comment by chun9425** [comment]
這題對輸出的要求理解錯誤喔，
你測試看看 sample 2，
會發現你的 output 跟範例答案不相同。

輸出的 + 跟 - 是交錯的，
例如將 sample 2 每一列（row）拼起來會變成下面這樣

+-+-
+-+- ===> +-+-+-+-+-+-
+-+-

而不是像你程式碼裡寫的奇數行由 + 開始，偶數行由 - 開始。

**Comment by troublecat55** [comment]
ACE了，眼睛花感謝提示
