### ISSUE TITLE
[Homework 2] 不知道要輸入幾行

### ISSUE THREAD

**Issue by yufang3132** [coding-coworking-club/basic-python-2020-fall#203]
## 提交連結

https://judge.ccclub.io/status/39fb7509b59cb6e18027d7c5f017fcd1

## 程式碼

```python
lst = []
while True:
    try:
        s = input()
        lst.append(s)
        print("-".join(lst))
    except:
        break
```

## 問題描述

試著按照今天公布的提示後，在jupyter notebook上跑，每input一次會加到前一次input的後面，全部輸入完會變「HoydeA-象牙舟-5:10a.m.-視線所及只剩生活-你終究不愛這世界」，但丟到judge上會顯示wrong answer，有參考過前面github上同學的問題了，但還是不知道哪裡出了問題、該怎麼調整

**Comment by misvap** [comment]
```python
print("-".join(lst))
```

這個部分如果寫在 try 裡面，while 每跑一次，它就會印出一次階段性的成果。但題目要的是一次印出最終結果喔！

**Comment by yufang3132** [comment]
謝謝助教，調整過print的位置之後有成功寫出來了～
（原來在jupyter notebook上，要按停止才會跑出答案）

**Comment by misvap** [comment]
欸斗，我不是助教啦😂 恭喜解出來！一起加油😀
