### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by WilsonJhong** [coding-coworking-club/basic-python-2020-fall#206]
## 提交連結

[連結請點我](https://judge.ccclub.io/status/ab2b7b46b28785e49b0e3ed72145b1ca)
## 程式碼

```python
name = input().split(" ")
money = input().split(" ")
while True :
    try :
        s = input()
        print((money[name.index(s)]))
    except :
        break
```

## 錯誤訊息

Time Limit Exceeded
## 問題描述

不確定還能如何簡化我的 Code QQ，有看到 hint 說可以用二元搜索來處理，但卻不知如何下手，再麻煩助教解惑感恩

**Comment by Neptune2901** [comment]
https://www.w3schools.com/python/ref_func_sorted.asp
字串也可以比大小~一樣用比較大小的方式來做二元搜索！
