### ISSUE TITLE
[Homework 2] 檢查密碼

### ISSUE THREAD

**Issue by ChiHsinTseng** [coding-coworking-club/basic-python-2020-fall#208]
## 提交連結

https://judge.ccclub.io/status/55e766f1f97425444bd470f7493160a7
## 程式碼

```python
def alphabet_number(s):
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    number = "0123456789"
    for i in s:
        if i in alphabet and i in number:
            return "True"
        else:
            return "False"

n = input()
print(alphabet_number(n))
```

## 錯誤訊息

wrong answer
## 問題描述

我是先定義一個function，如果同時包含了alphabet跟number的話就return "True"，反之則return "False"
測資是錯的但看不太出來是哪裡邏輯有錯誤，再麻煩助教了，謝謝

**Comment by yeutong** [comment]
因為 s 是我們要檢查的密碼（為字串）。在 `for i in s:` 的迴圈裡面，`i` 會是密碼裡面的每個字元。接著 `if i in alphabet and i in number:` 這行，因為 `i` （是某個字元，可能是字母或數字）不可能同時在 `alphabet` 的 list 及 `number` 的 list 裡面，所以不管輸入什麼都會輸出 false。

**Comment by ChiHsinTseng** [comment]
> 因為 s 是我們要檢查的密碼（為字串）。在 `for i in s:` 的迴圈裡面，`i` 會是密碼裡面的每個字元。接著 `if i in alphabet and i in number:` 這行，因為 `i` （是某個字元，可能是字母或數字）不可能同時在 `alphabet` 的 list 及 `number` 的 list 裡面，所以不管輸入什麼都會輸出 false。

想請問一下在同一個程式裡可以同時定義兩種function嗎？
