### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by sydney1111** [coding-coworking-club/basic-python-2020-fall#21]
## 提交連結

https://judge.ccclub.io/status/95405afa3a1b5bf2b64bde0f9018a9a4
## 程式碼

```n1,n2,n3=input(),input(),input()
t1=(int(n1[:n1.index(":")])*60)+(int(n1[3:]))
t2=(int(n2[:n2.index(":")])*60)+(int(n2[3:]))
alltime=t2-t1
fee=alltime//30*20
if alltime%30>0:
    fee+=20
if n3=="Y" and alltime<30:
    fee==0
if n3=="Y":
    fee/=2
print(int(fee))

```

## 問題描述

我一開始的程式是貼上來的這個，是錯誤的，我發現好像是因為如果if alltime%30>0被滿足，就不會進到下一個的if n3=="Y" and alltime<30這個，所以後來我把程式改成批改系統上附的連結內的樣子，讓這兩個成為在一起的if-elif條件，答案即正確，但我不曉得為什麼用兩個if是不行的，不是會一個一個條件嘗試是否滿足嗎?想請問這個，非常感謝!

**Comment by misvap** [comment]
那個...我不是助教，然後連結點進去看不到程式碼，不曉得是不是這個原因。這邊提供我的想法，不確定對不對，歡迎討論！

關於你上面的問題，我的想法是：
1. 如果要在一個 if a裡面再執行一個 if b，python的語法規定 if b 的內容必須再縮排，可以看昨天額外補充的 nested if statement。
例：
`    if license == "Y": 
        if parkingMinutes < 30:
            pay = 0`

2. 你的意思應該是滿足第一個 if 條件之後，再檢查後續 n3 的條件對吧？那這樣就是 and 的邏輯，必須寫成nested if statement，不然 python 會把你當成是if...elif的關係在看（你可以用jupyter notebook測看看，下面這兩段程式碼，我測出來的結果是一樣的）
`a = int(input())

if a == 0:
    print("A")
if a == 1:
    print("B")
if a == 2:
    print("C")
else:
    print("D")`

`a = int(input())

if a == 0:
    print("A")
elif a == 1:
    print("B")
elif a == 2:
    print("C")
else:
    print("D")`

3. 最後，同ㄧ層級的 if statement 的條件盡量還是設成同一個東西比較好（即要測試的 boolean 變數名稱應相同），你的alltime%30>0 跟 n3=="Y" and alltime<30 以及 n3=="Y" 是不同的 boolean 變數。

**Comment by misvap** [comment]
那個...我不是助教，然後連結點進去看不到程式碼，不曉得是不是這個原因。這邊提供我的想法，不確定對不對，歡迎討論！

關於你上面的問題，我的想法是：
1. 如果要在一個 if a裡面再執行一個 if b，python 的語法規定 if b 的內容必須再縮排，可以看昨天額外補充的 nested if statement。

2. 你的意思應該是滿足第一個 if 條件之後，再檢查後續 n3 的條件對吧？那這樣就是「如果 a 滿足再看 b 是否滿足」的邏輯，必須寫成nested if statement，不然 python 會把你當成是 if...elif 的關係在看（你可以用jupyter notebook測看看，下面這兩段程式碼，我測出來的結果是一樣的）
`a = int(input())

if a == 0:
    print("A")
if a == 1:
    print("B")
if a == 2:
    print("C")
else:
    print("D")`

`a = int(input())

if a == 0:
    print("A")
elif a == 1:
    print("B")
elif a == 2:
    print("C")
else:
    print("D")`

3. 最後，同ㄧ層級的 if statement 的條件盡量還是設成同一個東西比較好（即要測試的 boolean 變數名稱應相同），你的alltime%30>0 跟 n3=="Y" and alltime<30 以及 n3=="Y" 是不同的 boolean 變數。（我自己寫的時候覺得這樣比較好思考，但不確定適不適用所有的情況）

**Comment by sydney1111** [comment]
你好!謝謝你的回應!不好意思，那我直接把程式貼上來(貼if這塊而已，其他都一樣)
這個是judge上顯示正確的版本
if n3=="Y" and alltime<30:
    fee==0
elif alltime%30>=1:
    fee+=20
if n3=="Y":
    fee/=2
這個版本我理解的是如果第一個if吻合，就不會執行elif，但會繼續執行第二個if。
下面這個是不正確的版本
if alltime%30>0:
    fee+=20
if n3=="Y" and alltime<30:
    fee==0
if n3=="Y":
    fee/=2
這裡是我不懂的地方，總共有三個if，我的想法是先檢測第一個if，無論吻合與否，都會再進行第二個if，再來是第三個if，就是可能alltime是20，第一個符合fee+20=20，再來進行第二個，因為alltime<30，所以fee會歸零這樣，但執行出來卻是錯誤的，呈現結果fee是10，我猜想可能是因為沒有檢測到第二個if(但也可能不是這個原因)，所以我很疑惑為什麼這樣寫不行。

**不好意思，你的第三點我沒有看得很懂!可以再麻煩說明一下嗎~boolean變數結果不是只有true跟false嗎?還是你指的是>,<,==這些符號盡量每個if都一致?非常感謝!!

**Comment by misvap** [comment]
hi! 附上我剛剛找到的解釋給你參考：

By using if repeatedly you will ask all if conditions, no matter if any other before that was true.
 With elif you evaluate the first if, and if it is false THEN evaluate the second, if both of them were false THEN the third and so on, if any of them was true you stop evaluating the next conditions

關於第三點，我想講的是boolean變數的名稱啦！不是它的值（true/ false），但我剛剛回去看Kevin解題的邏輯再搭配上面那段英文，發現不一定要同一個變數名稱作為條件判斷也可以。但原因是你使用 if...if...if 而非 if...elif...elif的時候，程式會同時判斷各個 if statement，沒有誰先誰後的問題（所以不適用有順序的條件）。但若使用 if...elif 敘述的話，elif 只會在 if 的敘述錯誤時才會執行。

然後我第一則回覆的第二點再讓我想一下，if...elif 和 nested if statement 的使用差別。

**Comment by jeffery12697** [comment]
> 你好!謝謝你的回應!不好意思，那我直接把程式貼上來(貼if這塊而已，其他都一樣)
> 這個是judge上顯示正確的版本
> if n3=="Y" and alltime<30:
> fee==0
> elif alltime%30>=1:
> fee+=20
> if n3=="Y":
> fee/=2
> 這個版本我理解的是如果第一個if吻合，就不會執行elif，但會繼續執行第二個if。
> 下面這個是不正確的版本
> if alltime%30>0:
> fee+=20
> if n3=="Y" and alltime<30:
> fee==0
> if n3=="Y":
> fee/=2
> 這裡是我不懂的地方，總共有三個if，我的想法是先檢測第一個if，無論吻合與否，都會再進行第二個if，再來是第三個if，就是可能alltime是20，第一個符合fee+20=20，再來進行第二個，因為alltime<30，所以fee會歸零這樣，但執行出來卻是錯誤的，呈現結果fee是10，我猜想可能是因為沒有檢測到第二個if(但也可能不是這個原因)，所以我很疑惑為什麼這樣寫不行。
> 
> **不好意思，你的第三點我沒有看得很懂!可以再麻煩說明一下嗎~boolean變數結果不是只有true跟false嗎?還是你指的是>,<,==這些符號盡量每個if都一致?非常感謝!!

思路是對的，但要歸零的話要寫 fee = 0, fee == 0 是判斷有沒有等於零

**Comment by jeffery12697** [comment]
> hi! 附上我剛剛找到的解釋給你參考：
> 
> By using if repeatedly you will ask all if conditions, no matter if any other before that was true.
> With elif you evaluate the first if, and if it is false THEN evaluate the second, if both of them were false THEN the third and so on, if any of them was true you stop evaluating the next conditions
> 
> 關於第三點，我想講的是boolean變數的名稱啦！不是它的值（true/ false），但我剛剛回去看Kevin解題的邏輯再搭配上面那段英文，發現不一定要同一個變數名稱作為條件判斷也可以。但原因是你使用 if...if...if 而非 if...elif...elif的時候，程式會同時判斷各個 if statement，沒有誰先誰後的問題（所以不適用有順序的條件）。但若使用 if...elif 敘述的話，elif 只會在 if 的敘述錯誤時才會執行。
> 
> 然後我第一則回覆的第二點再讓我想一下，if...elif 和 nested if statement 的使用差別。

如果只有單純的一行判斷式，那兩個就看起來差不多，但如果條件多的話 nested if statement 會比較可以活用
