### ISSUE TITLE
[Week 5] 比賽排名

### ISSUE THREAD

**Issue by tziyingchen** [coding-coworking-club/basic-python-2020-fall#210]
## 提交連結

https://judge.ccclub.io/status/f48ddc3d1b260a8ea1d9b3e40b387641

## 程式碼

```python
a = [int(i) for i in input().split(' ')]
b = sorted(a)
for index, time in enumerate(a):
    for time in a:
        print(a.index(time), end = ' ')
```

## 問題描述

寫這題的過程中我遇到兩個問題
1. 我想用enumerate的方式取得sorted(list)的索引號，但是仍然無法解決遇到一樣數字只會取到第一個索引號的問題
2. 我不是很能理解為什麼我的code會自動執行數次，最後Print出多次重複的索引號。

**Comment by Poyu781** [comment]
我不是助教，所以不太能完全解答你，但針對這題與你的思路，可以給你一些建議。
首先，我不太確定你的變數 b 要幹嘛，然後我不是很能解釋那兩個迴圈是在跑什麼鬼XD ，只是在你用 enumerate 的情況下，再放一個迴圈在裡面好像有點奇怪，你可以試著跑看看[程式連結](http://www.pythontutor.com/live.html#code=a%20%3D%20%5Bint%28i%29%20for%20i%20in%20input%28%29.split%28'%20'%29%5D%0Ab%20%3D%20sorted%28a%29%0Afor%20index,%20time%20in%20enumerate%28a%29%3A%0A%20%20%20%20for%20time%20in%20a%3A%0A%20%20%20%20%20%20%20%20print%28a.index%28time%29,%20end%20%3D%20'%20'%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-live.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)
最後一點，當你使用
``` python 
        print(a.index(time), end = ' ')
```
代表程式會去 a =[ 5,3,3,1] 裡面找 time 的 index ，因為 index()只會找第一個配對到的資料，所以你不管怎樣，在 3 的時候，都只會得到 index =1 的值

根據你的思路，我寫出這樣的程式，你可以參考看看
``` python 
a = [int(i) for i in input().split(' ')]  ## 跟你一樣
index_time_list =[] 
for index, time in enumerate(a): ## 此段是產生放置 index 跟 item 的 list ，像是：index_time_list = [ [0,5], [1,3], [2,3], [3,1] ]
    list_input = [index, time ]
    index_time_list.append(list_input)
    
def return_time_value(x):   ##此串應該可以用 lambda 去簡化，但我不太會，加上這樣會比較好理解，就寫成這樣，主要是等等 sorted 排序時，可以以 index_time_list  中的 time 為排序標準
    return x[1]

arrange_list = sorted(index_time_list,key = return_time_value) ## 排序化，讓 arrange_list =[ [3,1], [1,3], [2,3], [0,5]]
for i in arrange_list: ##最後利用迴圈跑出排序後每個 time 的位置值
    print(i[0],end=' ')
```

這一定不是最好的寫法，但你可以試著從這個角度再設計看看你的程式～

**Comment by Poyu781** [comment]
剛剛又看了一下你寫的，基本上就是你的第一個 for 迴圈，是根據你的 len(a) 決定的，再來下一個迴圈，又跟著 a 跑了 len(a) 次，所以你這樣設計，會跑 len(a) 平方次
