### ISSUE TITLE
[Homework 2] 尋找低谷

### ISSUE THREAD

**Issue by HSIAOWENHSUAN** [coding-coworking-club/basic-python-2020-fall#215]
## 提交連結

https://judge.ccclub.io/status/2fe9d5eaf44b4cafd7bf4cd96676d4e4

## 程式碼

```python
num_lst = [int(i) for i in input().split()]
adjust_num_lst = num_lst[1:(len(num_lst)-1)]
min_valley = min(adjust_num_lst)

for i in range(len(num_lst)):
    if min_valley == num_lst[i]:
        print(i)
```

## 問題描述

助教你好：
我的想法是因為要尋找最低點，而題目保證只有一個低谷且不會有相同數值的情形，所以也就是扣除第一個值和最後一個值後取最小值後，再去找最小值在原本num_lst中的位置，將測試帶入都對，但在批改系統顯示wrong answer
再麻煩助教，謝謝～

**Comment by Poyu781** [comment]
題目有寫錯，如果有兩個低谷，需要產生兩個數字喔

**Comment by Poyu781** [comment]
像是 11 5 13 12 17 這樣的話，需要產生 512 這樣的 output

**Comment by yeutong** [comment]
@Poyu781  不是這樣耶
低谷的條件是比相鄰兩邊都低，而這樣的情況只會出現一次。題目保證不會有相同數值只限於相鄰邊，也就是不會出現 1 2 2 3 4 這種狀況。但有可能會有 1 2 3 2 3 ，其中低谷出現在 index 3 的位子，因為 2 比相鄰兩邊的 3 都來得小。
因此  11 5 13 12 17 這種情況不會發生，因為 5 比左右都小，12 也比左右都小 ，出現了兩個符合低谷條件的位子

@HSIAOWENHSUAN  所以不能直接找最小值，而且低谷的數值可能出現不止一次。

**Comment by Poyu781** [comment]
@tong4627 
``` python
int_lst = [ int(i) for i in input().split() ]
answer = ''
for index_in_list in range(1,len(int_lst)-1):
    if int_lst[index_in_list-1] > int_lst[index_in_list] and int_lst[index_in_list+1] > int_lst[index_in_list] :
        min = index_in_list
        answer = answer + str(min)
print(answer)
```
我的寫法，如果輸入 11 5 13 12 17
就會產生 13 （index 1 and index 3 )，不過我這樣寫會對，的確是因為你說的，系統給的數字只會有一個最低谷，
所以我後來直接 print(min) 的答案也是對的

那不好意思，給錯方向了！
