### ISSUE TITLE
[Homework 2] 尋找低谷

### ISSUE THREAD

**Issue by ChiHsinTseng** [coding-coworking-club/basic-python-2020-fall#216]
## 提交連結

https://judge.ccclub.io/status/682f387d6f5133112e09f02acd8d47f1
## 程式碼

```python
mountain = [int(n) for n in input().split()]
ans = []

for i in range(len(mountain) - 2):
    if mountain[i] < mountain[i - 1] and mountain[i] < mountain[i + 1]:
        ans.append(mountain[i])
        
print(mountain.index(min(ans)))
```

## 錯誤訊息

Runtime Error
## 問題描述

我的想法是先 input 一個山稜線的 list，跟給一個答案的空 list，for 迴圈 range 減二是因為扣除頭尾，那當 i 同時小於前後兩個 index 的同時就把他 append 到 ans。
用 judge 上兩筆資料測試都是正確的，不知道還有哪裡是考慮不夠周全，再麻煩助教了，謝謝！

**Comment by yufang3132** [comment]
雖然我不是助教>_<  但在range的設定上，這樣如果低谷在倒數第二個時候，是不是會顯示不出來

**Comment by yeutong** [comment]
@ChiHsinTseng 
```
if mountain[i] < mountain[i - 1] and mountain[i] < mountain[i + 1]:
```
這個是低谷的條件沒有錯，題目保證低谷會恰好出現一次，也就是說這個條件只會滿足一次。不過要小心邊界條件（當 i = 0 時）會發生什麼事。

**Comment by yeutong** [comment]
可以參考 #215 ，裡面有對題目以及測資更詳細的說明 ~

**Comment by ChiHsinTseng** [comment]
@tong4627 大概了解該怎麼改了，謝謝助教～！

@yufang3132 謝謝你的提醒><！！
