### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by yufang3132** [coding-coworking-club/basic-python-2020-fall#217]
## 提交連結

https://judge.ccclub.io/status/3044eebe5dea3396be4b4834b73069fd

## 程式碼

```python
name_lst = input().split()
debt_lst = input().split()
name_lst, debt_lst = zip(*sorted(zip(name_lst, debt_lst)))
 
def finding(name_lst, debt_lst, target):
    mid = len(debt_lst)//2
    if target == name_lst[mid]:
        return debt_lst[mid]
    elif target < name_lst[mid]:
        return finding(name_lst[:mid], debt_lst[:mid], target)
    else:
        return finding(name_lst[mid:], debt_lst[mid:], target)

visit_lst = []

while True:
    try:
        visit_name = input()
        visit_lst.append(visit_name)
    except:
        break

for visit_name in visit_lst:
        print(finding(name_lst, debt_lst, visit_name))

```

## 問題描述

試著用了二元搜索，但還是超過時間

解題的想法是把欠債金額，跟欠債者的名字一起排序，讓兩個串列排序之後，維持互相對應的狀態，然後針對每次輸入的欠債者名字進行二元搜索，找到之後印出相對應的金額

**Comment by yeutong** [comment]
嗨嗨 @yufang3132  ，你的做法是對的！ 
之前把時間限制壓比較緊是為了不要讓大家用 index 直接去找，不過因為你的做法概念上是沒有問題的，所以我把題目的時間限制拉寬一點點，你再丟一次同樣的程式碼應該就可以通過了！

另外如果你好奇要怎麼進一步節省時間的話，可以嘗試看看在做二元搜索的時候不要把整個 list 傳入，可以只記錄目前要搜索的 起始 index 跟 結束 index （跟直接對 list 切片的概念差不多）。因為不用一直複製 list ，所以會快很多，應該可以壓在 200ms 內

**Comment by yufang3132** [comment]
謝謝助教～
之後也會照助教教的，再試著節省時間看看！
