### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by Unstopab** [coding-coworking-club/basic-python-2020-fall#22]
## 提交連結

https://judge.ccclub.io/status/3e5ffb2873688d99e7eff76a2381947b

## 程式碼

```python
x = input()
x = x.title()
x = x.split()
words = []

for i in x[1:-1]:
    if (i == "To" or i == "A" or i == "An" or i == "The" 
    or i == "From" or i == "For" or i == "Of" or i == "And" or i == "In"):
        words.append(i.lower())
    else:
        words.append(i)
print(x[0], end = " ")
for i in words:
    print(i, end = " ")
print(x[-1], end = "")
```

## 問題描述

不好意思，我在Jupyter Notebook上試跑題目範例能跑出正確結果，但放在批改系統則顯示為Wrong Answer，不曉得是哪邊沒考慮清楚，謝謝！

**Comment by Neptune2901** [comment]
最後一個字假如不該大寫還是會變大寫

**Comment by Unstopab** [comment]
謝謝您的回覆，想再向您確認一下，根據題目：「書籍、期刊、報紙等作品的標題中**每個字皆須首字母大寫**，除了to、冠詞a、an、the、少於五個字母的連接詞from、for、of、and、in**不須大寫，除非這些字出現於標題句首或句尾**。」這樣最後一個字會有不該大寫的情況嗎@@?

**Comment by Neptune2901** [comment]
我漏看XD
問題可能出在str.title()
[詳見](https://www.programiz.com/python-programming/methods/string/title)

**Comment by Unstopab** [comment]
感謝~關鍵出在title遇到英數夾雜的字串如hj36hj會輸出成Hj36Hj，後來已改用別種寫法過關了

**Comment by dovewalk** [comment]
> 我漏看XD
> 問題可能出在str.title()
> [詳見](https://www.programiz.com/python-programming/methods/string/title)

我也遇到一樣的問題 感謝解答
