### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by sydney1111** [coding-coworking-club/basic-python-2020-fall#221]
## 提交連結

https://judge.ccclub.io/status/5ee3357f671d112cf843ba31be0d7f09
## 程式碼

```python
#5 討債集團(用二元搜索)
def search(namelst, moneylst):
    midst = len(namelst) // 2
    if namelst[midst] == name:
        return moneylst[midst]
    elif namelst[midst] > name:
        return search(namelst[0 : midst], moneylst[0 : midst])
    else : return search(namelst[midst:], moneylst[midst:])
namelst, moneylst = input().split(), input().split()
moneylst =[moneylst for _, moneylst in sorted(zip(namelst, moneylst))]
namelst = sorted(namelst)
runlst = []
while True :
    try:
        runname = input()
        if runname == "":
            break
        else:
            runlst.append(runname)
    except:break
for name in runlst:
    print(search(namelst, moneylst))

```

## 問題描述

一直是time limit exceeded，不曉得還可以怎麼改....。
我的解題思路是，先定義函數，找出中位數，若中位數即要找的答案，return其相對位置的金額，若中位數的名字>目標，取位置零到中位數開始遞迴，否則則從中位數到尾遞迴。接著處理input，將名字和金額一起排序後取出金額自成list，再讓名字自己有排序好的list，然後處理不定量input，最後以runlst迴圈取出每個開始函數內容。
以上是最原始的版本，在附上的連結中我嘗試多加了一項處理，若是目標名字先前已出現過，就直接取其答案，不用再進行一次二元搜索，但這樣時間反而變慢了，也想知道為什麼，謝謝。

**Comment by yeutong** [comment]
嗨嗨 @sydney1111  可以再試著丟一次 code，應該可以壓在時間內。另外也可以參考 #217 ，有提到如何進一步節省時間
關於你多做的處理，我有看到程式碼了，但你只是把找過的名字存在 `gothrough` 跟 `anslst` 裡面，遇到相同的名字還是會進行二元搜索，所以手續變多了但工沒有少XD （不確定是傳錯版本還是忘記做這個部分了？）
不過你的想法蠻不錯的， 如果把它實作完應該會變快一些~
