### ISSUE TITLE
[Homework 2] 不知道要輸入幾行

### ISSUE THREAD

**Issue by StarCat0928** [coding-coworking-club/basic-python-2020-fall#225]
## 提交連結

https://judge.ccclub.io/status/f0ff02da58bdc9f5658f29e004336e2d
## 程式碼

```python
s1 = input()
lst = [s1]
while (s1 != ""):
    try:    
        s1 = input()
        lst.append(s1)

    except:
        break

lst2 = lst[0:-1]
for i in range(0, len(lst2)):
    if(i == len(lst2)-1):
        print(lst[i], end="\b")
    else:
        print(lst[i] + "-", end="")
```

## 錯誤訊息

Wrong Answer
## 問題描述

我的想法是這樣的，將輸入的部分放入一個串列中，在分別列印並加入-，最後一個在使用Backspace脱逸字元\b。我在Spyder上跑都輸出正確，但不知為什麼在judge上就會出現Wrong Answer。

**Comment by winnywu508** [comment]
目前用jupyter notebook跑出來sample 1 output變成 HoydeA-象牙舟-5:10a.m.-視線所及只剩生

**Comment by StarCat0928** [comment]
我原本是可以全部輸出完，但是最後會多出現一個-，所以我才使用了\b脱逸字元

**Comment by winnywu508** [comment]
你的for lop lst2 = lst[0:-1] 只跑lst 2, 就不會包括最後一個input

**Comment by StarCat0928** [comment]
是指我的迴圈終點沒設定對嗎

**Comment by winnywu508** [comment]
對 這樣都不會跑到最後一個input

**Comment by StarCat0928** [comment]
那我把迴圈終點設定為len(lst2)應該是對的吧

**Comment by winnywu508** [comment]
你可以把lst 2 print出來看看對不對

**Comment by winnywu508** [comment]
lst2 = lst[0:-1] <- 這邊你設定lst2要少一個

**Comment by StarCat0928** [comment]
對的，但是最後會多出一個-

**Comment by StarCat0928** [comment]
所以應該要做一個新的串列

**Comment by winnywu508** [comment]
不會阿 用lst就可以了
s1 可以拿掉一個，一開始lst用空的list就可以 （比如說 lst =[])

**s1 = input()**
**lst = [s1]**
while (s1 != ""):
    try:    
        **s1 = input()**
        lst.append(s1)

**Comment by StarCat0928** [comment]
我試試看

**Comment by StarCat0928** [comment]
我改完後還是Wrong Answer

**Comment by StarCat0928** [comment]
```python3
s1 = input()
lst = [s1]
while (s1 != ""):
    try:    
        s1 = input()
        lst.append(s1)

    except:
        break
for i in range(0, len(lst)-1):
    if(i == len(lst)-2):
        print(lst[i], end="")
    else:
        print(lst[i] + "-", end="")
```

**Comment by StarCat0928** [comment]
我測試後輸出正確，但是仍是Wrong Answer

**Comment by winnywu508** [comment]
我看了一下 我用jupyter notebook跑sample 答案是**HoydeA-象牙舟-5:10a.m.-視線所及只剩生活**
問題還蠻容易看出來的，你用visualize跑跑看找找看

http://www.pythontutor.com/visualize.html#mode=display

**Comment by StarCat0928** [comment]
助教，就是我有點看不懂visualize網站在跑些什麼

**Comment by winnywu508** [comment]
那len(lst)用sample1的input來說是多少？
你直接print出來看看

再看一下這一段
for i in range(0, len(lst)-1):
    if(i == len(lst)-2):

**Comment by StarCat0928** [comment]
助教，我更改了我的程式碼，將迴圈的部分修改了一下，範例的測試也OK，但judge還是Wrong Answer
```python3
s1 = input()
lst = [s1]
while (s1 != ""):
    try:    
        s1 = input()
        lst.append(s1)

    except:
        break
lst2 = lst[0:-1]
for i in range(0, len(lst2)):
    if(i == (len(lst2)-1)):
       print(lst2[len(lst2)-1], end="")
    else:
       print(lst2[i] + "-", end="")
```

**Comment by StarCat0928** [comment]
https://judge.ccclub.io/status/cc9705bd1a10f5e06908ad8b67fecd0d

**Comment by StarCat0928** [comment]
![Uploading Screen Shot 2020-10-18 at 12.30.19 PM.png…]()

**Comment by StarCat0928** [comment]
![Screen Shot 2020-10-18 at 12 30 19 PM](https://user-images.githubusercontent.com/61607964/96358791-c9b9b400-113d-11eb-93e2-b563647be933.png)

**Comment by winnywu508** [comment]
你看你的lst 2 
我把lst 跟lst 2都print出來給你看

![Uploading Screen Shot 2020-10-18 at 12.43.35 PM.png…]()

**Comment by winnywu508** [comment]
<img width="980" alt="Screen Shot 2020-10-18 at 12 43 35 PM" src="https://user-images.githubusercontent.com/55421188/96358968-b0196c00-113f-11eb-92f2-89c6263417cf.png">

**Comment by StarCat0928** [comment]
我懂了助教，lst2 = lst[0:-1]那裡錯了

**Comment by StarCat0928** [comment]
應該要改成lst2 = lst就可以了
