### ISSUE TITLE
[Homework 2] 尋找低谷

### ISSUE THREAD

**Issue by JayJCChiu** [coding-coworking-club/basic-python-2020-fall#227]
## 提交連結

https://judge.ccclub.io/status/eff470ac0509a77256f0364590c2d807
## 程式碼

```
#先定義一個 function 找出低谷，且先排除邊界，以免產生問題
def valley(mt):
    for i in range(1, len(mt)-1):
        if mt[i] < mt[(i-1)] and mt[i] < mt[(i+1)]:
            return mt.index(mt[i])
#呼叫 function，並處理邊界問題
mt = [int(i) for i in input().split(' ')]
if valley(mt) != None:
    print(valley(mt))
else:
    if mt[0] < mt[1]:
        print(mt.index(mt[0]))
    elif mt[-1] < mt[-2]:
        print(mt.index(mt[-1]))
```

## 錯誤訊息

Wrong Answer
## 問題描述

測資有通過，且我有測試連續遞增（1 2 3 4）或連續遞減（5 4 3 2）等狀況；另外我也有參考助教回應其他同學的問題，不過仍不解的是，若低谷出現在邊界、會希望呈現何種輸出結果？以目前我的測試結果，是會顯示邊界的index，不過依據錯誤訊息顯示，這不是題目想要的QQ，再麻煩助教撥冗提點，謝謝！

**Comment by soarfox** [comment]
我不是助教，但我有參考到其他同學給的提示，所以才順利解出這一題。

如果低谷出現在邊界，那當然希望結果是「不要印出邊界的index」，因為題目內文有提到：「……小明決定自己只要遇到低谷，也就是『比兩端都低的地方』，他就休息……」，因此邊界就不納入低谷的範圍中，這也就是為什麼很多同學會將邊界值排除在外的緣故；可以試試看類似這樣的測資：[ 4 15 14 13 12 4 10 11 ] (參考 #178 同學提出)，看看你的程式會印出哪個index？　也可參考 #215

**Comment by JayJCChiu** [comment]
@soarfox 感謝這位同學的解釋跟測資，我重新調整了寫法也解出來了，謝謝你～～
