### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by ffj238** [coding-coworking-club/basic-python-2020-fall#229]
## 提交連結

https://judge.ccclub.io/status/1eb96fd0f8539005d968101e7a7c5ebf

## 程式碼

```python
name = list(input().split())
money = list(input().split())
count = "True"
order = []
name_ascii = []

def middle(s):
    if len(s) % 2 == 0:
        middle_n = (int(s[int((len(s)/2)-1)])+int(s[int(len(s)/2)]))/2
        middle_n = int(middle_n)
    else:
        middle_n = s[int((len(s)-1)/2)]
    return middle_n

def search(n, lst):
    if n == middle(lst):
        a = name_ascii.index(n)
        return money[a]
    elif n < middle(lst):
        left = lst[:len(lst)//2]
        return search(n, left)
    else:
        right = lst[len(lst)//2:]
        return search(n, right)
    
def ascii(s):
    temp = []
    for i in s:
        ascii_a = str(ord(i))
        temp.append(ascii_a)
    temp = int("".join(temp))
    return temp

for i in name:
    name_ascii.append(ascii(i))
name_ascii_s = sorted(name_ascii)

while count == "True":
    try:
        order.append(input())
    except:
        count = "False"
        
for i in order:
    a = ascii(i)
    print (search(a, name_ascii_s))  
```

## 錯誤訊息

Runtime Error

## 問題描述

助教好，不好意思這麼晚才問問題，我真的走投無路ㄌ...
目前在寫這題的想法：

1. name 串列儲存人名，money 串列儲存欠債金額
2. middle 函式取得串列中位數
3. search 函式執行二元搜索
4. ascii 函式執行 ASCII code 轉換
5. name 串列內每個人名轉成 ASCII code，存成 name_ascii 串列
6. name_ascii 串列再 sorted 為 name_ascii_s
7. order 串列儲存討債順序
8. 將 order 串列內每個人名轉成 ASCII code 後，以 search 函式在 name_ascii_s 中比對
9. 找到後，從原始 name_ascii 串列取得索引值，以同個索引值取得 money 串列的金額並印出

目前以judge系統提供的測資在Jupyter內測試都沒有出現問題，
但是judge時仍會出現Runtime Error，實在不知道哪裡出了問題只好上來詢問，謝謝QQ

**Comment by yeutong** [comment]
我這邊幫你測是在執行 `middle()` 這個函數的時候會出現 `list index out of range` 的錯誤訊息，把有問題的 s 印出來之後發現是空的 list。

**Comment by yeutong** [comment]
可能要再仔細看一下 `search()` 裡面的處理，我猜是神秘的邊界問題，但我看了半天也沒發現問題在哪QQ 加油！
