### ISSUE TITLE
[Homework 2] 不知道要輸入幾行

### ISSUE THREAD

**Issue by enn-lu** [coding-coworking-club/basic-python-2020-fall#230]
## 程式碼

```python
string='' 
line=input()
print(line)
while line:
    line=line.replace('/n','')+'-'
    string+=line
    print(line)
    line=input()
string=string[0:-1]
print(string)
```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/71515972/96352805-dd8ef700-10f8-11eb-9a53-d82b1be6a294.png)

## 問題描述
用了各種方法去judge 系統都是錯誤，但在jupyter卻是正確的
如果程式有問題
我是先把每一個都加上-然後再用index取道最後一個字串

**Comment by yeutong** [comment]
參考 #171

**Comment by enn-lu** [comment]
我參考以後找不到他的錯誤，是要改用try 嗎?但寫不出我的想法
