### ISSUE TITLE
[Homework 2] 討債集團

### ISSUE THREAD

**Issue by ChiHsinTseng** [coding-coworking-club/basic-python-2020-fall#235]
## 提交連結

https://judge.ccclub.io/status/b4cb27f3d9157d962cd8d23bf89b6e65
## 程式碼

```python
def find(names, money, name_list):
    middle = len(names) // 2
    if name_list == names[middle]:
        return money[middle]
    elif name_list < names[middle]:
        return find(names[:middle], money[:middle], name_list)
    elif name_list > names[middle]:
        return find(names[middle:], money[middle:], name_list)

names = input().split()
money = input().split()
name_list = input()
lst1 = []

while name_list != '':
    try:
        lst1.append(find(names, money, name_list))
        name_list = input()
    except:
        break
        
print('\n'.join(lst1))    
```

## 錯誤訊息

Wrong Answer
## 問題描述

我是先用二元搜索的方式寫出一個 function，輸入的部分 names=欠債外國人名，money=對應欠款金額，name_list=催討順序，再給一個空的 lst1 作為之後輸出答案的 list。
之後當 name_list 不等於空白的時後會一直可以 input，最後輸出要換行所以用 \n。
用 Jupyter 上的使用測資都是正確的，但在 Judge 上顯示 wrong answer，不知道是哪裡錯了><

**Comment by yeutong** [comment]
給的名字不是排序好的噢，需要自己排~

**Comment by ChiHsinTseng** [comment]
@tong4627 嗨助教～想確認一下是"欠債外國人名"的部分要排序嗎？

**Comment by yeutong** [comment]
對的，可以參看二元搜索那題，要做二元搜索的前提是尋找的列表要經過排序，否則你比較了中位數之後回傳前半或後半都沒有意義。

**Comment by ChiHsinTseng** [comment]
@tong4627 助教我又有問題ㄌ>< 我後來用 zip 跟 sort 的方式有寫出來，結果是time limit exceed

**Comment by ChiHsinTseng** [comment]
@tong4627 後來用 zip 跟 sort 寫就成功了～～謝謝助教：）
