### ISSUE TITLE
[Homework 2] 檢查密碼

### ISSUE THREAD

**Issue by f89234** [coding-coworking-club/basic-python-2020-fall#236]
## 提交連結

https://judge.ccclub.io/status/c3622ae81cfeff9abefb25712c171a63

## 程式碼

```python

#包含英文和數字的密碼
def password(p):
    English = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    Number = "0123456789"
    combine = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    temp = 0
    kevin = 0
    burger = 0
    for egg in p:
        if egg in English:
            temp = 1
    for ham in p:
        if ham in Number:
            kevin = 1
    for burger in p:
        if burger not in combine:
            burger = 1
    if temp and kevin == 1 and burger!= 1:
        return True
    else:
        return False

p = input()
print(password(p))
```

## 錯誤訊息

wrong answer

## 問題描述

我把有數字設為 temp =1
有英文設為 kevin =1
沒有在數字跟英文串列中的 burger =1
(burger 是出現不在數字、字母的時候要是 1)
然後去跑每一個題目雖然是正確的 True and False
但不曉得邏輯上哪裡有誤？

**Comment by Poyu781** [comment]
那個...我又路過，變數請好好設定，你這題會錯，跟你變數亂使用有關係！
請注意一下，你 burger 要拿來當判斷有無亂碼進入密碼的變數，又拿burger in p ，等於說你 burger 這個變數，不只是會  1 or  0 ，還有可能是其他從 input()  放到 p 這個變數裡面的東西，
如果看不懂，歡迎試試看這一組 input() : 12Er#ERE121
你應該就知道了～
另外建議你可以看一下變數定義的文章，不然你未來變數一多，絕對不知道培根跟漢堡是什麼關係的！

**Comment by f89234** [comment]
喔喔喔喔喔喔
我現在才發現變數設定重複！！！！！！！！難怪！！！！！
非常感謝
雖然現在無法進系統看是否修改後正確，但謝謝同學解惑～～～～
