### ISSUE TITLE
[General] 揪狼殺

### ISSUE THREAD

**Issue by troublecat55** [coding-coworking-club/basic-python-2020-fall#237]
## 提交連結

https://judge.ccclub.io/status/4bc9a56aff8210cd3863fca30642ab3d
## 程式碼

```python
n = int(input())
dic = {}
while n > 0:
    s = str(input())
    n -= 1
    l = [int(num) for num in s.split()]
    for item in l:
        if item in dic: #assign key as item(available time), value as amount of items(how many people available at that time)
            dic[item] += 1
        else:
            dic[item] = 1
    dic_sorted = {k:v for k,v in sorted(dic.items(), reverse=False, key=lambda item:item[0])} #sorted dictionary from key(available time)

time_lst = [] #have a global time list
for key, value in dic_sorted.items(): #if more than 12 people(value) want to join in a specific time, then append the time(key) into time list
    if value >= 12:
        time_lst.append(key)

if not time_lst: #if time_lst is empty(no more than 12 people want to join a specific time)
    key_lst=list(dic_sorted.keys()) #convert key into a new list
    val_lst=list(dic_sorted.values()) #convert value into a new list
#     print(val_lst) #debug
    for i in range(len(val_lst)):
        if val_lst[i] == max(val_lst): #find the maximum people in value list
            time_lst.append(key_lst[i]) #append the correspond key(time), and it or them into time_list 

#print(time_lst)  #debug

def find_continious_sub(l): #a function to find continuous subarray in time_list
    sub_list = []
    ans = []
    sub_empty = True
    second = 0
    for i in range(len(l)):
        if len(l) == 1:
            ans.append(l[0])
        elif l[i] - second != 1:
            if sub_empty:
                sub_list.append(l[i])
                second = l[i]
                sub_empty = False
            else:
                ans.append(sub_list)
                sub_list = []
                sub_list.append(l[i])
                second = l[i]
        else:
            sub_list.append(l[i])
            second = l[i]
            sub_empty = False
    if sub_empty == False:
        ans.append(sub_list)
    
    return(ans)


if len(time_lst) == 1:#if there's only one item in time_list, print it(answer)
    print(int(time_lst[0]))
else: #divide continuous number(time) into subarray in time_list, and save it into sub_time_lst
    sub_time_lst = find_continious_sub(time_lst)
    # print(sub_time_lst) #debug
    
    for l in sub_time_lst: 
        final_lst = sub_time_lst[0] #assign the first subarray into final_list
        if len(l) > len(final_lst): #if the length of other arrays are longer than first array then substitute it 
            final_lst = l
        
    print(int(final_lst[0])) #print the first item of final list(answer)
```

## 錯誤訊息

Wrong Answer

## 問題描述

我在repl.it丟測資有通過，debug一個晚上不知道為什麼會Wrong Answer，想知道是我誤解題目的意思嗎還是漏掉或寫錯什麼。

1.我的作法是先接測資，丟到dictionary 裡，用時間當key，在那個時間有幾個人ok當value。
2.接著建一個time_list，如果dictionary 裡value（人數）大於等於12，就把對應的key（時間）存到time_list裡
3.如果time_list是空的（沒有任何一個時間有或超過12人參加），則把dictionary的key, value分別存在新的list裡，然後找value list裡的最大值（最多人ok），再把對應的key（最多人ok的時間）存在time_list裡。
4.（然後我中間寫一個function，可以找list連續值，然後轉成subarray。）
5.接下來看time_list ，如果只有一個item（人數都小於12），那可以直接print出來
6.如果time_list有多個item，那就用「找list連續值，然後轉成subarray的function」轉成subarray（時間如果有連續會變成一組），先把第一個subarray存進final_lst，如果其他subarray長度比第一個長就取代（連續時間長就取代），最後print final_lst的第一個值。

先感謝助教！

**Comment by fangha1216** [comment]
在judge上會得到wrong answer有可能是因為judge上的系統不支援字典排序
導致順序錯誤
這邊有個測資可以讓你測試看看

25
16 22 0 19 6 4 11 9 20 10 5 7 21
12 16 13 5 10 7 20 14 21 17
8 11 6 16 15 19 0 9 10 23 20 12 1 3 21 7 22 4 17 14
6 14 23 8 4 7 3 20 21 17
18 15 19 10 6 12 20 7 3 21 23 14 22 16 13 0 5 9
13 19 0 1 22 21 14 17 5 15 8
17 8 15 3 14 4 21 20 23 11 13 16 1 5 12 22 2 6 10 7
11 9 23 17 8 16 10 4 14 1
1 3 5 18 17 20 11 16 19 4 0 23 15 14 7 10 12 6 2
23 5 2 20 12 0
8 16 1 19 6 9 15
23 18 16 7 0 11 22 5 2 6 3
7 4 6 3 0 14 12 16 2 23 15
23 2 11 20 1 0 18 14 22 12 21 13
21 9 22 17 12 13
17 6 23 21 8 9 3 7 1 2 11 13 20 22 10 4
6 9 11 16 5 12 18 17 13 8 10 22 0 4 3 2
7 4 23 0 8 21 2 15 16 13 12 9 19 22 1 14
13 7 20 0 22 1 12 19
16 17 4 13 8 6 22 9 10 5 14 0 7 12 19 21 20 2 3
3 17 23 12 14 13 2 21 1 20 15 7 9
17 23 19 14 12 4 20 15 1 7 22 0 2 9 18
1 14 12 21 0 4 3 11 16 2 15 23 9 5 13 8
15 0 8 2 16 10 23 3 4 19
2 18 16 12 15 19 1 21 11 10 13 8 6 23 17 0 14 20

answer:
12

**Comment by troublecat55** [comment]
ace了，非常感謝助教提供側資！是我最後一個條件判斷出問題，眼花寫錯，跟dictionary好像無關XD
