### ISSUE TITLE
[Week 6] 小明的電話簿

### ISSUE THREAD

**Issue by Robbie-LAN** [coding-coworking-club/basic-python-2020-fall#238]
## 提交連結

https://judge.ccclub.io/status/814bb1e4e66bb864c45862e999574b3a
## 程式碼

```
#小明的電話簿

dic = {}
list_ss = []

while True:
    ans = input()
    if ans == 'end':
        break
    elif 'a' in ans:
        list_a = ans.split()
        dic[list_a[2]] = list_a[1]
        dic[list_a[1]] = list_a[2] #人名電話當key都有
    elif 's' in ans:
        list_s = ans.split()
        list_ss.append(list_s[1])
            
for i in (list_ss):
    try:
        print(dic[i])
    except:
        print(f"Cannot find {i}")

```

## 問題描述

在Jupyter上可正常執行，但在judge系統上卻顯示WA，不知哪裡出了問題

**Comment by Viggochang** [comment]
你的做法是把所有電話連絡人資訊存進 dic 裡面
再把所有查找資訊存進 list_ss 裡面
當 dic 和 list_ss 都完成後
再針對 list_ss 做 for 迴圈依序輸出查詢結果

但這樣的作法忽略了 "加入電話資訊" 和 "查找資訊" 之間的順序問題
舉例來說，若你的輸入為:
s kevin 
a kevin 123456
正確的輸出應該是 Cannot find kevin
因為在查找kevin時，kevin的電話資訊還沒加入
但你的做法先把電話資訊都建立好了才開始查找，因此會輸出 "123456"

[改進方向]
當 input() 出現 s 時立刻進行查找

**Comment by Robbie-LAN** [comment]
原來題目是要我們出現s就立刻尋找，我誤會成是要最後在一次找全部的s，我懂了也AC了，謝謝助教
