### ISSUE TITLE
[Week 6] 神奇翻譯機

### ISSUE THREAD

**Issue by evetyy** [coding-coworking-club/basic-python-2020-fall#239]
## 提交連結
https://judge.ccclub.io/status/e2ef1e4c4873302aeb1115315b4c1d87

## 程式碼

```python
n = int(input())
dic = {}

for i in range(n):
    key, value = input().split()

lst = [input().split(" ")]
for word in lst:
    lst = lst.append(dic[word])
    
print(' '.join(lst))
```

## 錯誤訊息

Runtime Error
## 問題描述

想法是先建一個字典，輸入最後一行後，找出每個字在字典裡的位置，再加到list裡，最後把list印出來

**Comment by chun9425** [comment]
你的程式在下面這行會出錯
```python
key, value = input().split()
```
使用 split() 後的結果是一個串列，
所以無法把這個串列指定給 key, value 這二個變數
