### ISSUE TITLE
[General] 幾連霸

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#24]
## 提交連結

https://judge.ccclub.io/status/eb1cf46d5b0efb2689894ca381e3998c
## 程式碼
n=input().split()
count=0

aList=[]
for i in range(len(n)-1):
    if int(n[i+1])==int(n[i])+1:
        count+=1
    elif int(n[i+1])!=int(n[i])+1:
        aList.append(count)
        count=0
aList.append(count)
print(max(aList)+1)

此程式碼經批改系統測試為正確

```python

```

## 錯誤訊息

題目本身似乎有錯誤
## 問題描述

助教您好，本題似乎有兩個錯誤
1. Description要求我們輸出「連續的數（遞增）最多"幾次"」，但根據批改系統的解答回推，系統是要求「連續的數（遞增）最多"幾個"」，也就是"遞增次數+1"
2.Sample Input 1 打錯了，應該是「1 2 3 4 5 6 7 8」，原先的「1 2 3 4 5 6 78」並不會得出Sample Output 1的結果

**Comment by jeffery12697** [comment]
請參考[學員須知](https://www.notion.so/ccClub-2020-Fall-ed14cfc6c5ed46ceadf294f419cb80c3)依規定附上提交連結

**Comment by yles840421** [comment]
> 請參考[學員須知](https://www.notion.so/ccClub-2020-Fall-ed14cfc6c5ed46ceadf294f419cb80c3)依規定附上提交連結

已更改為程式代碼連結
因我原意是想提醒此題內容有誤，所以原本附上的是題目連結

**Comment by jeffery12697** [comment]
對耶，感謝提醒～

**Comment by yles840421** [comment]
> 對耶，感謝提醒～

哈哈不會~感謝助教更正!
