### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by ambre915** [coding-coworking-club/basic-python-2020-fall#240]
## 提交連結

https://judge.ccclub.io/status/8bb3924b631748f3175fb3b14cf0f50a

## 程式碼

```python
## 11-2：字串字典
s = str(input())
s = list(s)
s = sorted(s)
dict = {}

for i in range(len(s)):
    s[i] = s[i].lower()
print(s)

for key in s:
    dict[key] = dict.get(key, 0) + 1   
print(dict)
    
for key in dict:
    if key.isalpha() == True:
        print(key, end = '')
        print(dict[key], end = ' ')
    else:
        continue
```

## 問題描述

還以為是蠻簡單的練習但我找不到我的盲點XD
我的想法是字串轉為list後，把list中的字母全部轉小寫。
再把它存成字母與出現次數的字典資料型態（其實那裡是上網找的寫法，我還沒有很明白’dict.get(key, 0) + 1‘這個寫法的意思）。最後就是列印出來了。
我也有把大小寫視為相同以及符號不計給考慮進去，但不確定wrong answer的原因為何，還請助教幫忙解惑，感激不盡！

**Comment by Neptune2901** [comment]
因為先排序才轉成小寫，可能會有原本為大寫的字母被排在前面，導致輸出沒有按照字母序排列

**Comment by ambre915** [comment]
> 因為先排序才轉成小寫，可能會有原本為大寫的字母被排在前面，導致輸出沒有按照字母序排列
喔喔喔原來如此！！！問題解決，謝謝助教 <3
