### ISSUE TITLE
[Week 6] 助教業績統計

### ISSUE THREAD

**Issue by evetyy** [coding-coworking-club/basic-python-2020-fall#242]
## 提交連結

https://judge.ccclub.io/status/df35cc200f11b1b698d1747fc960da3b
## 程式碼

```python
string = input() 
highest = 0
n = 1

while string != '0':
    new_string = string.split()
    total = 0
    for word in range(len(new_string)):
        total += int(new_string[word])
        if total < highest:
            n += 1
            string = input()
            break
        else:
          highest = total

print(n, highest)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/71555507/96541444-90667d00-12d2-11eb-85ac-27a907e6dd28.png)
![image](https://user-images.githubusercontent.com/71555507/96541521-cb68b080-12d2-11eb-8d89-1bf8c2a6da1c.png)

## 問題描述

邏輯是當輸入的字串不等於0時，把字串分開，將每個數字加總成total，如果total比highest數字大的話，就用這個值取代highest，如果比較小的話，再次輸入下一筆字串，n+1表示這是下一位助教的業績。
程式可以跑，但是測資的答案錯誤。用Trace code發現是 total += int(new_string[word]) 無法將所有數字加總，像是截圖的當時，輸入的字串是[5 6 1]，預期結果應該 total = 5 + 6 + 1，但是實際上只有 total = 5，就跳下一行了。
想請助教幫忙看看，也想請問如何先將整串加總後，再跳下一行比較 total 和 highest 的數字呢?
隨堂練習寫了很久但是一題都還沒解出來要變成缺席了QQ 謝謝助教!!

**Comment by Neptune2901** [comment]
裡面的for迴圈還沒加總完就被拿去跟highest相比，然後比較小就break了

**Comment by evetyy** [comment]
https://judge.ccclub.io/status/6aa31985f36c0b3b312dff2555068688

助教不好意思, 加了條件還是無法成功, 請問能不能提供一些建議呢? 期望自己能趕在23:59前解出來 ><  謝謝!!

**Comment by evetyy** [comment]
https://judge.ccclub.io/status/177ba42c1847f7381e5c0eb57daabe0c

換個方式先將串列中的字串轉成數字, 再相加, 還是有Runtime error, 找不出來哪裡有誤 ><
