### ISSUE TITLE
[General] 括號合法

### ISSUE THREAD

**Issue by sydney1111** [coding-coworking-club/basic-python-2020-fall#243]
## 提交連結

https://judge.ccclub.io/status/e2843d37746330dbf50647d4b8815256
## 程式碼

```python

#180035 括號合法
try:
    s = input()
    lst = list(enumerate(s))
    biggest = 0
    left = []
    right = []
    for i, j in lst:
        if j == '(':
            left.append(i)
        if j == ')':
            right.append(i)
    if len(left) == len(right):
        for i in range(len(left)):
            if left[i] < right[i]:
                ans = "True"
            else:
                ans = "False"
                break
        print(ans)
    else:
        print("False")
except:
    print("False")
```

## 問題描述

結果是wrong answer，不曉得哪裡出錯。
我的解題思路:
1.將input的內容進行enumerate形成有位置與內容的list
2.以list進行迴圈，若其內容物是左括號，將其位置編號加入left list，若為右括號，位置編號加入right list
3.左括號與右括號的數量需一致，若否則輸出False
4.若兩者數量一致，以其長度進行迴圈，在left list和right list的相同位置上(兩list的內容排序皆由小至大)，在left list內的數字需比在right list內的數字小，即須有一個左括號在右括號前面，否則輸出False。

**Comment by winnywu508** [comment]
如果什麼都不輸入的話output要出現true
