### ISSUE TITLE
[Homework 3] 推薦系統

### ISSUE THREAD

**Issue by addie-tyc** [coding-coworking-club/basic-python-2020-fall#244]
## 提交連結
https://judge.ccclub.io/status/eb6137aea4dd1f22fe4e1981282da036

## 程式碼

```python
# 推薦系統
p = int(input())
x = input().split(" ")
d = {}
while x != ["end"]:
    d[x[0]] = x[1:len(x)]
    x = input().split(" ")
lst = []
for k in d.keys():
    lst.append(d[k])

# 計算相似程度
score = []
for i in range(len(lst)):
    s = []
    for j in range(len(lst)):
        count = 0
        for m in lst[i]:
            for n in lst[j]:
                if m == n:
                    count += 1
        s.append(int(100*count/len(lst[i])))
    score.append(s)

# 建立推薦商品清單
items = []
for i in range(len(lst)):
    item = []
    for j in range(len(score[i])):
        if score[i][j] >= p:
            item_ = list(set(lst[j]) - set(lst[i]))
            for z in item_[::-1]:
                item.append(z)
    items.append(list(dict.fromkeys(item)))

# 印出答案
for i in range(len(items)):
    print(list(d.keys())[i], end = " ")
    print(" ".join(items[i]))

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/65952631/96568596-b30c8c00-12fa-11eb-9ecb-a672d0af3fce.png)

## 問題描述
題目提供的測資是對的，不曉得哪邊邏輯不對，還請助教們指點 QwQ
感謝，辛苦了！

**Comment by winnywu508** [comment]
**sample two:**
r B
l C U
q Z S B
c 

最後一個 q的item順序反過來了

**Comment by addie-tyc** [comment]
@winnywu508 感謝您的回覆
但我用上面的 code 跑出來是 SZB ？？
![image](https://user-images.githubusercontent.com/65952631/96963467-446a4100-153b-11eb-8594-24fe6bd2cc86.png)

**Comment by winnywu508** [comment]
![image](https://user-images.githubusercontent.com/55421188/96965248-69ac7e80-153e-11eb-8d8a-842bf83f71da.png)

**Comment by addie-tyc** [comment]
@winnywu508 誒？？？方便請教一下，請問這樣是哪裡出問題了呢？QwQ

**Comment by winnywu508** [comment]
**用python visualize跑跑看下面看看**
step 97 items.append(list(dict.fromkeys(item))) append的list會變成 Z S B

lst = [['S', 'F', 'C', 'D', 'U', 'Q', 'Z'], ['Q', 'D', 'F', 'S', 'B', 'Z'], ['Q', 'F', 'U', 'C', 'D'], ['Z', 'D', 'F', 'U', 'B', 'S', 'Q', 'C']]
score =[[100, 71, 71, 100], [83, 100, 50, 100], [100, 60, 100, 100], [87, 75, 62, 100]]
d = {'r': ['S', 'F', 'C', 'D', 'U', 'Q', 'Z'], 'l': ['Q', 'D', 'F', 'S', 'B', 'Z'], 'q': ['Q', 'F', 'U', 'C', 'D'], 'c': ['Z', 'D', 'F', 'U', 'B', 'S', 'Q', 'C']}
p = 50

items = []
for i in range(len(lst)):
    item = []
    for j in range(len(score[i])):
        if score[i][j] >= p:
            item_ = list(set(lst[j]) - set(lst[i]))
            for z in item_[::-1]:
                item.append(z)
    items.append(list(dict.fromkeys(item)))

# 印出答案
for i in range(len(items)):
    print(list(d.keys())[i], end = " ")
    print(" ".join(items[i]))

![image](https://user-images.githubusercontent.com/55421188/96968249-4e903d80-1543-11eb-973d-5d0300153ba4.png)

**Comment by addie-tyc** [comment]
@winnywu508 嗚嗚謝謝助教！
我跑了發現是自己在 jupyter 上面不知道清單發生了什麼事，顛三倒四然後對了w
但其實只跑一次就會是ZSB www
因為我掌握不到 set 出來之後的順序，於是我就放棄了
```python
# 建立推薦商品清單
items = []
for i in range(len(lst)):
    item = []
    for j in range(len(score[i])):
        if score[i][j] >= p:
            for m in lst[j]:
                if m not in lst[i]:
                    item.append(m) # 把這邊改成巢巢巢狀迴圈
    items.append(list(dict.fromkeys(item)))

# 印出答案
for i in range(len(items)):
    print(list(d.keys())[i], end = " ")
    print(" ".join(items[i]))
```
但結果還是 WA ......
煩請助教不吝指導 QAQ
我有可視看了 sample 測資了 QQ

**Comment by yles840421** [comment]
我發現
1. int(100*count/len(lst[i]))這樣的寫法可能有問題
剛測試int(100*1/3)→33，似乎會自動四捨五入
而int(100*1/3) == 100*1/3→False
假如閾值剛好在界線可能會有誤判
2. 用for k in d.keys()建立會有順序的錯誤
由於dict沒有順序性，每台電腦建立的lst順序可能會不同
向我這邊跑出來的結果就會是
小明 鑰匙
小美 
凱文 卡片 番茄 機車
小華 卡片 錢包 機車 鑰匙

**Comment by yles840421** [comment]
剛解決dict排序的問題就AC了~int那邊不影響這次做題!

**Comment by addie-tyc** [comment]
@yles840421 原來如此，大感謝！
是說我以為 int 會無條件捨去？
