### ISSUE TITLE
[Homework 3] 字串回文

### ISSUE THREAD

**Issue by yihan-lin** [coding-coworking-club/basic-python-2020-fall#247]
## 提交連結

https://judge.ccclub.io/status/4d69063654ae27aba7e146dc5512e12d
## 程式碼

```python
n = list(input())
ans =[]
import numpy as np
a =np.unique(n)
for i in range(len(a)):
    if n.count(a[i]) % 2 !=0:
        ans.append("F")
if len(ans)==0 or len(ans)==1:
    print("True")
else:
    print("False")
```

## 錯誤訊息
Runtime error

## 問題描述
思路-將輸入變成list，先把list中相異的值取出來為a(為節省時間)，再算每一個值在原list(即n)當中的出現次數，如果不是偶數就在ans的lst中增加F
因為回文一定要有偶數次數，或僅可以有一次非偶數，所以0或1個F是可以被接受的，為True，否則則為非
我在自己的編輯器可以成功，但在JUDGE出現程式出錯，還請助教解答QQ

**Comment by Neptune2901** [comment]
judge沒辦法使用numpy套件唷，所以會噴runtime error
