### ISSUE TITLE
[Homework 3] 天數相差

### ISSUE THREAD

**Issue by addie-tyc** [coding-coworking-club/basic-python-2020-fall#249]
## 提交連結
https://judge.ccclub.io/status/3c1b3be419ac4b5c9f299d0e76c2a8c4

## 程式碼

```python
# 天數相差
from datetime import datetime
date_format = "%Y %m %d"
a = datetime.strptime(input(), date_format)
b = datetime.strptime(input(), date_format)
delta = a - b
print(abs(delta.days))
```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/65952631/96746892-3a8cf480-13fa-11eb-8c88-b9e1d681610f.png)

## 問題描述
在 jupyter 上沒問題，不曉得在 judge 上是哪個部分出錯了 QwQ
再麻煩助教們，感謝！

**Comment by Unstopab** [comment]
我原本也跟大大寫的差不多，
後來想到datetime要求的最小年是公元1年，所以如果輸入是給公元前1年1月1日(-1/1/1)，目前的程式會因為年是負數而出錯，後來依此調整一下程式碼就過了~給大大參考。

datetime詳細說明網址：
https://docs.python.org/3/library/datetime.html

**Comment by combokang** [comment]
Hi 大大們，我沒有處理公元前的問題，反而是處理了如果年份長度不足四個數字時報錯的問題，處理後就過了
給有需要的人參考
