### ISSUE TITLE
[Homework 3] S型分班

### ISSUE THREAD

**Issue by addie-tyc** [coding-coworking-club/basic-python-2020-fall#251]
## 提交連結
https://judge.ccclub.io/status/a61fa736698c51e463760daf028dadbc

## 程式碼

```python
# S型分班
number = input().split(" ")
level = input().split(" ")

# 計算出現最多次數的level, 看需要迭代幾次
x = []
for i in set(level):
    count = 0
    for j in level:
        if i == j:
            count += 1
    x.append(count)
n = max(x)

# 把測資弄成清單
lst = []
for i in range(len(number)):
    lst.append([level[i], number[i]])

# 分班
for i in range(n):
    check = []
    s = locals()["s_"+str(i)] # 建立第i次迭代的名單
    s = [lst[0]] 
    for j in range(1, len(lst)):
        if lst[j][0] != lst[j-1][0] and lst[j][0] not in check: # 確保不會一次拿到相同level的學生
            s.append(lst[j])
            check.append(lst[j][0]) # 貼上本次迭代已經抓到的level，來確保不會有相同level的學生
    for k in s:
        lst.remove(k) # 迭代過的就踢出名單
    if i%2==0:
        s = sorted(s) # 小到大
        for m in range(len(s)):
            print(s[m][1], end = " ")
    else:
        s = sorted(s, reverse=True) # 大到小
        for m in range(len(s)):
            print(s[m][1], end = " ")
```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/65952631/96950687-766caa80-151d-11eb-907c-f1ec75ddfa3a.png)

## 問題描述
在 jupyter 上用測資都對，用助教在別的 issue 提供的測資也行，
不曉得哪裡出問題了QAQ
麻煩大家了，感謝！

**Comment by yles840421** [comment]
Hi~我這邊試跑是出現
Traceback (most recent call last):
  File "C:\Users\yles8\Documents\python-ccclub\test.py", line 23, in <module>
    s = locals()["s_"+str(i)] # 建立第i次迭代的名單
KeyError: 's_0'
這樣的錯誤

我其實不懂locals()是什麼哈哈，不過剛剛查了下，網路好像說它只能讀而不能修改的樣子
https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/358838/
給你參考看看

**Comment by addie-tyc** [comment]
@yles840421 恩，你說得對，而且我發現我寫在一起根本也不用每次都存，直接用s就可以了
但還是 runtime error 了QwQ
```python
# S型分班
number = input().split(" ")
level = input().split(" ")

# 計算出現最多次數的level, 看需要迭代幾次
x = []
for i in set(level):
    count = 0
    for j in level:
        if i == j:
            count += 1
    x.append(count)
n = max(x)

# 把測資弄成清單
lst = []
for i in range(len(number)):
    lst.append([level[i], number[i]])

# 分班
for i in range(n):
    check = []
    s = [lst[0]] # 建立第i次迭代的名單
    for j in range(1, len(lst)):
        if lst[j][0] != lst[j-1][0] and lst[j][0] not in check: # 確保不會一次拿到相同level的學生
            s.append(lst[j])
            check.append(lst[j][0]) # 貼上本次迭代已經抓到的level，來確保不會有相同level的學生
    for k in s:
        lst.remove(k) # 迭代過的就踢出名單
    if i%2==0:
        s = sorted(s) # 小到大
        for m in range(len(s)):
            print(s[m][1], end = " ")
    else:
        s = sorted(s, reverse=True) # 大到小
        for m in range(len(s)):
            print(s[m][1], end = " ")
```

**Comment by yles840421** [comment]
Hi~
1. 你迭代幾次那段可以簡化成
n = max([level.count(a) for a in set(level)])

2.你這樣的輸出法最後會多出一個空格，可以先建一個answer變數，把答案用List型式存進去後，最後用" ".join(answer)的方式print

3.*會runtime error的原因:你的check並未包含最一開始的s = [lst[0]]，所以同一個level有可能被重複取，導致最後for i in range(n)迴圈已經沒東西可取runtime error，因此s = [lst[0]]需要加一個check.append(lst[0][0])

改成下面這樣就能AC了
-----------------------------------------------------------------------------
S型分班
number = input().split(" ")
level = input().split(" ")

計算出現最多次數的level, 看需要迭代幾次
n = max([level.count(a) for a in set(level)])

把測資弄成清單
lst = []
for i in range(len(number)):
    lst.append([level[i], number[i]])

分班
ans = []
for i in range(n):
    check = []
    s = [lst[0]] # 建立第i次迭代的名單
    check.append(lst[0][0])
    for j in range(1, len(lst)):
        if lst[j][0] != lst[j-1][0] and lst[j][0] not in check: # 確保不會一次拿到相同level的學生
            s.append(lst[j])
            check.append(lst[j][0]) # 貼上本次迭代已經抓到的level，來確保不會有相同level的學生
    for k in s:
        lst.remove(k) # 迭代過的就踢出名單
    if i%2==0:
        s = sorted(s) # 小到大
        for m in range(len(s)):
            ans.append(s[m][1])
    else:
        s = sorted(s, reverse=True) # 大到小
        for m in range(len(s)):
            ans.append(s[m][1])

print(" ".join(ans))

**Comment by addie-tyc** [comment]
@yles840421 感恩大大
不過我只更正了你提到的 3. 就過了w
