### ISSUE TITLE
[Homework 3] 推薦系統

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#252]
## 提交連結

https://judge.ccclub.io/status/f150b916eb8a547638dd351addeb612a
## 程式碼

```python
threshold = int(input())
customerList = []
itemList = []
n = input()
while n != "end":
    tem = n.split()
    customerList.append([tem[0]])
    itemList.append(tem[1:])
    n = input()


setList = []
answerList = []
for i in range(len(customerList)):
    tem = []
    for j in range(len(customerList)):
        percentage = 0 / len(itemList[i])
        if i != j:
            for a in itemList[j]:
                if a in itemList[i]:
                    percentage += 1 / len(itemList[i])
        if percentage*100 >= threshold :
            for a in itemList[j]:
                if a not in itemList[i]:
                    if a not in tem:
                        tem.append(a)
    answerList.append(tem)

for i in range(len(customerList)):
    customerList[i].extend(answerList[i])

for i in customerList:
    print(" ".join(i))
```

## 錯誤訊息
wrong answer

## 問題描述

您好，我的output跟sample測資確定一模一樣(用a==b確認過)，卡了很久還是沒靈感不知道錯哪裡...可以麻煩跟我說怎麼樣測資過不了嗎?非常感謝!
BTW,想請問「依商品出現的順序依序輸出」這句是如何解讀的，是「全部人商品出現的順序」，還是「符合標準的人商品出現的順序呢」?
比如說:
50
小美 香蕉 蘿蔔 番茄
凱文 電腦 手機 錢包 鑰匙
小明 電腦 手機 錢包 卡片 機車
小華 電腦 手機 番茄
end
這樣的input，是應該出現 1.凱文 番茄 卡片 機車，還是 2.凱文 卡片 機車 番茄的才正確呢?

**Comment by Neptune2901** [comment]
2.對的

**Comment by yles840421** [comment]
> 2.對的

Hi，感謝回復!
不知是否能跟我說是哪個測資過不了嗎?

**Comment by Neptune2901** [comment]
試試看吧
```
90
i C O G Z X H K J U I
t C X O Z G E H
g X E C Z O U I
w J Z O X E
p O I C U Z G J H X E
end
```

**Comment by yles840421** [comment]
我懂了....percentage += 1 / len(itemList[i])的寫法出了問題
我猜是因為二進位的關係，(1/10+1/10+1/10+1/10+1/10+1/10+1/10+1/10+1/10) != 0.9，而是0.8999999999， 看來非二倍數的分數用連續相加會不精準

後來改為percentage = len( set(itemList[j]).intersection(itemList[i]) ) / len(itemList[i]) 就通過了!
感謝提供測資~!有測資反推真的一下子就能完成debug了

**Comment by lazyYC** [comment]
@Neptune2901 
助教想請問一下 我的code有通過測資、也確認不是空格、或是樓上yles大的錯誤
能否請助教幫我看看問題在哪？

```python
threshold = int(input())
d = {}   #d是一個用來放置 {人名: [物品]} 的辭典
while True:
    p = input().split()
    if p == ['end']:
        break
    else:
        d[p[0]] = p[1:]
recommand = {}   #recommand是用來放置每個人名應推薦的商品之辭典
for i in d.keys():
    for j in d.keys():
        if len(set(d[i]) & set(d[j])) / len(set(d[i])) >= threshold / 100:  ###交集比例大於等於閾值的判定
#以下：先用set作差集計算，再轉回有順序且方便加減的list儲存
#若該人名底下沒有value，則賦值；若有則加到後面
            try:
                recommand[i] += list(set(d[j]) - set(d[i]) - set(recommand[i]))
            except:
                recommand[i] = list(set(d[j]) - set(d[i])) 
for i in recommand.keys():
    print(i, end = '')
    if recommand[i] != []:
        print(' ', end = '')
    print(' '.join(recommand[i]))
```

提交連結在此
https://judge.ccclub.io/status/ff0537d4aeda49d4d39e31f4fa27c0c3
結果是wrong answer，想請教助教會是什麼問題呢？

**Comment by Neptune2901** [comment]
上面那組測資從系統看也是WA
妳要再嘗試看看嗎XD

**Comment by lazyYC** [comment]
@Neptune2901 
我今天又試了一下 還是找不到錯誤 OTZ
我有把output設成變數，跟Judge上提供的答案用 == 比對
結果是True耶
能否請助教給點提示XD

**Comment by Neptune2901** [comment]
我用妳的code輸入 Sample output 1就長不一樣囉

**Comment by yles840421** [comment]
> @Neptune2901
> 我今天又試了一下 還是找不到錯誤 OTZ
> 我有把output設成變數，跟Judge上提供的答案用 == 比對
> 結果是True耶
> 能否請助教給點提示XD

Hi~因為你這邊用 for i in d.keys()來跑迴圈，而推薦清單的順序會因為誰先誰後而受影響(如sample 1，若凱文的下一個是小華而非小明，那正確輸出會變成「凱文 番茄 卡片 機車 」)，因為不同系統跑dict出來的順序性不同，所以會出現助教那邊看起來長不一樣，你自己跑看起來一樣的狀況(我剛用自己電腦python IDE跑的就跟visual tool跑的結果不同)

**Comment by lazyYC** [comment]
@yles840421  OMG～長知識了！原來還有這個狀況，難怪助教大大一直跟我說我跟測資output不一樣我卻找不出來XD
不過因為我想不到怎麼用dict的前提下怎麼解決這問題，後來用list重寫一遍就ace了，十分感謝！

**Comment by yles840421** [comment]
哇你也太晚睡
我之前有遇到人也是類似問題
set跟dict沒有順序性，蠻容易遇到這種狀況的哈哈

**Comment by combokang** [comment]
Hi 助教，想建議題目需求可以再寫明確一點，畢竟每個人對文字敘述的理解可能有不同。像是「依商品出現的順序依序輸出」這句我解讀成「全部人商品出現的順序」，於是我多加了一行去處理但一直通過不了，來github參考大家發過的issue才發現我在邏輯的解讀錯了。以上一點小意見，辛苦了
