### ISSUE TITLE
[Homework #000109] 優惠卷

### ISSUE THREAD

**Issue by StarCat0928** [coding-coworking-club/basic-python-2020-fall#255]
## 提交連結

https://judge.ccclub.io/status/558876e8f2d59bfba015c1aadaeb5fd5
## 程式碼

```python
s = " "
lst = []
while(s != ""):
    try:
        s = input()
        temp = s.split()
        for i in range(0, len(temp)):
            lst.append(temp[i])
    except:
        break
print(lst)
money = int(lst[-1])

while(i != len(lst)-1):
    if(lst[i] == "$"):
        money = money - int(lst[i+1])
        i += 1
    else:
        money = money*int(lst[i])/10
    i += 1
          
if(money <= 0):
    money = 0
          
print(str(int(money)))
```

## 錯誤訊息

Wrong Answer
## 問題描述

首先我這題的想法是先處理不定多行輸入，並將每次輸入split並append到一個預定的串列中，輸入結束後串列的最後一項會是原價，將其指定給money變數，之後設定一個while迴圈，若串列的值為「＄」時，則將money減掉「＄」後的值，並將i+1，若值非「＄」，則將money打折，最後若money低於0，則將money設為0，最後將money以整數方式印出。請問上述做法有何錯誤？

**Comment by yles840421** [comment]
Hi~
1. 這題不是用不定行輸入哈哈，題目有說共為六行，用你的寫法會需要多輸入一個空行才能執行程式
2.你多放了一個print(lst)在中間
3.還有記得要無條件捨去,可以from math import floor

**Comment by StarCat0928** [comment]
喔，我知道了，原來有指定6行啊，沒注意聽題目

**Comment by StarCat0928** [comment]
把print(lst)刪掉就正確了，原本那行是要做測試，結果不小心也放進judge裡了
