### ISSUE TITLE
[Homework #] 推薦系統

### ISSUE THREAD

**Issue by Powei-Hsiao** [coding-coworking-club/basic-python-2020-fall#257]
## 提交連結

https://judge.ccclub.io/status/ae66e1b30df48c7dead620010036945b
## 程式碼

```python
threshold = int(input())
lst = []
while True:
    s = input()
    if s != 'end':
        lst.append([str(s) for s in s.split()])
    else:
        break
#print(lst)
onhand_dic = {sub_list[0]:sub_list[1:] for sub_list in lst}
#print(onhand_dic)
similarity_list = []
for value1 in onhand_dic.values():
    m = len(value1)
    temp = []
    for value2 in onhand_dic.values():
        n = len(set(value2)&set(value1))
        temp.append(n/m)
    similarity_list.append(temp)
    
#print(similarity_list)
buyin_dic = {lst[i][0]:[] for i in range(len(lst))}

for i in range(len(lst)):
    for j in range(len(lst)):
        if similarity_list[i][j] >= threshold/100:
            print(i, j)
            temp_list = list(set(onhand_dic[lst[j][0]])-set(onhand_dic[lst[i][0]]))
            print(temp_list)
            temp_list = sorted(temp_list, key=lst[j].index)
            print(temp_list)
            for item in temp_list:
                if item not in buyin_dic[lst[i][0]]:   
                    buyin_dic[lst[i][0]] += [item]
#print(buyin_dic)

for key in buyin_dic.keys():
    print(key, end=' ')
    print(' '.join(buyin_dic[key]))
```

## 錯誤訊息

Wrong Ansuer

## 問題描述

再度看到脫窗...希望能提點一下哪邊的邏輯沒有注意到。
想法如下
1. 建立onhand_dic 其中 key 代表人，value 代表擁有的產品。
2. 建立 simularity_list 其中[ i ] [ j ] 代表 i 和 j 的相似度，例如範例一中，simularity_list[ 0 ][ 1 ] 代表 kevin對小明的相似度。
3. 建立 buyin_dic 準備放每個人要買的東西，其中 value 以 list 存放。

建立完後使用兩個 for-loop go through 每個人對其他人(也包括自己)的 similarity_list，當大於 threshold 時，以 set 差集找出要買的商品，而因 set 並無排序功能，再以 list() 和 sorted() 將欲購買的商品重新排序。接著判斷該商品有無在 buyin_dic內，如無則依序填入。

**Comment by yles840421** [comment]
Hi~!
1.你中間有三個flag忘記刪掉了(print(i, j);print(temp_list);print(temp_list))
2.這次依然是空格的問題哈哈，假如沒推薦商品，你人名後會多一個空格(如:"小美 "，而非"小美")，剛排除這問題後測試就AC了

我自己會設一個self test的簡單程式檢查這個狀況，建議你也可以試看看
```python
mine = """
凱文 卡片 機車 番茄
小明 鑰匙
小美 
小華 錢包 鑰匙 卡片 機車
"""

sample = """
凱文 卡片 機車 番茄
小明 鑰匙
小美
小華 錢包 鑰匙 卡片 機車
"""


print(mine == sample)
```
像用這樣來test output肉眼難以發現的小問題

**Comment by Powei-Hsiao** [comment]
又是空格!!
謝謝你分享測試方法!

**Comment by lazyYC** [comment]
> Hi~!
> 1.你中間有三個flag忘記刪掉了(print(i, j);print(temp_list);print(temp_list))
> 2.這次依然是空格的問題哈哈，假如沒推薦商品，你人名後會多一個空格(如:"小美 "，而非"小美")，剛排除這問題後測試就AC了
> 
> 我自己會設一個self test的簡單程式檢查這個狀況，建議你也可以試看看
> 
> ```python
> mine = """
> 凱文 卡片 機車 番茄
> 小明 鑰匙
> 小美 
> 小華 錢包 鑰匙 卡片 機車
> """
> 
> sample = """
> 凱文 卡片 機車 番茄
> 小明 鑰匙
> 小美
> 小華 錢包 鑰匙 卡片 機車
> """
> 
> 
> print(mine == sample)
> ```
> 
> 像用這樣來test output肉眼難以發現的小問題

同謝！十分感謝 @yles840421推薦的測試方法。
