### ISSUE TITLE
[Homework #203305] S型編班

### ISSUE THREAD

**Issue by StarCat0928** [coding-coworking-club/basic-python-2020-fall#262]
## 提交連結

https://judge.ccclub.io/status/55f5b5bc9b444a4b11b5c7a1c100521d
## 程式碼

```python
s1 = [int(n) for n in input().split()]
s2 = [str(s) for s in input().split()]
s3 = []
num = len(s1)-1
n = 0
d = 1
u = 0
for i in range(0, len(s2)):
    s3.append(s2[i])

for i in range(0, len(s1)-1):
    for j in range(i+1, len(s1)):
        if(ord(s2[i]) > ord(s2[j])):
            temp = s2[i]
            s2[i] = s2[j]
            s2[j] = temp

for i in range(0, len(s1)):
    if(s2[i] == s2[i-1]):
        s2.append(s2[i])

while(True):
    if(s2[n] == s2[n-d]):
        s2[n] = ""
        num-=1
        d += 1
    else:
        d = 1
    n += 1
    if(n >= num):
        break
        
while(True):
    if(s2[u] == ""):
        s2.remove(s2[u])
        u-=1
    u+=1
    if(u == len(s2)-1):
        break

for i in range(0, len(s2)):
    for j in range(0, len(s3)):
        if(s2[i] == s3[j]):
            print(str(s1[j]), end=" ")
            s3[j] = ""
            s1[j] = ""
            break
```

## 錯誤訊息

Wrong Answer
## 問題描述

以下是我的想法，將兩行輸入分別設為s1、s2，並將s2複製一份給s3，用於之後比較用， num、n的設定為之後跑迴圈所使用，接下來第一個迴圈主要是將輸入串列進行排序，第二個迴圈是目的是將相同的英文字母append到後方，而第三個迴圈則是將前方多餘相同的東西換成""，並透過第四個迴圈刪除，最後則是拿完成排序後的s2與原本的s3做比較，一比較到正確答案，便直接以相同索引值輸出s1內容並將s3、s1的索引值以""蓋掉，以免之後重複輸出同樣的，請問以上演算有何錯誤？

**Comment by yles840421** [comment]
Hi, 這邊是我的一些建議~

1.s3可以簡化成 s3 = s2.copy() 即可(而s2可直接寫成input().split()，不用浪費運算量把原本就是str的再跑str處理

2.你第一個for迴圈其實就是為了sorting，可以用 **s2.sort(key = lambda x:  ord(x))** 的方式一行搞定

3.你第四個迴圈是為了消除""，可以用 **s2 = " ".join(s2).split()** 一行搞定

4.**你錯誤的地方在於沒有考慮append到尾巴後的還會有重複&排序的問題(比如遇到ccclubb 1234567就會失敗)，用你的寫法框架我想不到處理的方法...可能得考慮另一條路
