### ISSUE TITLE
[General] 日期計算

### ISSUE THREAD

**Issue by yufang3132** [coding-coworking-club/basic-python-2020-fall#263]
## 提交連結

https://judge.ccclub.io/status/24ba325645c4d2ceb88e251c9141016b

## 程式碼

```python
import datetime

start = input()
days = int(input())

start_time = datetime.datetime.strptime(start,"%Y %m %d")
result = start_time + datetime.timedelta(days)

print(result.strftime("%Y-%m-%d"))
```

## 問題描述

在jupyter notebook上測試有出現相對應的答案，但在judge系統上出現了runtime error，不知道問題出在哪裡QQ
在參考網路上datetime模組的用法，解題想法是先用模組裡的strptime函數，把第一次input的字串轉成日期格式，再用timedelta函數，加上第二行所input的天數，最後印出結果，但因為只要日期，所以用strftime函數轉成以年月日的格式回傳

**Comment by Viggochang** [comment]
%Y 對應的是 四位數 的年份
如果今天要表示的是 100年10月10號
```
start = 100 10 10
start_time = datetime.datetime.strptime(start,"%Y %m %d")
```
此時會出現錯誤

可以思考一下如何避開這樣的問題
或是嘗試使用 strptime 以外的方式取得時間

**Comment by yufang3132** [comment]
謝謝助教～
改用其他方法寫出來了～
