### ISSUE TITLE
[Homework 3] 天數相差

### ISSUE THREAD

**Issue by evetyy** [coding-coworking-club/basic-python-2020-fall#266]
## 提交連結

https://judge.ccclub.io/status/fdba521f748ea3297d7acee55f9ff6f5
https://judge.ccclub.io/status/2698d4feac5ab08a1e1fac9c3ee31cbc
https://judge.ccclub.io/status/b0125908a36645ea6adfac930d934ecc
## 程式碼

```python
import datetime

d1 = datetime.datetime.strptime(input(), '%Y %m %d')
d2 = datetime.datetime.strptime(input(), '%Y %m %d')
delta = d1 - d2
print(abs(delta.days))
```

## 錯誤訊息

Runtime Error
## 問題描述

用Jupyter notebook測試都沒有問題，試過連結裡的三種寫法，定義年份比0小的話就不合條件，但還是出現錯誤訊息，先謝謝助教~~

**Comment by yles840421** [comment]
Hi~我不是助教，但剛好寫過這題，跟你分享下想法
這邊要考慮到「小於1000的年份」，譬如西元100年7月15日的input會是「100 7 15」，就會導致你的程式Runtime error

**Comment by yles840421** [comment]
我當初是用zfill()方式解決的，可以參考看看
