### ISSUE TITLE
[Week 7] 時間戳記

### ISSUE THREAD

**Issue by enn-lu** [coding-coworking-club/basic-python-2020-fall#267]
## 程式碼

```python
a=str(input())
from datetime import datetime
timestamp = a
dt_object = datetime.fromtimestamp(timestamp)
print("dt_object =", dt_object)

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/71515972/97197032-1f4e2a80-17e8-11eb-955f-9ed4bcc835d7.png)
![image](https://user-images.githubusercontent.com/71515972/97197464-a6030780-17e8-11eb-9915-fb8be16e9497.png)

## 問題描述
因為因為要輸入秒的時間，所以先輸入進去，再去切割，但是卻發現是數字不能直接換算，改成文字以後，再帶入進去還是顯示為數字。

**Comment by yles840421** [comment]
Hi,

1.你要把a從字串轉為int型態才能使用fromtimestamp，所以改成 **timestamp = int(a)**

2.這邊題目沒有要求"dt_object ="這點，所以print(dt_object)就好了
