### ISSUE TITLE
[Homework 3]學習歷程

### ISSUE THREAD

**Issue by hazel-ys-lin** [coding-coworking-club/basic-python-2020-fall#270]
## 提交連結
https://judge.ccclub.io/status/1fe2a49477c291219d9fcd065764a01b

## 程式碼

```python
a, b, c, d, interest = input().split(' '), input().split(' '), input().split(' '), input().split(' '), input()
r_list = [a, b, c, d]
a_list1 = []
a_list2 = []

for i in range(len(r_list)):
    if interest == r_list[i][0]:
        for j in range(1, len(r_list[i])):
            for k in range(len(r_list)):
                if r_list[i][j] == r_list[k][0]:
                    for l in range(1, len(r_list[k])):
                        a_list1.append(r_list[k][l])
            a_list2.append(r_list[i][j])

a_list1 = sorted(a_list1)
a_list2 = sorted(a_list2)
ans_list = []

for i in a_list1:
    ans_list.append(i)
for i in a_list2:
    ans_list.append(i)
ans_list.append(interest)

print(' '.join(ans_list))
```

## 問題描述

（一）
將前四行的修課資料都加入成list (a, b, c, d)
建立包含所有課程資料的的list ( r_list )
由於題中說輸入的課程資料的一行當中，除了課程名字的第一個值之外都為同個位階，因此推測課程的先修前後只有兩個位階，建立a_list1和a_list2

（二）
用迴圈先找到課程資料list( r_list )內哪個是學生輸入的課程
從找到的課程的第[1]位置檢視同個位階的課程有沒有先修課程
將先修課程加入a_list1
將課程名稱後的課程加入a_list2

（三）
分別排序a_list1和a_list2
分別append進入ans_list
在ans_list最後加上學生感興趣的課程名稱
用join輸出中間有單格空白之列表

Wrong Answer
範例的測資都有過，想知道還有哪些測資可能產生錯誤或是沒想到的地方><

**Comment by andysleep** [comment]
一開始假設兩個位階就錯囉
試試
a b c
b e
e f
f g
a
