### ISSUE TITLE
[Homework 3] 字串回文

### ISSUE THREAD

**Issue by shenginsound** [coding-coworking-club/basic-python-2020-fall#271]
## 提交連結

https://judge.ccclub.io/status/68af6627a4bf6a21ccb16ffd0aa4965c
## 程式碼

```python
word = input()
word_list = []
countlst = []
for element in word :
    word_list.append(element) #把字母變成一個一個元素放進串列
for i in word_list :
    a = word_list.count(i) #每個字母出現幾次
    countlst.append(a) #把字母出現的次數放進另一個串列裡
if len(word_list) % 2 == 0 : ＃如果串列裡有偶數個，只要有一個或多個字母，只出現奇數次的話，就不能回文 eg:aaabbb,aabc
     if 1 in countlst : #先排除出現一次的時候，如果統一寫成只出現奇數次（如下面elif 的寫法)，會抓不出aabc類型的False
        print("False")
     elif 1 not in countlst : #再排除出現奇數次的情況
         for j in countlst :
            if j % 2 == 1 :
                print("False")
                break
            else :
                print("True")
                break
else :                      #如果串列裡有奇數個，字母單獨出現一次的只能有一個或0個，才能回文
    if countlst.count(1) > 1 :  #單獨出現一次的字母超過一個，不能回文
        print("False")
    else :
        print("True")
```

## 錯誤訊息

Wrong answer
## 問題描述

想法：
1.先將字串分成字母總數為偶數還是奇數
2.如果是偶數，如果有字母出現一次或是奇數次的話不能回文
3.如果是奇數，回文只能夠接受一個字母單獨出現一次
jupyter notebook上可以跑出答案，judge上則wrong answer，也會超過時間
覺得可能是自己對回文的定義不是很理解，所以寫錯了，望請助教或是經過的同學們指點迷津ＱＱＱ
感謝助教與大家

**Comment by yles840421** [comment]
Hi,我是經過的同學哈哈
你的解題概念是正確的，這題其實很單純只是看「字母出現奇數次」的次數不能大於一
下面是一些建議
1.#把字母變成一個一個元素放進串列→ word_list.extend(word)的寫法就可以完成

2.#每個字母出現幾次→單純要數量計算，那原本的str型態就可以做到了(count函式在list跟str都可以用)

3.if len(word_list) % 2 == 0 → 你在這行後的邏輯就歪掉了，重點是「字母出現奇數次」不可大於1，像你的程式會把「aaabbbccc」判斷為True，因為沒考慮過出現3,5,7等其他奇數次的情況

**建議可以設變數oddtimes直接紀錄奇數出現次數，oddtimes > 1就是False，反之為True**

**Comment by shenginsound** [comment]
喔喔喔 感謝你 我來思考跟試試看 謝謝你！！

**Comment by shenginsound** [comment]
> Hi,我是經過的同學哈哈
> 你的解題概念是正確的，這題其實很單純只是看「字母出現奇數次」的次數不能大於一
> 下面是一些建議
> 1.#把字母變成一個一個元素放進串列→ word_list.extend(word)的寫法就可以完成
> 
> 2.#每個字母出現幾次→單純要數量計算，那原本的str型態就可以做到了(count函式在list跟str都可以用)
> 
> 3.if len(word_list) % 2 == 0 → 你在這行後的邏輯就歪掉了，重點是「字母出現奇數次」不可大於1，像你的程式會把「aaabbbccc」判斷為True，因為沒考慮過出現3,5,7等其他奇數次的情況
> 
> **建議可以設變數oddtimes直接紀錄奇數出現次數，oddtimes > 1就是False，反之為True**

謝謝你 我後來用了另一種方式寫 然後參考你寶貴的建議 有解出來（落淚）感謝你ＱＱＱＱＱ
