### ISSUE TITLE
[Homework 3] 字串回文

### ISSUE THREAD

**Issue by dovewalk** [coding-coworking-club/basic-python-2020-fall#275]
## 提交連結

https://judge.ccclub.io/status/4c8c1158512747c6bb2b3074da5897ed
## 程式碼

```python
n = [str(i) for i in input()]
a=0
b=1
for i in n:  
    if n.count(i)%2 !=0 and b!=i:
        b=i
        a+=1
if a==0 or a>=2:
    print(False)
else:
    print(True)
```

## 錯誤訊息

![123](https://user-images.githubusercontent.com/71716725/97843604-8d34ad80-1d24-11eb-9d98-81b145faab11.jpg)

## 問題描述

但我依據Sample 帶入後，出來顯示的答案都是正確的

**Comment by Kevinweisl** [comment]
請修正提交連結，細節請參考 [github 發文須知](https://www.notion.so/ccclub/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)
