### ISSUE TITLE
[Week 2] 停車費

### ISSUE THREAD

**Issue by hazel-ys-lin** [coding-coworking-club/basic-python-2020-fall#28]
## 提交連結

https://judge.ccclub.io/status/4bb357b021edd7c6458f879f6c4c3388

## 程式碼

```python
d1, d2, d3 = input(), input(), input()
enter_hour= int(d1[:d1.index(':')])
enter_minute=int(d1[-2:])
leave_hour=int(d2[:d2.index(':')])
leave_minute=int(d2[-2:])
time= ((60*leave_hour)+leave_minute)-((60*enter_hour)+enter_minute)
if time%30 !=0:
    total_hour=int(time/30)+1
elif 0<time<30:
    total_hour=1
else:
    total_hour=time/30
fee=20*total_hour
if d3=='Y':
    fee /=2
print(int(fee))

```

## 問題描述

在Visual Studio Code上跑沒有問題，但在Judger上顯示為Wrong Answer

**Comment by jeffery12697** [comment]
請參考[學員須知](https://www.notion.so/ccClub-2020-Fall-ed14cfc6c5ed46ceadf294f419cb80c3)依規定附上提交連結

**Comment by hazel-ys-lin** [comment]
您好，已經更新了喔

**Comment by jeffery12697** [comment]
`fee/=2` 除法會變成浮點數，題目輸出要整數
然後你沒考慮到小於30分的情況
以後運算子前後可以加空格會比較好看，像這樣 `fee /= 2`

**Comment by hazel-ys-lin** [comment]
您好，不好意思剛剛新增了小於30分的情況並修改fee浮點數部分，但結果還是Wrong Answer
提交連結和程式碼更新在貼文了><謝謝！

**Comment by jeffery12697** [comment]
題目說小於30分不用錢
