### ISSUE TITLE
[General] 安裝 pip 問題

### ISSUE THREAD

**Issue by elaine0620** [coding-coworking-club/basic-python-2020-fall#286]
## 程式碼

```python

```

## 問題描述

pip3 installed, 在command中也顯示requirement already satisfied
但當我打開Python空白文件要執行
"import requests
from bs4 import BeautifulSoup"的時候，出現這個錯誤…😂
![124614850_414874489533174_2562290782951933662_n](https://user-images.githubusercontent.com/71715242/99149187-6c2a7000-26c7-11eb-9707-ae40aed59743.png)
想問一下是為什麼呢，該如何修正？>

**Comment by tziyingchen** [comment]
我也有遇到一樣的問題QAQ
