### ISSUE TITLE
[Homework 3] 字串回文

### ISSUE THREAD

**Issue by venividivici1997** [coding-coworking-club/basic-python-2020-fall#290]
## 提交連結
https://judge.ccclub.io/status/9414f7282954d87abb031ca4357350f0

## 程式碼

```python

word = input()

oddtimes=0

for i in word:

    a = word.count(i)

    if a%2==1:

        oddtimes+=1

    if oddtimes>1:

        break

if oddtimes<=1:

    print("True")

else:

    print("False")

```

## 錯誤訊息
Time Limit Exceeded

## 問題描述
我對這題的想法是如果字串字符出現奇數次超過一次就是False，其他情形則是True。嘗試過幾次讓程式碼更簡單的方式，但還是出現Time Limit Exceeded。

**Comment by yufang3132** [comment]
雖然跟你的寫法不同，但之前也一直遇到Time Limit Exceeded的問題，後來參考其他同學的發文，讓已經數過的字不用再數之後，Time Limit Exceeded就不會再出現了
