### ISSUE TITLE
[Homework 4] 信箱名建議

### ISSUE THREAD

**Issue by venividivici1997** [coding-coworking-club/basic-python-2020-fall#295]
## 提交連結

https://judge.ccclub.io/status/c7613a0aded3b37b4016eb4b78b047f6

## 程式碼

```python

email=input()

list1 = list(email)

for i in list1:
    
    if i=="-":

        list1.remove(i)
    
    if i=="+":

        list1.remove(i)


new_email_dot = "".join(list1)

list2=list(new_email_dot)

for j in list2:

    if j==".":

        if list2.index(".")< list2.index("@"):

            list2.remove(j)

new_email = "".join(list2)

print(new_email)

```
Wrong Answer

## 問題描述

我的想法是先把輸入的信箱拆成一個個串列中的元素，先刪除加號和減號；接著再重新變成一個字串、然後再變成串列，這時候判斷如果在＠之前的dot要刪除，而@之後的dot保留。測資也有通過，但不知道為何顯示wrong answer。

**Comment by venividivici1997** [comment]
剛剛也檢查了如果輸入最後包含一個空白，而輸出最後也要有一個空白，並對此做出修正，但仍然是wrong answer QQ

**Comment by yles840421** [comment]
Hi~
你這個方法因為Remove造成list的index變動(如:原本index 3的被刪掉，原本index 4會遞補向前)，會有疏漏的情況(如原本的index 4變index 3，但for迴圈已經從index 4繼續下去了

這個測資就可以看出你程式的問題: kevin-81.02......14+ccclub@ccclub.io
tip: 建議可以改用replace

**Comment by venividivici1997** [comment]
好的，謝謝！
