### ISSUE TITLE
[General] Jupyter安裝失敗

### ISSUE THREAD

**Issue by jimmyhsutw** [coding-coworking-club/basic-python-2020-fall#3]
## 程式碼

```python

```

## 錯誤訊息
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/m4/cg7ff2sn1ms0z3nfntq7w2gm0000gn/T/tmp9yzck9t6
       cwd: /private/var/folders/m4/cg7ff2sn1ms0z3nfntq7w2gm0000gn/T/pip-install-o2eghp5e/argon2-cffi
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/__init__.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/low_level.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_ffi_build.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_password_hasher.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/exceptions.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_legacy.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/__main__.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_utils.py -> build/lib.macosx-10.6-intel-3.6/argon2
  running build_clib
  building 'argon2' library
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/extras
  creating build/temp.macosx-10.6-intel-3.6/extras/libargon2
  creating build/temp.macosx-10.6-intel-3.6/extras/libargon2/src
  creating build/temp.macosx-10.6-intel-3.6/extras/libargon2/src/blake2
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -msse2 -Iextras/libargon2/src/../include -Iextras/libargon2/src/blake2 -c extras/libargon2/src/argon2.c -o build/temp.macosx-10.6-intel-3.6/extras/libargon2/src/argon2.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command '/usr/bin/clang' failed with exit status 1

  ERROR: Failed building wheel for argon2-cffi
Failed to build argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly!

## 問題描述
安裝Jupyter發生問題，還不會上傳截圖，所以直接放在下面！

-- 請盡量完整地敘述你的問題。 -->

**Comment by jeffery12697** [comment]
`pip install --upgrade pip setuptools wheel`
終端機打這串再試試

**Comment by alexypdu** [comment]
@jimmyhsutw  請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29) 將內文格式修正唷！

**Comment by jimmyhsutw** [comment]
> `pip install --upgrade pip setuptools wheel`
> 終端機打這串再試試

抱歉還是出現一樣的提醒
Building wheel for argon2-cffi (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/m4/cg7ff2sn1ms0z3nfntq7w2gm0000gn/T/tmpkiemtjgi
       cwd: /private/var/folders/m4/cg7ff2sn1ms0z3nfntq7w2gm0000gn/T/pip-install-_uu8yykg/argon2-cffi
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/__init__.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/low_level.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_ffi_build.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_password_hasher.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/exceptions.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_legacy.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/__main__.py -> build/lib.macosx-10.6-intel-3.6/argon2
  copying src/argon2/_utils.py -> build/lib.macosx-10.6-intel-3.6/argon2
  running build_clib
  building 'argon2' library
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/extras
  creating build/temp.macosx-10.6-intel-3.6/extras/libargon2
  creating build/temp.macosx-10.6-intel-3.6/extras/libargon2/src
  creating build/temp.macosx-10.6-intel-3.6/extras/libargon2/src/blake2
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -msse2 -Iextras/libargon2/src/../include -Iextras/libargon2/src/blake2 -c extras/libargon2/src/argon2.c -o build/temp.macosx-10.6-intel-3.6/extras/libargon2/src/argon2.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command '/usr/bin/clang' failed with exit status 1
  ERROR: Failed building wheel for argon2-cffi
Failed to build argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly

**Comment by jowu0827** [comment]
我一樣遇到jupyter安裝失敗，錯誤訊息截圖如下
![jupyter安裝失敗](https://user-images.githubusercontent.com/71591643/93710235-98b68580-fb77-11ea-99da-5b0ffc95369f.PNG)

**Comment by jeffery12697** [comment]
`xcode-select --install`
打這個試試
