### ISSUE TITLE
[Week 2] 小明審報名表 2

### ISSUE THREAD

**Issue by elaine0620** [coding-coworking-club/basic-python-2020-fall#30]
## 提交連結

https://judge.ccclub.io/contest/3/problem/202104

## 程式碼

```python

a=input()
b=input()
c=input()
d=input()
e=input()
f=input()
g=input()
h=input()
  
if a=='小華'or d=='':
        z=1
else:
        z=5 
    if '會計' in c:
        z+=1
    if len(e)>200 or len(e)<50:
        z-=1
    if len(f)>100:
        z+= 1
    hour=int(g[0:g.find('小時')])
    if hour< 5:
        z-=1
    elif hour>=10 and <=16:
        z+=1
    elif hour>=17:
        z+=3
    if len(h)>30:
        z+=1
if z>=10:
       z=10
print(z)

```

## 錯誤訊息

compile error

## 問題描述

用jupyter: 跑得出來; but compile error after submission...

**Comment by jeffery12697** [comment]
請參考[學員須知](https://www.notion.so/ccClub-2020-Fall-ed14cfc6c5ed46ceadf294f419cb80c3)依規定格式貼程式

**Comment by elaine0620** [comment]
我貼上時有注意縮排 但不知道為何貼上去之後都跑掉... @@
tried to edit but the same...:(

剛剛已經附上word檔案 可以麻煩助教打開word檔review程式碼嗎? 謝謝!

**Comment by alexypdu** [comment]
程式碼要貼在 

\`\`\`python
\`\`\`

裡面

**Comment by elaine0620** [comment]
Finally got it...:p Please see the updated version!! thanks!

**Comment by tcwang76** [comment]
不確定你是不是貼code的時候格式跑掉了...
"z=1" 和 "z=5" 的縮排都多內縮了一階，
另外 "elif hour>=10 and <=16:" 這裡的 and 是連結兩個判斷式，
所以要寫成 "elif hour >= 10 and hour <= 16:" 才完整唷
