### ISSUE TITLE
[Homework 4] 台灣大公園

### ISSUE THREAD

**Issue by sandy273040** [coding-coworking-club/basic-python-2020-fall#300]
## 提交連結

https://judge.ccclub.io/status/4c9a6a5a9bc77597af97a290f131b617

## 程式碼

```python
a=[]
a1_num=[]
a_eng=[]
dict_a={}
rec_list=[]
rec_num=[]
dict_rec={}
result=[]
a=(" ".join(a)).split() #輸入變成一個元素為單位的串列
for i in range(len(a)): #區域及其所在人數各自一個串列 #回圈下面合併成字典
    a_num=int(a[0])
    if i!=0 and i%2==0 and i <= a_num*2:
        a1_num.append(a[i])
    elif i%2!=0 and i < a_num*2:
        a_eng.append(a[i])
    elif i!=0 and i > a_num*2 and 65 <=ord(a[i])<=122: ＃遊客慾望清單
        rec_list.append(a[i])

for x in range(len(a_eng)):
    dict_a.update({a_eng[x]:a1_num[x]}) ＃區域名稱與人數合併成字典
for y in range(len(rec_list)):
    if rec_list[y] in dict_a.keys():
        rec_num.append(dict_a[rec_list[y]]) ＃把遊客慾望清單區域與所在人數比對
for z in range(len(rec_list)):
    dict_rec.update({rec_num[z]:rec_list[z]})

b=int(a[-1])  ＃最後一個數字
dict_rec=[(k,dict_rec[k]) for k in sorted(dict_rec.keys())] ＃排序字典key（人數）
result=[t[1] for t in dict_rec] #把對應英文字母丟到result串列中
print((" ".join(result[0:b] ))) #print出符合要求數量的字母

```

## 錯誤訊息

wrong answer
## 問題描述

測資丟進去是對的，想請問還有什麼地方是沒有考慮到的嗎？

**Comment by yles840421** [comment]
Hi,
你貼的這個程式我跑不出output耶?
這個寫法應該不可能跳出最前方的while迴圈吧
畢竟任何輸入都會被append而不會造成break

另外這題的寫法不適用不定行輸入喔，是根據input值的固定行數模式

**Comment by sandy273040** [comment]
Hi 助教
我有把不定行輸入拿掉了然後把a改成a=input().split()
但還是顯示wrong answer

另外想問助教要怎麼判斷什麼時候要用不定行輸入，因為我常常不知道什麼時候要用定行或不定行QQ

**Comment by sandy273040** [comment]
有把不定行輸入跟輸出部分修改了，測資丟進去也是對的，但還是跑出wrong answer QQ

**Comment by yles840421** [comment]
哈哈我不是助教啦，路過的學員而已
那你可以貼修改過的程式碼給我嗎？我等等回家再看看

**Comment by sandy273040** [comment]
喔喔原來>< 我看好久還是不知道問題在哪裡QQ

a=[]
a1_num=[]
a_eng=[]
dict_a={}
rec_list=[]
rec_num=[]
dict_rec={}
result=[]
a=(" ".join(a)).split() #輸入變成一個元素為單位的串列
for i in range(len(a)): #區域及其所在人數各自一個串列 #回圈下面合併成字典
    a_num=int(a[0])
    if i!=0 and i%2==0 and i <= a_num*2:
        a1_num.append(a[i])
    elif i%2!=0 and i < a_num*2:
        a_eng.append(a[i])
    elif i!=0 and i > a_num*2 and 65 <=ord(a[i])<=122: ＃遊客慾望清單
        rec_list.append(a[i])

for x in range(len(a_eng)):
    dict_a.update({a_eng[x]:a1_num[x]}) ＃區域名稱與人數合併成字典
for y in range(len(rec_list)):
    if rec_list[y] in dict_a.keys():
        rec_num.append(dict_a[rec_list[y]]) ＃把遊客慾望清單區域與所在人數比對
for z in range(len(rec_list)):
    dict_rec.update({rec_num[z]:rec_list[z]})

b=int(a[-1])  ＃最後一個數字
dict_rec=[(k,dict_rec[k]) for k in sorted(dict_rec.keys())] ＃排序字典key（人數）
result=[t[1] for t in dict_rec] #把對應英文字母丟到result串列中
print((" ".join(result[0:b] ))) #print出符合要求數量的字母

**Comment by sandy273040** [comment]
```python
a=[]
a1_num=[]
a_eng=[]
dict_a={}
rec_list=[]
rec_num=[]
dict_rec={}
result=[]
a=(" ".join(a)).split() #輸入變成一個元素為單位的串列
for i in range(len(a)): #區域及其所在人數各自一個串列 #回圈下面合併成字典
    a_num=int(a[0])
    if i!=0 and i%2==0 and i <= a_num*2:
        a1_num.append(a[i])
    elif i%2!=0 and i < a_num*2:
        a_eng.append(a[i])
    elif i!=0 and i > a_num*2 and 65 <=ord(a[i])<=122: ＃遊客慾望清單
        rec_list.append(a[i])

for x in range(len(a_eng)):
    dict_a.update({a_eng[x]:a1_num[x]}) ＃區域名稱與人數合併成字典
for y in range(len(rec_list)):
    if rec_list[y] in dict_a.keys():
        rec_num.append(dict_a[rec_list[y]]) ＃把遊客慾望清單區域與所在人數比對
for z in range(len(rec_list)):
    dict_rec.update({rec_num[z]:rec_list[z]})

b=int(a[-1])  ＃最後一個數字
dict_rec=[(k,dict_rec[k]) for k in sorted(dict_rec.keys())] ＃排序字典key（人數）
result=[t[1] for t in dict_rec] #把對應英文字母丟到result串列中
print((" ".join(result[0:b] ))) #print出符合要求數量的字母

```

**Comment by yles840421** [comment]
Hi,
妳這個程式看起來真的有點奇怪...我猜你是不是搞錯題意了
1. 妳更新版的程式沒有input()的地方
2. 看起來妳的作法是想把全部input輸入成list之後依index值分類，但總行數是根據第一行input的內容，用這作法邏輯很奇怪的感覺
3. 妳程式裡面好幾個" ＃ "都不是 註解字元"#"，python無法識別為註解，得刪掉才能跑程式
4. 你最後用字典取key會有排序性問題，可以看看我在(#294)的回答

我建議你可以看看其他人的提問(#296)釐清下題意，真的看不懂也可以直接私訊問我(FB:林雨樵)
