### ISSUE TITLE
[General] failed to import pre-trained model to gensim (plz help us plz)

### ISSUE THREAD

**Issue by lazyYC** [coding-coworking-club/basic-python-2020-fall#306]
**前情提要：目前需要一個能比對文義相似度的model**
**例如能把一段文字拆解成詞，之後各自跟我想要的情緒詞會(e.g. 難過)作相似度檢定，最後平均整段分數**

**# downloaded pre-trained corpus "cc.zh.300.bin.gz" from https://fasttext.cc/docs/en/crawl-vectors.html
#已經把cc.zh.300.bin.gz放置在預設path下**

```
from gensim.models import Word2Vec
model = Word2Vec.load_word2vec_format('cc.zh.300.bin', binary=True, norm_only=True)
```

**error msg**

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-afcdaad52eab> in <module>
----> 1 model = Word2Vec.load_word2vec_format('cc.zh.300.bin', binary=True, norm_only=True)
TypeError: load_word2vec_format() got an unexpected keyword argument 'norm_only'

--------------------------------------------------------------------------

<br><br><br><br>

**#remove argument 'norm_only'**

```
from gensim.models import Word2Vec
model = Word2Vec.load_word2vec_format('cc.zh.300.bin', binary=True)
```

**error msg**
---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
<ipython-input-3-6530cbdf3edc> in <module>
----> 1 model = Word2Vec.load_word2vec_format('cc.zh.300.bin', binary=True)

c:\users\yuchi\appdata\local\programs\python\python39\lib\site-packages\gensim\models\word2vec.py in load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype)
   1109             limit=None, datatype=REAL):
   1110         """Deprecated. Use :meth:`gensim.models.KeyedVectors.load_word2vec_format` instead."""
-> 1111         raise DeprecationWarning("Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.")
   1112 
   1113     def save_word2vec_format(self, fname, fvocab=None, binary=False):

DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.

<br>

**使用.bin.gz(也就是未解壓縮的檔案)，error msg一樣**

<br><br><br><br>

**#改用建議的gensim.models.KeyedVectors.load_word2vec_format**
```
import gensim
model = gensim.models.KeyedVectors.load_word2vec_format('cc.zh.300.bin', binary=True)
```

**error msg**
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-40e847d99660> in <module>
      1 import gensim
----> 2 model = gensim.models.KeyedVectors.load_word2vec_format('cc.zh.300.bin', binary=True)

c:\users\yuchi\appdata\local\programs\python\python39\lib\site-packages\gensim\models\keyedvectors.py in load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype)
   1545         """
   1546         # from gensim.models.word2vec import load_word2vec_format
-> 1547         return _load_word2vec_format(
   1548             cls, fname, fvocab=fvocab, binary=binary, encoding=encoding, unicode_errors=unicode_errors,
   1549             limit=limit, datatype=datatype)

c:\users\yuchi\appdata\local\programs\python\python39\lib\site-packages\gensim\models\utils_any2vec.py in _load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype, binary_chunk_size)
    274     logger.info("loading projection weights from %s", fname)
    275     with utils.open(fname, 'rb') as fin:
--> 276         header = utils.to_unicode(fin.readline(), encoding=encoding)
    277         vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
    278         if limit:

c:\users\yuchi\appdata\local\programs\python\python39\lib\site-packages\gensim\utils.py in any2unicode(text, encoding, errors)
    366     if isinstance(text, unicode):
    367         return text
--> 368     return unicode(text, encoding, errors=errors)
    369 
    370 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

<br>

**#感覺說不定是能解決的小問題？**

**Comment by lazyYC** [comment]
救命RRRRRR

**Comment by hyusterr** [comment]
你下載的模型來自於 fasttext，而 fasttext 也可以按你說的拿到詞向量，要不要考慮用用看 fasttext

**Comment by lazyYC** [comment]
@hyusterr 
大感謝！ 我昨天也有用fasttext，可是不知道為啥昨天不行今天就可以了XD
不過實現之後發現我這個做法
**把一段文字拆解成詞，之後各自跟我想要的情緒詞會(e.g. 難過)作相似度檢定，最後平均整段分數**
區辨力好像不是很好

**Comment by hyusterr** [comment]
嗯嗯，不會很好是可以想像的，因為跟一個句子裡面有太多詞了，而一句話裡面或許只要有一個形容詞就足以讓你知道他很難過，例如：
"我昨天出門吃飯，但是台北一直下雨讓我非常的難過，好想去看一場電影紓壓，卻連這個時間都沒有。"
這裡面跟難過有關的詞其實只有一個，但整句話看起來超難過的，然而其他的詞把難過稀釋掉了。
也許你可以試試看用 ckip tagger [https://github.com/ckiplab/ckiptagger](url)，為每個你斷過的詞標上詞性(POS tag)，然後只針對形容詞之類的計算看看效果好不好。
如果表現仍然不滿意，我們可以再想想看可能可以怎麼更好。

**Comment by lazyYC** [comment]
@hyusterr 
謝謝建議，我想到另個方法是用sentiment analyses把情緒強度高的字挑出來
我兩個都試試看 看哪個效果比較好！
