### ISSUE TITLE
[General]  7-2：加減長方形

### ISSUE THREAD

**Issue by Poyu781** [coding-coworking-club/basic-python-2020-fall#32]
## 提交連結
https://judge.ccclub.io/status/69228b88adde1eb7e8da99d2bac74568

## 程式碼

```python
l = int(input())
w = int(input())
row = ""
for a in range(1,w+1):
	if a  % 2 != 0 :
		for i in range(1,l+1) :
			if i % 2 != 0 :
				row += "+"
			else : 
				row += "-"	
		print(row)
		row = ""
	else : 
		for i in range(1,l+1) :
			if i % 2 != 0 :
				row += "-"
			else :
				row += "+"
		print(row)
		row = ""
```

## 錯誤訊息
顯示為 Wrong Answer

## 問題描述
不知是否理解錯誤，在問題範本中，此 input 出來的結果是如此，
<img width="931" alt="截圖 2020-09-22 下午11 53 05" src="https://user-images.githubusercontent.com/66525909/93913160-41f7aa00-fd37-11ea-8d45-a407ea337ac8.png">
但我自己的理解，此 input 出來的結果應該是長這樣
<img width="55" alt="截圖 2020-09-22 下午11 53 45" src="https://user-images.githubusercontent.com/66525909/93913866-4375a200-fd38-11ea-8053-a7cbec410e3c.png">

我不確定這些跟我的程式碼顯示為錯誤答案是否有關係。

基本上我測試了幾組 input，出來的解果都是正負相交的長方形，想知道問題出在哪裡，謝謝！
程式碼測試連結：https://reurl.cc/Oqvl93

**Comment by jeffery12697** [comment]
他是一列印完跳下一列，然後正負相交，所以假設第一列尾是正，第二列頭就是負
