### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by lazyYC** [coding-coworking-club/basic-python-2020-fall#33]
## 提交連結

https://judge.ccclub.io/status/c0ef50b58bfd07ac5b36872f9f98c122

## 程式碼

```python
n1,n2,suit,bat = int(input()),int(input()),int(input()),int(input())
y = (bat-n1*suit) / (n2-n1)
x = suit -y
(x and y) %1 ==0 and (x and y) > 0
```

## 問題描述

在我的Jupyter上填入sample input之後，結果跟sample output的一樣，但是在judge上卻顯示wrong answer。
找很久不曉得是哪邊漏掉了，謝謝回覆！

**Comment by Poyu781** [comment]
Hello  我不是助教，但我剛好看到你的問題，有發現幾個問題，你可以試著更正看看
1. 你可以試看看  print (x and y) ，你會發現他只是顯示 y 的值，由此可以知道，假如你的 x 是 3.5 y 是 8 的時候，這個 (x and y) %1 ==0 還是會顯示 True ，這跟題目的需求就不同了。
2. 你沒有將最後一行程式寫成判斷式，來評斷最後 output 要產出 "True" 還是 “False" ，題目不是要你的 x y 值。
3.  我無法參透你 y 的由來，可以分享一下嗎，覺得這算法很特別 ！

**Comment by lazyYC** [comment]
> Hello 我不是助教，但我剛好看到你的問題，有發現幾個問題，你可以試著更正看看
> 
> 1. 你可以試看看  print (x and y) ，你會發現他只是顯示 y 的值，由此可以知道，假如你的 x 是 3.5 y 是 8 的時候，這個 (x and y) %1 ==0 還是會顯示 True ，這跟題目的需求就不同了。
> 2. 你沒有將最後一行程式寫成判斷式，來評斷最後 output 要產出 "True" 還是 “False" ，題目不是要你的 x y 值。
> 3. 我無法參透你 y 的由來，可以分享一下嗎，覺得這算法很特別 ！

Hello Poyu，

1. 感謝你的提醒，我把條件判斷改成這樣就正常了：
```python
x %1==0 and y %1 ==0 and x >0 and y > 0
```

2. 這個我還是不太明白，因為不用print()還是會看到程式回覆Boolean Value
不過的確要用print()，Judge系統才讓我過

3. 我的解法是把數字填進去會變成兩個式子：

```python
suit = x + y 
bat = n1x + n2y
```
 
把第一個式子乘以n1就可以先解出y
 
不過後來發現我少了一個條件：當n1 = n2會變成無解或無限多解
所以加上了try語句來處理ZeroDivisionError的問題
最後送出就成功了

以下是我通過的code:

##
##
##防雷
##
##
##
##
##

```python
n1,n2,suit,bat = int(input()),int(input()),int(input()),int(input())
try:
    y = (bat-n1*suit) / (n2-n1)
    x = suit -y
except ZeroDivisionError:
    print('False')
    
else:
    print(x %1==0 and y %1 ==0 and x >0 and y > 0)
```
