### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by TzuYuChen1** [coding-coworking-club/basic-python-2020-fall#37]
## 程式碼

```python
sentinal = 'end'
n = []
for i in iter(input, sentinal):
    n.append(i)
int(n.replace(',', ''))
```

## 錯誤訊息

<img width="734" alt="螢幕快照 2020-09-24 上午12 21 59" src="https://user-images.githubusercontent.com/71683601/94040823-fd821200-fdfb-11ea-8b87-7b95c6b02ebc.png">

## 問題描述

不好意思，在寫這項作業時僅能完成到輸入n+1行，到end停止的條件，再往後將會計數字轉換成數字的過程，只找到將字串的會計數字轉為數字的方式，但此方式無法在list中進行，目前實在沒有頭緒。
不知道能否有方向引導？不好意思，謝謝。

**Comment by Neptune2901** [comment]
要針對list內的元素操作可以用
```Python
for ele in n:
    ele.replace(',', '')
```

**Comment by TzuYuChen1** [comment]
謝謝，我後來嘗試使用while迴圈後可以解題了～
