### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by ZoeTsao** [coding-coworking-club/basic-python-2020-fall#38]
## 提交連結

https://judge.ccclub.io/status/f326db81395ddf70e069b714476647b3
## 程式碼

```s1=input()
a=int(s1.replace(",",""))
s2=input()
b=int(s2.replace(",",""))
s3=input()
c=s3.replace(",","")
s4=input()

if "end" in s3:
    print(format(a+b,","))

elif "end" in s4:
    print(format(a+b+int(c),","))

```

## 問題描述

請問助教上面的邏輯是否正確，用jupyter帶入題目算出來的結果跟所需output是一樣的，謝謝助教～～

**Comment by Neptune2901** [comment]
題目要求：
輸入為 n + 1 行。
前 n 行是需要相加的數字，可能為純數字或會計數字。
最後一行是字串 end，代表輸入結束。

可以考慮用while處理輸入項目
