### ISSUE TITLE
[General] 停車位順位

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#40]
## 提交連結

https://judge.ccclub.io/status/4172799d3774d2c0a5fe9e31624467e6
https://judge.ccclub.io/problem/181204
## 程式碼

```python

```

## 問題描述

[範本出錯]
input1第二行應為「abc B 9 74」
input2第四行應為「m416t50y5z C 5 176」
您好，發現原input皆少一個空白導致輸入錯誤，我自行填回空白後程式已通過系統測試

**Comment by alexypdu** [comment]
已更正，感謝回報！
