### ISSUE TITLE
[General] 記帳本 II

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#41]
## 程式碼
https://judge.ccclub.io/status/4e4dcadb603aa9e6c95dd3b79c4056e0
https://judge.ccclub.io/problem/181202

```python

```

## 問題描述

您好，方才發現這邊也有兩個地方少了空白
題目說明部分的:「若輸入為 "e204 200"...」→「若輸入為 "e 204 200"...」
Sample input的"「q1」→「q 1」

**Comment by alexypdu** [comment]
已更正，感謝回報！
