### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by ambre915** [coding-coworking-club/basic-python-2020-fall#42]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203101

## 程式碼

```python
n = int(input())
for i in range(1, n+1):
    print('{:^10}'.format((i*2-1)*"*"))
for i in range(n-1, 0, -1):
    print('{:^10}'.format((i*2-1)*"*"))
```

## 問題描述

助教們好，這題我想到的解法是這樣。
規則應該都是沒有錯的，但作業系統沒有過。
還請助教們幫忙看看，謝謝。

**Comment by Neptune2901** [comment]
試試看n > 5的情況
以及似乎比範例多輸出了*右邊的空格們

**Comment by ambre915** [comment]
> 試試看n > 5的情況
> 以及似乎比範例多輸出了*右邊的空格們

已解決，謝謝！
