### ISSUE TITLE
[General] 停車費 II

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#43]
## 提交連結

https://judge.ccclub.io/problem/181205
## 程式碼

```python

```

## 問題描述

Sample Input 2應該是貼錯了，結果不會等於Sample Output 2

**Comment by sc090410** [comment]
謝謝提醒，前陣子在搬移的過程中可能有點問題

**Comment by yles840421** [comment]
原來~感謝更正!
