### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by ChiHsinTseng** [coding-coworking-club/basic-python-2020-fall#44]
## 提交連結

https://judge.ccclub.io/problem/180013
## 程式碼

```python
a = input()
b = input()
c = input()
d = a.split(" ")
e = b.split(" ")

if c in d or c in e:
    print('true')
else:
    print('false')

```

## 問題描述

在 Jupyter 上面測試是正確的但放到 Judge 上是顯示 wrong answer

**Comment by Neptune2901** [comment]
輸出 True 或 False
大小寫...嗎?

**Comment by ChiHsinTseng** [comment]
> 輸出 True 或 False
> 大小寫...嗎?

對了！！謝謝你～～

**Comment by Huang-0000** [comment]
lst1 = str(input())
lst2 = str(input())
s = str(input())
if s in (lst1.split() or lst2.split()):
    print("True")
else:
    print("False")

在 Jupyter  Notebook 上測試是正確的，但放到 Judge 上是卻顯示 wrong answer。
