### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by candyho-learning** [coding-coworking-club/basic-python-2020-fall#45]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203101

## 程式碼

```
star = '*'
layer = int(input())

for a in range(layer):
    print(" " * (layer-1-a),star * (1 + 2 * a))
    
for b in range(layer-1):
    print(" " * (b+1),star * (2 * (layer-1) -1 - 2 * b))

```
## 問題描述

助教你好，這題我在編輯器上反覆測試不同數字看起來都對，但在Judge上顯示 wrong answer，請助教指點哪邊出問題，謝謝！

**Comment by tcwang76** [comment]
用print(a, b)的方法，Python會自動在a和b中間加一個空格做分隔唷
建議可以用"+"的方式把前後字串連起來

**Comment by candyho-learning** [comment]
謝謝，已解決，但為何肉眼看不出來本來用 " , "的時候有空格xD
