### ISSUE TITLE
[General] 日期計算

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#47]
## 提交連結

https://judge.ccclub.io/status/7ab4a8c5076aba192bac3be956ba88c0
## 程式碼

```python
import datetime

d1=input().split()
d1="-".join(d1)
n=int(input())
d1=datetime.datetime.strptime(d1,"%Y-%m-%d")
day=d1+datetime.timedelta(days=n)
print(str(day)[:10])
```

## 問題描述

您好，我自己在測試範例題都正常，但批改系統顯示Runtime error，想請問是何種測資導致無法通過呢，謝謝!

**Comment by Neptune2901** [comment]
[strftime及strptime doc](https://docs.python.org/3.8/library/datetime.html#strftime-strptime-behavior)
看起來是年份沒給四位數就會壞掉

**Comment by yles840421** [comment]
原來%Y一定要四位數!
已用zfill解決，感謝解惑~!
