### ISSUE TITLE
[Homework １] 印菱形

### ISSUE THREAD

**Issue by peichen12345** [coding-coworking-club/basic-python-2020-fall#49]
## 程式碼
r = int (input())
for i in range(r):
    for j in range(r - i):
        print(" ", end = "")
        j += 1
    for k in range(2 * i - 1):
        print("*", end = "")
        k += 1
    print("\n")
    i += 1
for i in range(r):
    for j in range(i):
        print(" ", end = "")
        j += 1
    for k in range(2 * (r - i) - 1):
        print("*", end = "")
        k += 1
    print("\n")
    i += 1

```python

```

## 問題描述
在## 提交連結

## 程式碼

```python

```

## 問題描述
在ｊｕｐｙｔｅｒ　ｎｏｔｅｂｏｏｋ跑出的程式沒有問題，但在網頁上跑出ｗｒｏｎｇ　ｅｒｒｏｒ

**Comment by chun9425** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結及程式碼
