### ISSUE TITLE
[General] 4-2：及格分數

### ISSUE THREAD

**Issue by Mahungchi** [coding-coworking-club/basic-python-2020-fall#5]
## 提交連結

https://judge.ccclub.io/status/3e22e12efa1e6d661eaa12cec190e31a

## 程式碼

```python
n = input()

if (int(n)>=60) and (int(n)<=100):
    print("PASS")
elif (int(n)>=0) and (int(n)<60):
    print("Fail")
else:
    print("Error")
```

## 錯誤訊息

ccClub Judge系統判定為Wrong Answer

## 問題描述

在Jupyter Notebook上面編譯都正常無誤，不知道為什麼ccClub Judge系統判斷這個是Wrong Answer

**Comment by jeffery12697** [comment]
題目是說 ‘Pass' 不是 'PASS'

**Comment by Mahungchi** [comment]
抱歉，自己眼殘囧
目前已經順利通過，謝謝
