### ISSUE TITLE
[General] 1-1：輸出兩次

### ISSUE THREAD

**Issue by er258er258** [coding-coworking-club/basic-python-2020-fall#51]
## 程式碼

    a = input("Pine")
    b = input("Apple")
    print(a + b)
    a = input("Pine")
    b = input("Apple")
    print(a + b)

```python

```

## 問題描述

只能印出Pine且不確定輸出兩次是否可以有其他方式處理，不用打兩次

**Comment by winnywu508** [comment]
你現在把 =input() 跟assign a爲”Pine"值 搞混在一起了喔
所以你跑這個code的時候會印出Pine再加上你輸入為a的值

我覺得你可以再複習一下udemy+ Medium

udemy: section 2 - 7: 輸入以及輸出
https://www.udemy.com/course/ccclub-python-for-beginners/learn/lecture/7530194#questions

Medium: 第一講
https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-71f55bccb693

**Comment by er258er258** [comment]
好的感謝解答
