### ISSUE TITLE
[Homework 1] 小明買宵夜

### ISSUE THREAD

**Issue by joyce-JC** [coding-coworking-club/basic-python-2020-fall#52]
## 提交連結

2ddd6845125d

## 程式碼

```python

m = input()
m = m.split(" ")

p = input()
p = p.split(" ")

money = int(input())

for i in range(len(p)):
    if str(money - int(p[i])) in p:
        a = int(p[i])
        b = int(money - int(p[i]))
    else:
        break

A = p.index(str(a))
B = p.index(str(b))

print(A,B)

print(m[A], m[B])

```

## 問題描述

發現自己有邏輯盲點，一直找不出錯在哪裡。
另外，曾經一次提交後出現「compile Error」，不太確定這是什麼意思，想請教助教這種情況該如何訂正。
再麻煩了，非常感謝！

**Comment by Neptune2901** [comment]
提交連結給的不對唷 應該是sumission左邊ID點進去的連結

**Comment by joyce-JC** [comment]
> 提交連結給的不對唷 應該是sumission左邊ID點進去的連結

不好意思，已重新貼上ID連結，再麻煩指教！

**Comment by lazyYC** [comment]
你好（我不是助教），
我想應該是少考慮到總預算剛好等於某餐點的兩倍價格這個情況，
可能會跑出符合你設的條件判斷，但不符合題目要求的結果。

**Comment by yeutong** [comment]
感謝 @lazyYC  幫忙回覆～
面對 `總預算剛好等於某餐點的兩倍價格` 的情形，的確會讓程式輸出錯誤的答案。儘管這次測資中其實沒有這樣的陷阱（未來會考慮加上去的XD），但這個觀察真的很棒！

@joyce-JC 
`compile error` 是指編譯錯誤，通常是 if 或 for loop 行尾忘記加上冒號，或是縮排錯誤所導致的。另外你可以試試
```
a b c
1 2 3
5
```
看看是哪裡在搞鬼吧！

**Comment by joyce-JC** [comment]
> 感謝 @lazyYC 幫忙回覆～
> 面對 `總預算剛好等於某餐點的兩倍價格` 的情形，的確會讓程式輸出錯誤的答案。儘管這次測資中其實沒有這樣的陷阱（未來會考慮加上去的XD），但這個觀察真的很棒！
> 
> @joyce-JC
> `compile error` 是指編譯錯誤，通常是 if 或 for loop 行尾忘記加上冒號，或是縮排錯誤所導致的。另外你可以試試
> 
> ```
> a b c
> 1 2 3
> 5
> ```
> 
> 看看是哪裡在搞鬼吧！

好的！非常感謝！
