### ISSUE TITLE
[Homework 1] 小明買宵夜

### ISSUE THREAD

**Issue by troublecat55** [coding-coworking-club/basic-python-2020-fall#53]
## 提交連結

https://judge.ccclub.io/status/69cb28023d5395353047162ff376940c

## 程式碼

```python

```

## 問題描述

我已經用O(n^2)(nested array)跟O(n)(hash table)解過這一題了，所以我的問題跟作業submission比較沒有關聯，只是我太好奇問的，希望不要invalid
最近很巧的，我在Leecode上看到跟這題類似的題目：https://leetcode.com/problems/two-sum/
看到有人用Two pointer的方式來解：https://leetcode.com/problems/two-sum/discuss/287/Python-solution-with-detailed-explanation
但是我看不懂這種解法，希望能得到助教的解釋
非常感謝！

**Comment by yeutong** [comment]
嗨~ 任何與程式相關的問題都非常歡迎在 GitHub 發問，或單純拋出來討論也可以！只有格式錯誤的情況才會標記 `invalid` XD

two pointer 是先將串列由小到大排好，分別把兩個指標指向左右兩端。假設答案是 a、b，且 a < b，那麼我們的目標就是最終要讓左邊指標指向 a，右邊指標指向 b。
接著不斷比較指標現在指向的兩數之和比目標更大或更小。
因為一開始指向兩端，所以可以保證左邊指標在 a 或 a 的左方，右邊指標在 b 或 b 的右方。
在比較的過程中，若指標指向兩數之和比目標大，就表示至少右邊指標還在 b 的右方，因此將右邊指標左移一格。
反之，若指標指向兩數之和比目標小，就表示至少左邊指標還在 a 的左方，因此將左邊指標右移一格。
然後重複這個過程就可以找到答案嘍！

如果還是不太清楚可以參考看 [這篇文章](https://blog.techbridge.cc/2019/08/30/leetcode-pattern-two-pointer/)
另外要注意 sort 過之後 index 就會改變了（如同在 leetcode 討論區留言提及的一樣），會需要另外存起來之類的~

**Comment by troublecat55** [comment]
你給的連結實在太有用啦，非常感謝你！
