### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by daisy41030** [coding-coworking-club/basic-python-2020-fall#58]
## 程式碼

```n=int(input('enter row number'))
for i in range(n):
    print(" "*(n-i-1)+"*"*(2*i+1))
for i in range(n-1):
    print(" ")*(i+1)+"*"*(2*(2-i)+1)

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/71951575/94356022-a5c9fc00-00c4-11eb-9251-82e791ae0dd5.png)

## 問題描述

菱形最後呈現出來的只有上半部，下半部出不來

**Comment by Neptune2901** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結、錯誤訊息、及問題描述

**Comment by daisy41030** [comment]
> 請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結、錯誤訊息、及問題描述

已更新～

**Comment by chun9425** [comment]
你最後一行程式碼的括號有點對不太起來，
你先修正完括號的問題再想想看
