### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by tmousecello** [coding-coworking-club/basic-python-2020-fall#63]
## 程式碼

n = int(input())
a="*"
b=" "
for i in range(n+1):
	print(b*(n-i) +(i*2-1)*a)
	i+=1
for c in range(n):
	print(b*(c+1) + (i*2-5)*a)
	i-=1
	c+=1

```n = int(input())
a="*"
b=" "
for i in range(n+1):
	print(b*(n-i) +(i*2-1)*a)
	i+=1
for c in range(n):
	print(b*(c+1) + (i*2-5)*a)
	i-=1
	c+=1


```

## 錯誤訊息
若有錯誤訊息請提供截圖，若無則請留空。 

## 問題描述

程式碼跑出來的結過是正確的 但系統卻說worong answer

**Comment by chun9425** [comment]
你印出來的東西跟 output 不一樣，
菱形的上下都會多印兩排
