### ISSUE TITLE
[General] 1-1：輸出兩次

### ISSUE THREAD

**Issue by Jingyinguo** [coding-coworking-club/basic-python-2020-fall#64]
## 程式碼

```python
s1="Pine"
s2="Apple"
print(s1+s2)
print(s1+s2)

s3="Python"
s4="Class"
print(s3+s4)
print(s3+s4)

```

## 問題描述

電腦上跑沒問題，但提交後卻說是wrong answer

**Comment by chun9425** [comment]
題目的意思其實是要寫一個程式，
這個程式可以讓使用者輸入兩個資料，
然後不管使用者輸入的內容是什麼，
都把第一個輸入的內容跟第二個輸入的內容輸出兩次

你的想法是對的沒錯
但不是要明確的定出 s1, s2, s3, s4
而是要用 input() 讓使用者輸入資料
