### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by ianyeh0521** [coding-coworking-club/basic-python-2020-fall#67]
## 程式碼

```python
a=int(input())
for i in range(1,a+1):
    print(" "*(a-i)+"*"*(2*i-1)+" "*(a-i))
    i+=1
for i in range(a+1,2*a):
    print(" "*(i-a)+"*"*((2*a-1)-2*(i-a))+" "*(i-a))
    i+=1
```

## 錯誤訊息

![螢幕擷取畫面 (259)](https://user-images.githubusercontent.com/71587400/94368043-bbffa880-0114-11eb-8f7f-18a7e47ba31a.png)

## 問題描述

經jupyter notebook 測試完應該是沒問題的，但批改系統顯示wrong answer，想請問是何處出錯了，謝謝

**Comment by yles840421** [comment]
這個右邊不用空格的，右方的" "得刪掉

**Comment by ianyeh0521** [comment]
謝謝!
