### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by chiangkylechun** [coding-coworking-club/basic-python-2020-fall#70]
## 提交連結

https://judge.ccclub.io/status/e3dea31f0e8958042ed1be048ed05951

## 程式碼

```python
a,b,c,d=int(input()),int(input()),int(input()),int(input())
e=[]

if a <=0 or b <=0 or c <=0 or d <=0:
  print("False")
else:
  for i in range(c):
    if a*i+b*(c-i)==d:
      if i==0:
        e.append("False")
      else:
        e.append("True")
    else:
      e.append("False")
  if "True" in e:
    print("True")
  else:
    print("False")
```

## 問題描述

在Repl上拿sample測試都是沒問題的，解題的想法是確定輸入的整數都是正整數後，用range的方式一組一組帶入解(組內不能有0出現)，存成一個list，再看這個list裡有沒有解。如果有解(True)的話就print("True")，沒有的話就print("False")。但批改系統還是不給過，不知道還有哪裡沒注意到，想請助教看一下。謝謝！

**Comment by yeutong** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結、錯誤訊息，以利助教協助查看問題所在喲~

你的想法是可行的，但要注意若有不止一組正整數解，也要判定為不合格的題目

**Comment by chiangkylechun** [comment]
> 請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結、錯誤訊息，以利助教協助查看問題所在喲~
> 
> 你的想法是可行的，但要注意若有不止一組正整數解，也要判定為不合格的題目

已附上連結。
謝謝，我再想一下。

**Comment by chiangkylechun** [comment]
> 請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結、錯誤訊息，以利助教協助查看問題所在喲~
> 
> 你的想法是可行的，但要注意若有不止一組正整數解，也要判定為不合格的題目

最後把""不止一組正整數解，也要判定為不合格的題目"這個條件加上去就通過了！謝謝！
https://judge.ccclub.io/status/eae1f8ae176c4e3ff72f332b8dcffee2
