### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by HangC1112** [coding-coworking-club/basic-python-2020-fall#73]
## 提交連結

https://judge.ccclub.io/status/f93d362d1270cb07b68fa7f588dce109

## 程式碼

```python
n1,n2,suit,bat= int(input()),int(input()),int(input()),int(input())
i=(bat-n2*suit)/(n1-n2)
b=suit-i
if i<=0 or b<=0 or i%1!=0 or b%1!=0:
	print("False")
else:
	print("True")
```

## 問題描述

在judge系統上顯示runtime error 但不知道自己錯在哪邊，jupyter上都是OK的

**Comment by yeutong** [comment]
如果 n1 = n2 就會發生 ZeroDivisionError 喲！

**Comment by HangC1112** [comment]
> 如果 n1 = n2 就會發生 ZeroDivisionError 喲！

可是多加了條件那行改成 if n1-n2==0 or i<=0 or b<=0 or i%1!=0 or b%1!=0:
還是錯誤QQ 快瘋了

**Comment by yeutong** [comment]
一直無法通過真的心很累我知道，但還是盡量先自己做過測試再丟到 judge 上面
你試試看在 jupyter 上輸入 n1 與 n2 相同數值的測資，應該就知道為什麼了！

**Comment by HangC1112** [comment]
後來google如何除錯候用這樣通過了 但是用了迴圈跟3個break 想問助教有沒有更好的寫法?

**************防雷**************
**************防雷**************
**************防雷**************



while 1:
    try:
        n1,n2,suit,bat= int(input()),int(input()),int(input()),int(input())

        i=(bat-n2*suit)/(n1-n2)
        b=suit-i
    except :
        print('False')
        break
    if i>0 and b>0 and i%1==0 and b%1==0:
        print("True")
        break
    else:
        print('False')
        break

**Comment by yeutong** [comment]
如果先用 if 判斷 n1 跟 n2 是不是相等，再進行其他判斷，就可以省去使用 try except 了
