### ISSUE TITLE
[General] 3-1 字串強度、jupyter notebook上可以跑

### ISSUE THREAD

**Issue by sandy273040** [coding-coworking-club/basic-python-2020-fall#78]
## 提交連結

https://judge.ccclub.io/status/181402062dd7374660b0fe009ff8314a

## 程式碼

a=input("")
b=int(input(""))
if len(a)== b: 
    print("true")
else:
    print("false")

```python

```

## 問題描述

這個程式碼在jupyter notebook可以跑出來，但在judge 上卻不行，想請問助教是哪裡需要修正？
思路上是輸入一個字串在a、輸入一個數字在b，如果a字串長度等於b數字，印出true，若不相同印出false

**Comment by alexypdu** [comment]
`input()` 裡面不要放 `""`？

**Comment by sandy273040** [comment]
已解決，是True 和 False 大小寫問題
