### ISSUE TITLE
[Homework 1] 小明寫論文

### ISSUE THREAD

**Issue by dami951753** [coding-coworking-club/basic-python-2020-fall#80]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203105

## 程式碼

 a=input()
 a1=a.title()
 b=a1.split(' ')
 s=["To","A","An","The","And","From","In","For","Of"]
 i=1
 while i<len(b)-1:
     if b[i] in s:
         b[i]=b[i].lower()
     i=i+1
 d=" ".join(b)
 print(d)

```python

```

## 問題描述

在jupyter notebook 可以順利執行，但在Judge卻出現wrong answer，想請問邏輯方面哪裡出現問題?

**Comment by yeutong** [comment]
這個是題目連結不是提交連結，以及程式碼要放在兩個 ``` 中間，請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)將格式修正噢！

可以參考 #22 的討論，應該可以幫到你！
