### ISSUE TITLE
[General] 合併串列

### ISSUE THREAD

**Issue by yles840421** [coding-coworking-club/basic-python-2020-fall#86]
## 提交連結

https://judge.ccclub.io/status/2f47c9ca52d915aa5d969081baeeaa67
## 程式碼

```python
n=input().split()
m=input().split()

n.extend(m)
n.sort()

print(" ".join(n))
```

## 問題描述

您好，我有點不太懂這題題意，input提到的n跟output的n是同一個數字嗎?
假如是，那example的範例就不符題意
假如兩個n是不相干的數，那我的寫法應該對才是?(經測試符合兩個example的結果)

**Comment by winnywu508** [comment]
你的logic 是對的
把output寫成integer試試看

**Comment by winnywu508** [comment]
發問的subject title記得加問題的號碼

**Comment by yles840421** [comment]
您好，感謝回復! 
在改為int輸出後還是錯誤，而且output應該不會區分是int還是str形式的數字的樣子?
(如: print(" ".join(["1","2","3"])) 跟 print(1,2,3)應該相等才對?)

另外，因為這題位在第四頁，沒有 X-X題號，因此沒有附上~!

**Comment by yles840421** [comment]
發現原因了! 我需要先轉換成int形式來做sorting，原先是str形式就sorting，感謝解惑!
