### ISSUE TITLE
[Week 3] 中位數

### ISSUE THREAD

**Issue by er258er258** [coding-coworking-club/basic-python-2020-fall#87]
## 提交連結

https://judge.ccclub.io/status/5910c0bfcf6ec223adabfeeebb25c869

## 程式碼

i = [6,28,426]
x = len(i)
if int(x) % 2==0:
    b=int(x) // 2
    b=i[b]+i[b-1]
    b=b/2
    print(b)
else:
    b=int(x) // 2
    b=i[b]
    print(float(b))

```python

```

## 錯誤訊息

Wrong Answer

## 問題描述

看不出來問題主要在哪

**Comment by winnywu508** [comment]
code放的位子請看notion 

i 要改成input() 現在i 只能是固定的[6,28,426]
