### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by yihan-lin** [coding-coworking-club/basic-python-2020-fall#89]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203103
## 程式碼

```
a = input()
remove_doc = a.replace(",","")
lst_a = remove_doc.split()
number = lst_a[:len(lst_a)-1]
answer=0
for i in range(0,len(number)):
    answer += int(number[i])
final = "{:,}".format(answer)
print(final)

```

## 錯誤訊息

Wrong Answer
## 問題描述
我在Jupyter上有跑出答案，但在Judge系統錯誤，我後來在想會不會是input的問題，但不知道要怎麼輸入n個input，本來想用迴圈，但因為n也不知道有幾個，所以也不能定義n......但我不確定是不是這個問題，還是我本來打的就有問題，還請助教救命,,,,,,謝謝!!

**Comment by yeutong** [comment]
的確是 input() 的問題，可以參考[這篇 medium 文章](https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-4990a5757aa6)，了解關於 while 迴圈的使用喲～
