### ISSUE TITLE
[Homework 1] 印菱形

### ISSUE THREAD

**Issue by Chiahsin13** [coding-coworking-club/basic-python-2020-fall#90]
## 程式碼

```python
n=int(input())
x=" "
y="*"
for i in range(1,n+1):
    print(x*(n-i), y*(2*i-1), x*(n-i))
for z in range(1,n):
    print(x*z, y*(2*n-2*z-1), (x*z))
```

**Comment by misvap** [comment]
嗨！我不是助教，我幫你測了之後，有幾點發現，以下跟你分享。

錯誤：print() 的結果整個往後移了一個空白鍵，且"*" 右側不需再印空白。

參考方向：
1. print(a, b) 以及 print(a+b) 不同：
    print(a, b) 時，印出的 a 和 b 中間有一個空白鍵; 而 print(a+b) 的 a 和 b 中間則沒有空白鍵。

**Comment by Chiahsin13** [comment]
謝謝你的幫忙，多嘗試幾次成功了：Ｄ
