### ISSUE TITLE
[General] 7-1：長方星

### ISSUE THREAD

**Issue by tziyingchen** [coding-coworking-club/basic-python-2020-fall#92]
## 提交連結

--

https://judge.ccclub.io/status/181e70cb400703f711cd45b2ac3339a9
## 程式碼

```python
width, height= int(input()), int(input())
for a in range(height):
    for b in str(width):
        print('*' * int(width))
```

## 問題描述

在jupyter notebook上測試正確，但是Judge顯示為wrong answer, 是否是哪裡沒有思考完整?

**Comment by yeutong** [comment]
可以試試看高度、寬度都是 11 的情況
