### ISSUE TITLE
[Homework 1] 出題目

### ISSUE THREAD

**Issue by yihan-lin** [coding-coworking-club/basic-python-2020-fall#93]
## 提交連結

https://judge.ccclub.io/contest/4/problem/203102
## 程式碼

```python
S_Battery = int(input())
B_Battery = int(input())
cloth = int(input())
Battery = int(input())
X = (B_Battery * cloth - Battery)/ (B_Battery - S_Battery)
Y = (Battery - cloth * S_Battery)/ (B_Battery - S_Battery)
if int(X) == X and X>0 and int(Y) == Y and Y>0:
    print("True")     
else:
    print("False")
```

## 錯誤訊息

Runtime error
## 問題描述

我不知道錯在哪裡，在自己的編輯器上都是正確的....謝謝助教

**Comment by misvap** [comment]
嗨！我不是助教，跟你分享一下我的想法：

第 5 行和第 6 行都有 (B_Battery - S_Battery) 在分母。

在 Python 裡面，如果分母為零的話，這時候的 error 原因會是 Zero Division Error。可以思考 B_Battery == S_Battery（即 B_Battery - S_Battery == 0）時的狀況。

**Comment by yihan-lin** [comment]
謝謝您!!!考慮到了之後就成功了!!感激這位同學!!
