### ISSUE TITLE
[Homework 1] 會計數字處理

### ISSUE THREAD

**Issue by evetyy** [coding-coworking-club/basic-python-2020-fall#98]
## 提交連結
https://judge.ccclub.io/status/dee160b5fc57ef3535f9e156924c1ab3

## 程式碼

```python
data = [input()]
total = 0

for i in data:
    i.replace(',', '')
for i in range(len(data)):
    total += data[0:i]
print(total)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/71555507/94763556-277b9b80-03dd-11eb-893f-2552772c731c.png)

## 問題描述

試了好幾次還是錯誤, 找不出原因... judge系統顯示Runtime Error

**Comment by yeutong** [comment]
錯誤訊息的意思是你不能把數字跟串列相加，其中 `total` 是數字，`data` 是串列(List)，`data[0:I]` 則代表 `data` 這個串列中的第 0 到 第 i - 1 個元素。
可以參考社團中關於作業一的提示來思考怎麼修改程式～加油！

**Comment by evetyy** [comment]
謝謝助教~ 修改好幾次後，測試Sample input 1沒問題，但測試Sample input 2 的輸出會變成1613,18,779。用Trace code測試發現是在第一次插入"," 後， s 串列內的各個位置會改變。因為試了很久一直寫不出解法，想請助教幫忙看看，謝謝助教!

答案連結：https://judge.ccclub.io/status/86b321ca821a3c76b09e2efa4fd4dd16

![image](https://user-images.githubusercontent.com/71555507/95007273-7bd28580-0640-11eb-91cb-9f9b2fe16e55.png)

**Comment by huaitzu** [comment]
你設定插入`,`的條件為：
```
if i % 3 == 2 and i < len(str(total))-1:
    s.insert(i+1, ",")
    print(s)
```
因為你在跑for迴圈的list裡面插入新的東西，所以list內的index會改變。也就是說當你在`s[3]`的位置插入`,`，`,`的index就會變成 3，而後面的就會跟著順延，所以`s[5]`的字串就會從 '3' 變成 '1'。

雖然HW1的提示內是以字串的形式來解決這題，但概念上是一樣的，如果你想要用list來處理這題的話，可以依照提示的脈絡，來思考看看結果輸出的部分要怎麼設計

另外，答案輸出只有一個，你的迴圈內有放入print，這樣會輸出好幾次喔~


> 謝謝助教~ 修改好幾次後，測試Sample input 1沒問題，但測試Sample input 2 的輸出會變成1613,18,779。用Trace code測試發現是在第一次插入"," 後， s 串列內的各個位置會改變。因為試了很久一直寫不出解法，想請助教幫忙看看，謝謝助教!
> 
> 答案連結：https://judge.ccclub.io/status/86b321ca821a3c76b09e2efa4fd4dd16
> 
> ![image](https://user-images.githubusercontent.com/71555507/95007273-7bd28580-0640-11eb-91cb-9f9b2fe16e55.png)
